### ISSUE TITLE
[bug] Attempt to add Sales Invoice was fault

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#10404]
# 🐞 bug report

### ⁉️ Describe the bug

At current gitdev I tried to add new Sales Invoice and get errors after clicking save

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

```
Notice: A non well formed numeric value encountered in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/app/Validator.php on line 210

Warning: vsprintf(): Too few arguments in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/vtlib/Vtiger/Functions.php on line 421
```

```
App\Exceptions\Security: ERR_ILLEGAL_FIELD_VALUE||total in modules/Vtiger/inventoryfields/TotalPrice.php:66
Stack trace:
#0 modules/Vtiger/inventoryfields/Basic.php(508): Vtiger_TotalPrice_InventoryField->validate(3196.64, 'total', true, '3 196.64')
#1 modules/Vtiger/models/Record.php(1217): Vtiger_Basic_InventoryField->setValueToRecord(Object(FInvoice_Record_Model), Array, true)
#2 modules/Vtiger/models/Record.php(1242): Vtiger_Record_Model->initInventoryData(Array)
#3 modules/Vtiger/actions/Save.php(123): Vtiger_Record_Model->initInventoryDataFromRequest(Object(App\Request))
#4 modules/Vtiger/actions/Save.php(87): Vtiger_Save_Action->getRecordModelFromRequest(Object(App\Request))
#5 modules/Vtiger/actions/Save.php(61): Vtiger_Save_Action->saveRecord(Object(App\Request))
#6 include/main/WebUI.php(182): Vtiger_Save_Action->process(Object(App\Request))
#7 index.php(24): Vtiger_WebUI->process(Object(App\Request))
#8 public_html/index.php(11): require('/home/gitdevelo...')
#9 {main}
```

```
#0 [info] SELECT * FROM `vtiger_tab` || yii\db\Command::query
#1 [info] Opening DB connection: mysql:host=localhost;dbname=gitdevelop_crm;port=3306 || yii\db\Connection::open
#2 [info] SELECT * FROM `vtiger_entityname` || yii\db\Command::query
#3 [trace] Entering getColumnFields(FInvoice) method ...
#4 [info] SELECT * FROM `vtiger_field` WHERE `tabid`=95 || yii\db\Command::query
#5 [trace] Exiting getColumnFields method ...
#6 [info] SELECT * FROM `vtiger_actionmapping` || yii\db\Command::query
#7 [info] SELECT `vtiger_field`.* FROM `vtiger_field` LEFT JOIN `vtiger_blocks` ON vtiger_field.block = vtiger_blocks.blockid WHERE `vtiger_field`.`tabid`=95 ORDER BY `vtiger_blocks`.`sequence`, `vtiger_field`.`sequence` || yii\db\Command::query
#8 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=310 LIMIT 1 || yii\db\Command::query
#9 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=311 LIMIT 1 || yii\db\Command::query
#10 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=312 LIMIT 1 || yii\db\Command::query
#11 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=398 LIMIT 1 || yii\db\Command::query
#12 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=399 LIMIT 1 || yii\db\Command::query
#13 [trace] Entering App\Field::getFieldPermission: 95,subject
#14 [trace] Entering App\Field::getFieldsPermissions: 95
#15 [info] SELECT DISTINCT `vtiger_field`.`fieldid`, `vtiger_field`.`fieldname`, `vtiger_field`.`columnname`, `vtiger_profile2field`.`readonly`, `vtiger_profile2field`.`visible` FROM `vtiger_field` INNER JOIN `vtiger_profile2field` ON vtiger_profile2field.fieldid = vtiger_field.fieldid WHERE ((`vtiger_field`.`tabid`=95) AND (`vtiger_profile2field`.`visible`=0) AND (`vtiger_field`.`visible`=0) AND (`vtiger_field`.`presence` IN (0, 2))) AND (`vtiger_profile2field`.`profileid`=1) || yii\db\Command::query
#16 [info] SELECT * FROM `vtiger_ws_fieldtype` || yii\db\Command::query
#17 [trace] Entering App\Field::getFieldPermission: 95,subject
#18 [trace] Entering App\Field::getFieldsPermissions: 95
#19 [trace] Entering App\Field::getFieldPermission: 95,paymentdate
#20 [trace] Entering App\Field::getFieldsPermissions: 95
#21 [trace] Entering App\Field::getFieldPermission: 95,paymentdate
#22 [trace] Entering App\Field::getFieldsPermissions: 95
#23 [trace] Entering App\Field::getFieldPermission: 95,saledate
#24 [trace] Entering App\Field::getFieldsPermissions: 95
#25 [trace] Entering App\Field::getFieldPermission: 95,saledate
#26 [trace] Entering App\Field::getFieldsPermissions: 95
#27 [trace] Entering App\Field::getFieldPermission: 95,issue_time
#28 [trace] Entering App\Field::getFieldsPermissions: 95
#29 [trace] Entering App\Field::getFieldPermission: 95,issue_time
#30 [trace] Entering App\Field::getFieldsPermissions: 95
#31 [trace] Entering App\Field::getFieldPermission: 95,finvoice_formpayment
#32 [trace] Entering App\Field::getFieldsPermissions: 95
#33 [trace] Entering App\Field::getFieldPermission: 95,finvoice_formpayment
#34 [trace] Entering App\Field::getFieldsPermissions: 95
#35 [trace] Entering App\Field::getFieldPermission: 95,accountid
#36 [trace] Entering App\Field::getFieldsPermissions: 95
#37 [trace] Entering App\Field::getFieldPermission: 95,accountid
#38 [trace] Entering App\Field::getFieldsPermissions: 95
#39 [trace] Entering App\Field::getFieldPermission: 95,finvoice_paymentstatus
#40 [trace] Entering App\Field::getFieldsPermissions: 95
#41 [trace] Entering App\Field::getFieldPermission: 95,finvoice_paymentstatus
#42 [trace] Entering App\Field::getFieldsPermissions: 95
#43 [trace] Entering App\Field::getFieldPermission: 95,finvoice_status
#44 [trace] Entering App\Field::getFieldsPermissions: 95
#45 [trace] Entering App\Field::getFieldPermission: 95,finvoice_status
#46 [trace] Entering App\Field::getFieldsPermissions: 95
#47 [trace] Entering App\Field::getFieldPermission: 95,private
#48 [trace] Entering App\Field::getFieldsPermissions: 95
#49 [trace] Entering App\Field::getFieldPermission: 95,private
#50 [trace] Entering App\Field::getFieldsPermissions: 95
#51 [trace] Entering App\Field::getFieldPermission: 95,finvoice_type
#52 [trace] Entering App\Field::getFieldsPermissions: 95
#53 [trace] Entering App\Field::getFieldPermission: 95,finvoice_type
#54 [trace] Entering App\Field::getFieldsPermissions: 95
#55 [trace] Entering App\Field::getFieldPermission: 95,pscategory
#56 [trace] Entering App\Field::getFieldsPermissions: 95
#57 [trace] Entering App\Field::getFieldPermission: 95,pscategory
#58 [trace] Entering App\Field::getFieldsPermissions: 95
#59 [trace] Entering App\Field::getFieldPermission: 95,ssalesprocessesid
#60 [trace] Entering App\Field::getFieldsPermissions: 95
#61 [trace] Entering App\Field::getFieldPermission: 95,ssalesprocessesid
#62 [trace] Entering App\Field::getFieldsPermissions: 95
#63 [trace] Entering App\Field::getFieldPermission: 95,projectid
#64 [trace] Entering App\Field::getFieldsPermissions: 95
#65 [trace] Entering App\Field::getFieldPermission: 95,projectid
#66 [trace] Entering App\Field::getFieldsPermissions: 95
#67 [trace] Entering App\Field::getFieldPermission: 95,in_portal
#68 [trace] Entering App\Field::getFieldsPermissions: 95
#69 [trace] Entering App\Field::getFieldPermission: 95,in_portal
#70 [trace] Entering App\Field::getFieldsPermissions: 95
#71 [trace] Entering App\Field::getFieldPermission: 95,number
#72 [trace] Entering App\Field::getFieldsPermissions: 95
#73 [trace] Entering App\Field::getFieldPermission: 95,number
#74 [trace] Entering App\Field::getFieldsPermissions: 95
#75 [trace] Entering App\Field::getFieldPermission: 95,assigned_user_id
#76 [trace] Entering App\Field::getFieldsPermissions: 95
#77 [trace] Entering App\Field::getFieldPermission: 95,assigned_user_id
#78 [trace] Entering App\Field::getFieldsPermissions: 95
#79 [trace] Entering App\Field::getFieldPermission: 95,createdtime
#80 [trace] Entering App\Field::getFieldsPermissions: 95
#81 [trace] Entering App\Field::getFieldPermission: 95,createdtime
#82 [trace] Entering App\Field::getFieldsPermissions: 95
#83 [trace] Entering App\Field::getFieldPermission: 95,modifiedtime
#84 [trace] Entering App\Field::getFieldsPermissions: 95
#85 [trace] Entering App\Field::getFieldPermission: 95,modifiedtime
#86 [trace] Entering App\Field::getFieldsPermissions: 95
#87 [trace] Entering App\Field::getFieldPermission: 95,sum_total
#88 [trace] Entering App\Field::getFieldsPermissions: 95
#89 [trace] Entering App\Field::getFieldPermission: 95,sum_total
#90 [trace] Entering App\Field::getFieldsPermissions: 95
#91 [trace] Entering App\Field::getFieldPermission: 95,sum_gross
#92 [trace] Entering App\Field::getFieldsPermissions: 95
#93 [trace] Entering App\Field::getFieldPermission: 95,sum_gross
#94 [trace] Entering App\Field::getFieldsPermissions: 95
#95 [trace] Entering App\Field::getFieldPermission: 95,shownerid
#96 [trace] Entering App\Field::getFieldsPermissions: 95
#97 [trace] Entering App\Field::getFieldPermission: 95,shownerid
#98 [trace] Entering App\Field::getFieldsPermissions: 95
#99 [trace] Entering App\Field::getFieldPermission: 95,addresslevel8a
#100 [trace] Entering App\Field::getFieldsPermissions: 95
#101 [trace] Entering App\Field::getFieldPermission: 95,addresslevel8a
#102 [trace] Entering App\Field::getFieldsPermissions: 95
#103 [trace] Entering App\Field::getFieldPermission: 95,localnumbera
#104 [trace] Entering App\Field::getFieldsPermissions: 95
#105 [trace] Entering App\Field::getFieldPermission: 95,localnumbera
#106 [trace] Entering App\Field::getFieldsPermissions: 95
#107 [trace] Entering App\Field::getFieldPermission: 95,buildingnumbera
#108 [trace] Entering App\Field::getFieldsPermissions: 95
#109 [trace] Entering App\Field::getFieldPermission: 95,buildingnumbera
#110 [trace] Entering App\Field::getFieldsPermissions: 95
#111 [trace] Entering App\Field::getFieldPermission: 95,poboxa
#112 [trace] Entering App\Field::getFieldsPermissions: 95
#113 [trace] Entering App\Field::getFieldPermission: 95,poboxa
#114 [trace] Entering App\Field::getFieldsPermissions: 95
#115 [trace] Entering App\Field::getFieldPermission: 95,addresslevel7a
#116 [trace] Entering App\Field::getFieldsPermissions: 95
#117 [trace] Entering App\Field::getFieldPermission: 95,addresslevel7a
#118 [trace] Entering App\Field::getFieldsPermissions: 95
#119 [trace] Entering App\Field::getFieldPermission: 95,addresslevel6a
#120 [trace] Entering App\Field::getFieldsPermissions: 95
#121 [trace] Entering App\Field::getFieldPermission: 95,addresslevel6a
#122 [trace] Entering App\Field::getFieldsPermissions: 95
#123 [trace] Entering App\Field::getFieldPermission: 95,addresslevel5a
#124 [trace] Entering App\Field::getFieldsPermissions: 95
#125 [trace] Entering App\Field::getFieldPermission: 95,addresslevel5a
#126 [trace] Entering App\Field::getFieldsPermissions: 95
#127 [trace] Entering App\Field::getFieldPermission: 95,addresslevel4a
#128 [trace] Entering App\Field::getFieldsPermissions: 95
#129 [trace] Entering App\Field::getFieldPermission: 95,addresslevel4a
#130 [trace] Entering App\Field::getFieldsPermissions: 95
#131 [trace] Entering App\Field::getFieldPermission: 95,addresslevel3a
#132 [trace] Entering App\Field::getFieldsPermissions: 95
#133 [trace] Entering App\Field::getFieldPermission: 95,addresslevel3a
#134 [trace] Entering App\Field::getFieldsPermissions: 95
#135 [trace] Entering App\Field::getFieldPermission: 95,addresslevel2a
#136 [trace] Entering App\Field::getFieldsPermissions: 95
#137 [trace] Entering App\Field::getFieldPermission: 95,addresslevel2a
#138 [trace] Entering App\Field::getFieldsPermissions: 95
#139 [trace] Entering App\Field::getFieldPermission: 95,addresslevel1a
#140 [trace] Entering App\Field::getFieldsPermissions: 95
#141 [trace] Entering App\Field::getFieldPermission: 95,addresslevel1a
#142 [trace] Entering App\Field::getFieldsPermissions: 95
#143 [trace] Entering App\Field::getFieldPermission: 95,description
#144 [trace] Entering App\Field::getFieldsPermissions: 95
#145 [trace] Entering App\Field::getFieldPermission: 95,description
#146 [trace] Entering App\Field::getFieldsPermissions: 95
#147 [trace] Entering App\Field::getFieldPermission: 95,attention
#148 [trace] Entering App\Field::getFieldsPermissions: 95
#149 [trace] Entering App\Field::getFieldPermission: 95,attention
#150 [trace] Entering App\Field::getFieldsPermissions: 95
#151 [info] SELECT * FROM `u_yf_finvoice_invfield` ORDER BY `block`, `sequence` || yii\db\Command::query
#152 [trace] Entering Vtiger_Record_Model::initInventoryData
#153 [trace] Entering Vtiger_Record_Model::getInventoryData
#154 [trace] Exiting Vtiger_Record_Model::getInventoryData
#155 [info] SELECT * FROM `vtiger_currency_info` || yii\db\Command::query
#156 [error] ERR_ILLEGAL_FIELD_VALUE||total
App\Exceptions\Security: ERR_ILLEGAL_FIELD_VALUE||total in modules/Vtiger/inventoryfields/TotalPrice.php:66
Stack trace:
#0 modules/Vtiger/inventoryfields/Basic.php(508): Vtiger_TotalPrice_InventoryField->validate(3196.64, 'total', true, '3 196.64')
#1 modules/Vtiger/models/Record.php(1217): Vtiger_Basic_InventoryField->setValueToRecord(Object(FInvoice_Record_Model), Array, true)
#2 modules/Vtiger/models/Record.php(1242): Vtiger_Record_Model->initInventoryData(Array)
#3 modules/Vtiger/actions/Save.php(123): Vtiger_Record_Model->initInventoryDataFromRequest(Object(App\Request))
#4 modules/Vtiger/actions/Save.php(87): Vtiger_Save_Action->getRecordModelFromRequest(Object(App\Request))
#5 modules/Vtiger/actions/Save.php(61): Vtiger_Save_Action->saveRecord(Object(App\Request))
#6 include/main/WebUI.php(182): Vtiger_Save_Action->process(Object(App\Request))
#7 index.php(24): Vtiger_WebUI->process(Object(App\Request))
#8 public_html/index.php(11): require('/home/gitdevelo...')
#9 {main}
```

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  gitdev 5.1.32

**Comment by rskrzypczak** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/commit/2271f1a237839f32dd84d314fb7173a40e5712bd
