### ISSUE TITLE
[PL][PYTANIE] Za długie maile

### ISSUE THREAD

**Issue by mrzewnicki** [YetiForceCompany/YetiForceCRM#10947]
Witam,

Mam problem ponieważ czasami nie mogę zaimportować maila nawet ręcznie ponieważ wartość jest zbyt długa. W system.log mam następującą informację:

```Stack trace:
#0 /var/www/html/my_path/YetiForce/modules/Vtiger/models/Record.php(531): Vtiger_Text_UIType->validate('<span style="vi...')
#1 /var/www/html/my_path/YetiForce/modules/Vtiger/models/Record.php(490): Vtiger_Record_Model->getValuesForSave()
#2 /var/www/html/my_path/YetiForce/modules/Vtiger/models/Record.php(461): Vtiger_Record_Model->saveToDb()
#3 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/scanneractions/CreatedEmail.php(56): Vtiger_Record_Model->save()
#4 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/models/Record.php(291): OSSMailScanner_CreatedEmail_ScannerAction->process(Object(OSSMail_Mail_Model))
#5 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/models/Record.php(378): OSSMailScanner_Record_Model::executeActions(Array, Object(OSSMail_Mail_Model), 'IN$
#6 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/models/Record.php(538): OSSMailScanner_Record_Model::mailScan(Resource id #291, Array, 'INBOX', 24581, 0)
#7 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/cron/action.php(14): OSSMailScanner_Record_Model->executeCron('cli - ')
#8 /var/www/html/my_path/YetiForce/cron.php(78): require_once('/var/www/html/Y...')
#9 {main}
2019-07-11 09:09:06.2524 [error][MailScanner] - App\Exceptions\Security: ERR_VALUE_IS_TOO_LONG||description|| <span class="preheader" style="visibility:hidd$
Stack trace:
#0 /var/www/html/my_path/YetiForce/modules/Vtiger/models/Record.php(531): Vtiger_Text_UIType->validate(' <span class="p...')
#1 /var/www/html/my_path/YetiForce/modules/Vtiger/models/Record.php(490): Vtiger_Record_Model->getValuesForSave()
#2 /var/www/html/my_path/YetiForce/modules/HelpDesk/models/Record.php(87): Vtiger_Record_Model->saveToDb()
#3 /var/www/html/my_path/YetiForce/modules/Vtiger/models/Record.php(461): HelpDesk_Record_Model->saveToDb()
#4 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/scanneractions/CreatedHelpDesk.php(84): Vtiger_Record_Model->save()
#5 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/scanneractions/CreatedHelpDesk.php(40): OSSMailScanner_CreatedHelpDesk_ScannerAction->add(Object(OSSMail_M$
#6 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/models/Record.php(291): OSSMailScanner_CreatedHelpDesk_ScannerAction->process(Object(OSSMail_Mail_Model))
#7 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/models/Record.php(378): OSSMailScanner_Record_Model::executeActions(Array, Object(OSSMail_Mail_Model), 'IN$
#8 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/models/Record.php(538): OSSMailScanner_Record_Model::mailScan(Resource id #291, Array, 'INBOX', 24581, 0)
#9 /var/www/html/my_path/YetiForce/modules/OSSMailScanner/cron/action.php(14): OSSMailScanner_Record_Model->executeCron('cli - ')
#10 /var/www/html/my_path/YetiForce/cron.php(78): require_once('/var/www/html/Y...')
#11 {main}
```

Czy jest jakiś sposób zmiany/obejścia tego bo ostatecznie doprowadza to do sytuacji że nie moe odpowiedzieć klientowi ze Zgłoszenia.

W kliencie poczty generuje mi się również następujący błąd:
fopen(/var/www/html/my_path/YetiForce/cache/logs/system.log): failed to open stream: Permission denied in /var/www/html/YetiForce/app/Log/FileTarget.php on line 65

**Comment by bpabiszczak** [comment]
a jaka wersja systemu i czy problem występuje na gitdeveloper?

**Comment by mrzewnicki** [comment]
wersja 5.1, na gitdeveloper nie widziałem tak długich wiadomości, czasem sprawy ciągną się przez 1-2 miesiące

**Comment by mariuszkrzaczkowski** [comment]
Ten błąd został naprawiony w aktualnej wersji deweloperskiej https://github.com/YetiForceCompany/YetiForceCRM/commit/79756ee26be3e8407a6baa91d3903ed3b827341e#diff-c68a4e9329987315e0b2a54b0803fa4c
