### ISSUE TITLE
Update 5.0 -> 5.1

### ISSUE THREAD

**Issue by quasi754** [YetiForceCompany/YetiForceCRM#11000]
Hello,

When i trying import a file to update "5.0.0_to_5.1.0" i received a error:

![image](https://user-images.githubusercontent.com/48558884/61351819-0e380f00-a86c-11e9-966b-1ebe492fb32b.png)

Error from logs:
2019-07-17 08:22:04.5209 [error] - Invalid request - Response For Illegal Access
App\Exceptions\AppException: Invalid request - Response For Illegal Access in /var/www/html/YetiForce/config/csrf_config.php:21
Stack trace:
#0 [internal function]: CSRFConfig::{closure}('')
#1 /var/www/html/YetiForce/vendor/yetiforce/csrf-magic/src/Csrf.php(233): call_user_func(Object(Closure), '')
#2 /var/www/html/YetiForce/vendor/yetiforce/csrf-magic/src/Csrf.php(497): CsrfMagic\Csrf::check()
#3 /var/www/html/YetiForce/include/main/WebUI.php(107): CsrfMagic\Csrf::init()
#4 /var/www/html/YetiForce/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#5 {main}

What am i doing wrong?

**Comment by quasi754** [comment]
Does anyone have any idea?

**Comment by quasi754** [comment]
I used wrong update files.
