### ISSUE TITLE
[Question] Error when PDF generated: Call to a member function getType() on bool

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#11509]
### Description

```
2019-09-15 23:34:09.5686 [error] - Call to a member function getType() on bool
Error: Call to a member function getType() on bool in /var/www/html/crm/app/TextParser.php:1551
Stack trace:
#0 /var/www/html/crm/app/TextParser.php(1431): App\TextParser->getInventoryTable(Array)
#1 /var/www/html/crm/app/TextParser.php(378): App\TextParser->inventory('type=table colu...')
#2 [internal function]: App\TextParser->App\{closure}(Array)
#3 /var/www/html/crm/app/TextParser.php(381): preg_replace_callback('/\\$\\((\\w+) : ([...', Object(Closure), '<div style="fon...')
#4 /var/www/html/crm/modules/Vtiger/models/PDF.php(538): App\TextParser->parse()
#5 /var/www/html/crm/modules/Vtiger/actions/PDF.php(115): Vtiger_PDF_Model->parseVariables('<div style="fon...')
#6 /var/www/html/crm/app/Controller/ExposeMethod.php(65): Vtiger_PDF_Action->generate(Object(App\Request))
#7 /var/www/html/crm/app/Controller/ExposeMethod.php(78): Vtiger_PDF_Action->invokeExposedMethod('generate', Object(App\Request))
#8 /var/www/html/crm/include/main/WebUI.php(182): Vtiger_PDF_Action->process(Object(App\Request))
#9 /var/www/html/crm/index.php(24): Vtiger_WebUI->process(Object(App\Request))
#10 /var/www/html/crm/public_html/index.php(11): require('/var/www/html/e...')
#11 {main}
```

What is wrong?

**Comment by vovpff** [comment]
@rafalpospiech pls take a look for this issue.

**Comment by mariuszkrzaczkowski** [comment]
crm version ?

**Comment by vovpff** [comment]
5.2. Error appears after update. Looks like error inside PDF template because my template not work on gitdev also.

**Comment by vovpff** [comment]
[36_pdftemplate.zip](https://github.com/YetiForceCompany/YetiForceCRM/files/3616283/36_pdftemplate.zip)

**Comment by vovpff** [comment]
Many many thanks to @davide-alghi for solution.

int 5.2 was added a class name into table cell and for "seq" inventory field it crashes on creating class name string.

To fix this add these 4 lines before https://github.com/YetiForceCompany/YetiForceCRM/blob/ed4ae613d1f8af2009e7400edc1138a22a4a79ff/app/TextParser.php#L1546

```
if ('seq' === $name) {
    $html .= '<th class="col-type-ItemNumber" style="padding:0px 4px;text-align:right;' . $style . '">' . $tb . '</th>';
    continue;
}
```

EAN field also buggy: table cell for EAN field is without border.

To fix this replace https://github.com/YetiForceCompany/YetiForceCRM/blob/ed4ae613d1f8af2009e7400edc1138a22a4a79ff/app/TextParser.php#L1510 with 

```
$html .= '<td class="col-type-barcode" style="border:1px solid #ddd;padding:0px 4px;' . (\in_array($field->getType(), $fieldsTextAlignRight) ? 'text-align:right;' : '') . '"><div data-barcode="EAN13" data-code="' . $itemValue . '" data-size="1" data-height="16"></div></td>';
```
