### ISSUE TITLE
[bug] DSN cannot be empty in Installation

### ISSUE THREAD

**Issue by Sasamous** [YetiForceCompany/YetiForceCRM#11803]
# 🐞 bug report

### ⁉️ Describe the bug

While waiting for support in [this post](https://github.com/YetiForceCompany/YetiForceCRM/issues/11770) I tried to download last build (5.2) on the same machine, I renamed old "yetiforce" folder (5.1) in "yetiforceOLD" and new folder (5.2) in "yetiforce", I renamed database from yetiforce to yetiforceOLD, but I get 
![image](https://user-images.githubusercontent.com/40520020/67271296-88ef7680-f4ba-11e9-96ad-632c14b13163.png)

### 🔥 How to trigger the error

1. Rename old YetiForce folder in the server
2. Unzip new version with the same folder name of previous installation folder name
3. Navigate from Chrome to the page for installation.
5. service apache2 restart
6. service mariaDB restart
7. Navigate from Chrome to the page for installation and same error
8. Navigate from FTP in ../cache/logs, there is only cron.log and index.html, index is empty.
9. cron.log = 

> PHP Fatal error:  Uncaught yii\base\InvalidConfigException: Connection::dsn cannot be empty. in /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php:602
Stack trace:
#0 /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php(996): yii\db\Connection->open()
#1 /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php(983): yii\db\Connection->getMasterPdo()
#2 /var/www/html/yetiforce/app/Db.php(139): yii\db\Connection->getSlavePdo()
#3 /var/www/html/yetiforce/app/Utils/ConfReport.php(420): App\Db->getInfo()
#4 /var/www/html/yetiforce/app/Utils/ConfReport.php(378): App\Utils\ConfReport::init('all')
#5 /var/www/html/yetiforce/app/Utils/ConfReport.php(364): App\Utils\ConfReport::getByType(Array, true)
#6 /var/www/html/yetiforce/app/Cron.php(103): App\Utils\ConfReport::getAll()
#7 /var/www/html/yetiforce/app/Cron.php(56): App\Cron::generateStatusFile()
#8 /var/www/html/yetiforce/cron.php(25): App\Cron->__construct()
#9 {main}
  thrown in /var/www/html/yetiforce/vendor/yetiforce/yii2/db/Connection.php on line 602

10. Go to phpMyAdmin and Rename old Yetiforce DB
11. Restart services
12. Navigate from Chrome to the page for installation and same error

### 👎 Actual Behavior

HTTP ERROR 500 in installation page.

### 👍 Expected Behavior

Begin installation

### 👷 Testing 

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com 
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍  Your Environment 

| Environment		|	Version / Name	|
| ----------------	|	--------------	|
| YetiForce			|  5.2
| Web server (name and version)|	Apache 2.4	|
| PHP  |	7.2							|
| Browser (name and version)  | 	Any	|
| Operating System (name and version)  | 	Ubuntu 18.04.3 LTS	|
| Database (name and version) | 	10.1.41-MariaDB-0ubuntu0.18.04.1 Ubuntu 18.04	|
| Service Pack version | 		|

**Comment by Sasamous** [comment]
Solved with "_chmod -R a=rwx yetiforce_"
