### ISSUE TITLE
Error when trying to access custom module as admin

### ISSUE THREAD

**Issue by vhugozg** [YetiForceCompany/YetiForceCRM#12171]
Hi everyone.

I've been facing an issue with a custom module I created.
After a while, my admin user can't access the module, returning this error: ERR_NOT_FOUND_FIELD_MODEL|1

The weird thing is that other users, without admin access can still access and fully utilize the module.

![Image of yetiforce error](https://i.ibb.co/j6QXcnT/Capture.png)

The full error report:

```
#0 [info] SELECT * FROM `vtiger_tab` || yii\db\Command::query
#1 [info] Opening DB connection: mysql:host=localhost;dbname=yetiforce;port=3306 || yii\db\Connection::open
#2 [info] SELECT * FROM `vtiger_entityname` || yii\db\Command::query
#3 [info] SELECT * FROM `vtiger_currency_info` || yii\db\Command::query
#4 [info] SHOW FULL COLUMNS FROM `u_yf_browsinghistory` || yii\db\Command::query
#5 [info] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'u_yf_browsinghistory' AND kcu.table_name = 'u_yf_browsinghistory' || yii\db\Command::query
#6 [info] INSERT INTO `u_yf_browsinghistory` (`userid`, `date`, `title`, `url`) VALUES (1, '2019-12-02 17:03:21', 'Au5 List', 'index.php?module=Cadastro&amp;view=List&amp;mid=560&amp;parent=0') || yii\db\Command::execute
#7 [info] SELECT * FROM `vtiger_links` || yii\db\Command::query
#8 [info] SELECT * FROM `u_yf_browsinghistory` WHERE `userid`=1 ORDER BY `id` DESC LIMIT 20 || yii\db\Command::query
#9 [info] SELECT * FROM `vtiger_actionmapping` || yii\db\Command::query
#10 [info] SELECT * FROM `vtiger_customview` WHERE `entitytype`='Cadastro' ORDER BY `sequence` || yii\db\Command::query
#11 [info] SELECT * FROM `vtiger_customview` WHERE `cvid`=138 LIMIT 1 || yii\db\Command::query
#12 [info] SELECT * FROM `vtiger_field` WHERE `tabid`=129 || yii\db\Command::query
#13 [info] SELECT `columnindex`, `field_name`, `module_name`, `source_field_name` FROM `vtiger_cvcolumnlist` WHERE `cvid`=138 ORDER BY `columnindex` || yii\db\Command::query
#14 [info] SELECT `vtiger_field`.`fieldname`, `u_yf_cv_duplicates`.`ignore` FROM `u_yf_cv_duplicates` INNER JOIN `vtiger_field` ON vtiger_field.fieldid = u_yf_cv_duplicates.fieldid WHERE `u_yf_cv_duplicates`.`cvid`=138 || yii\db\Command::query
#15 [info] SELECT `u_yf_cv_condition`.`group_id`, `u_yf_cv_condition`.`field_name`, `u_yf_cv_condition`.`module_name`, `u_yf_cv_condition`.`source_field_name`, `u_yf_cv_condition`.`operator`, `u_yf_cv_condition`.`value`, `u_yf_cv_condition`.`index` AS `condition_index`, `u_yf_cv_condition_group`.`id`, `u_yf_cv_condition_group`.`condition`, `u_yf_cv_condition_group`.`parent_id`, `u_yf_cv_condition_group`.`index` AS `group_index` FROM `u_yf_cv_condition_group` LEFT JOIN `u_yf_cv_condition` ON u_yf_cv_condition.group_id = u_yf_cv_condition_group.id WHERE `u_yf_cv_condition_group`.`cvid`=138 ORDER BY `u_yf_cv_condition_group`.`parent_id` || yii\db\Command::query
#16 [info] SELECT `fieldid` FROM `vtiger_field` WHERE (`fieldname`='related_to') AND (`tabid`=40) LIMIT 1 || yii\db\Command::query
#17 [info] SELECT EXISTS(SELECT `fieldid` FROM `vtiger_fieldmodulerel` WHERE (`fieldid`=601) AND (`relmodule`='Cadastro') LIMIT 1) || yii\db\Command::query
#18 [info] SELECT EXISTS(SELECT * FROM `vtiger_modtracker_tabs` WHERE (`vtiger_modtracker_tabs`.`visible`=1) AND (`vtiger_modtracker_tabs`.`tabid`=129)) || yii\db\Command::query
#19 [info] SELECT EXISTS(SELECT * FROM `a_yf_record_converter` WHERE ((`source_module`=129) AND (`status`=1)) AND (`show_in_list`=1)) || yii\db\Command::query
#20 [info] Opening DB connection: mysql:host=localhost;dbname=yetiforce;port=3306 || yii\db\Connection::open
#21 [info] SELECT `vtiger_field`.* FROM `vtiger_field` LEFT JOIN `vtiger_blocks` ON vtiger_field.block = vtiger_blocks.blockid WHERE `vtiger_field`.`tabid`=129 ORDER BY `vtiger_blocks`.`sequence`, `vtiger_field`.`sequence` || yii\db\Command::query
#22 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=508 LIMIT 1 || yii\db\Command::query
#23 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=509 LIMIT 1 || yii\db\Command::query
#24 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=510 LIMIT 1 || yii\db\Command::query
#25 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=511 LIMIT 1 || yii\db\Command::query
#26 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=512 LIMIT 1 || yii\db\Command::query
#27 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=513 LIMIT 1 || yii\db\Command::query
#28 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=514 LIMIT 1 || yii\db\Command::query
#29 [info] SELECT `columnindex`, `field_name`, `module_name`, `source_field_name` FROM `vtiger_cvcolumnlist` WHERE `cvid`=138 ORDER BY `columnindex` || yii\db\Command::query
#30 [info] SELECT * FROM `vtiger_ws_fieldtype` || yii\db\Command::query
#31 [error] Not found field model | Field name: 1
#32 [error] ERR_NOT_FOUND_FIELD_MODEL|1
App\Exceptions\AppException: ERR_NOT_FOUND_FIELD_MODEL|1 in app/QueryGenerator.php:1141
Stack trace:
#0 app/QueryGenerator.php(470): App\QueryGenerator->getQueryField('1')
#1 modules/Vtiger/models/ListView.php(469): App\QueryGenerator->setOrder('1', NULL)
#2 modules/Vtiger/models/ListView.php(524): Vtiger_ListView_Model->loadListViewOrderBy()
#3 modules/Vtiger/views/List.php(284): Vtiger_ListView_Model->getListViewEntries(Object(Vtiger_Paging_Model))
#4 modules/Vtiger/views/List.php(97): Vtiger_List_View->initializeListViewContents(Object(App\Request), Object(Vtiger_Viewer))
#5 include/main/WebUI.php(261): Vtiger_List_View->preProcess(Object(App\Request))
#6 include/main/WebUI.php(181): Vtiger_WebUI->triggerPreProcess(Object(Vtiger_List_View), Object(App\Request))
#7 index.php(24): Vtiger_WebUI->process(Object(App\Request))
#8 {main}
```
Before this error could occur, I saved my module when it was working. When this came, I just deleted the old one and uploaded the "working version", but it did not resolve the issue. Now I have nothing to do besides creating everything again and not step at the error causing. 
I think this is related to my database, since it wont work with a new module install. 

Anyway, I'm really lost with this. I am using my own server, but the same has occurred in Yetiforce's own servers.

**Comment by mariuszkrzaczkowski** [comment]
the problem is in the settings saved in the session.  log out and log in again
