### ISSUE TITLE
[Bug] multireference fields update cron running error

### ISSUE THREAD

**Issue by JasonChau1227** [YetiForceCompany/YetiForceCRM#12722]
Describe the bug
cron status of multireference fields update changed to running and never end

How to Trigger the error
after setting up cron and run for it first time

Server Config
![yetiforce_settings (2)](https://user-images.githubusercontent.com/62273266/76848445-a7497a80-687e-11ea-894f-3ba9775f0368.png)

Cron.log

---------------  2020-03-17 18:26:15 | Start CRON  ----------
2020-03-17 18:26:15 | LBL_WORKFLOW - Not ready to run as the time to run again is not completed
2020-03-17 18:26:15 | LBL_SCHEDULED_IMPORT - Not ready to run as the time to run again is not completed
2020-03-17 18:26:15 | LBL_MAILER - Not ready to run as the time to run again is not completed
2020-03-17 18:26:15 | LBL_CARD_DAV - Not ready to run as the time to run again is not completed
2020-03-17 18:26:15 | LBL_CAL_DAV - Not ready to run as the time to run again is not completed
2020-03-17 18:26:15 | LBL_ACTIVITY_STATE - Not ready to run as the time to run again is not completed
2020-03-17 18:26:15 | LBL_SEND_REMINDER - Not ready to run as the time to run again is not completed
2020-03-17 18:26:15 | LBL_SEND_NOTIFICATIONS - Not ready to run as the time to run again is not completed
2020-03-17 18:26:15 | LBL_MULTI_REFERENCE_VALUE - Start task
2020-03-17 18:26:15 | ERROR: LBL_MULTI_REFERENCE_VALUE - Cron task execution throwed exception.
Error: Call to a member function getRelationQuery() on boolean in /home/aayeti/public_html/modules/Vtiger/uitypes/MultiReferenceValue.php:207
Stack trace:
#0 /home/aayeti/public_html/cron/MultiReference.php(36): Vtiger_MultiReferenceValue_UIType->reloadValue('SSalesProcesses', 121)
#1 /home/aayeti/public_html/cron.php(79): require_once('/home/aayeti/pu...')
#2 {main}

Environment

YetiForce 5.1.0
Web Server Apache 2.4.29
PHP 7.2
Operating System Ubuntu Linux 18.04.3
Database MySQL  5.7.29

**Comment by mariuszkrzaczkowski** [comment]
![github](https://user-images.githubusercontent.com/10198654/76845539-50708080-683f-11ea-99ba-5e806d0da447.jpg)

**Comment by JasonChau1227** [comment]
I updated the content and please help. Thank you

**Comment by areksolek** [comment]
No bug was found after testing on the current version.
