### ISSUE TITLE
[Question] [PL] Błąd LBL_HANDLER_NOT_FOUND po wejściu do Widżety - konfiguracja

### ISSUE THREAD

**Issue by odiiin** [YetiForceCompany/YetiForceCRM#12943]
### Description

Problem z błędem LBL_HANDLER_NOT_FOUND pojawił sie w pewnym momencie i nie wiem czym mógł zostać spowodowany. Myślałem, że może po aktualizacji do 5.3.0 v4 błąd się naprawi ale pozostał. Dodatkowo po aktualizacji znikneły wszystkie widgety na "Strona główna" i przyciski "Dodaj widżet z filtru" i "Dodaj wykres z filtru" nie działają (nie reagują).

Ogólnie błąd pojawia się po wejściu do Konfiguracja serwera -> Moduły standardowe -> Widżety - konfiguracja:

![obraz](https://user-images.githubusercontent.com/62703577/80096916-b05af500-856a-11ea-9dcb-0a7f2973c68a.png)

Pozdrawiam,
Dziękuję.

**Comment by mariuszkrzaczkowski** [comment]
logs??

**Comment by odiiin** [comment]
W logach yetiforce ani w logach systemowych nic się nie pojawia w momencie wchodzenia do Widżety - konfiguracja, mam uruchomiony tail -F i nic.

W logach yetiforce można znaleźć powtarzający się błąd:

```
[28-Aug-2019 13:49:10 Europe/Sarajevo] PHP Deprecated:  Function create_function() is deprecated in /var/www/html/public_html/modules/OSSMail/roundcube/program/include/rcmail_output_html.php on line 978
[28-Aug-2019 13:49:10 Europe/Sarajevo] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 438
[28-Aug-2019 13:49:10 Europe/Sarajevo] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/html/public_html/modules/OSSMail/roundcube/program/lib/Roundcube/rcube_plugin_api.php on line 438
```

A w logach systemowych problem z Opcache:

```
[Thu Apr 23 14:23:44.886012 2020] [proxy_fcgi:error] [pid 174] [client 192.168.1.180:53603] AH01071: Got error 'PHP message: PHP Warning:  Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) in Unkn$
[Thu Apr 23 14:23:47.722615 2020] [proxy_fcgi:error] [pid 1258] [client 10.77.0.15:60801] AH01071: Got error 'PHP message: PHP Warning:  Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) in Unknow$
[Thu Apr 23 14:23:50.879461 2020] [proxy_fcgi:error] [pid 2128] [client 192.168.1.180:53604] AH01071: Got error 'PHP message: PHP Warning:  Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) in Unk$
[Thu Apr 23 14:23:52.827825 2020] [proxy_fcgi:error] [pid 1667] [client 10.77.0.15:60802] AH01071: Got error 'PHP message: PHP Warning:  Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) in Unknow$
```

Te błędy były już wcześniej, kiedy widżety działały

**Comment by mariuszkrzaczkowski** [comment]
włącz logi w CRM

**Comment by odiiin** [comment]
OK, włączyłem wszystko na true w config/Debug.php
I na stronie z błędem (Widżety - konfiguracja), mam coś takiego:

**Śledzenie wywołania funkcji**
```
include/Loader.php(149)
#0 app/CustomView.php(206): Vtiger_Loader::getComponentClassName('Filter', '', 'Leads')
#1 app/CustomView.php(265): App\CustomView->getCustomViewFromFile('')
#2 app/CustomView.php(288): App\CustomView->getColumnsByCvidFromDb('')
#3 app/QueryGenerator.php(680): App\CustomView->getColumnsListByCvid('')
#4 modules/Vtiger/models/MiniList.php(78): App\QueryGenerator->initForCustomViewById('')
#5 modules/Vtiger/models/MiniList.php(86): Vtiger_MiniList_Model->initListViewController()
#6 modules/Settings/WidgetsManagement/models/Module.php(528): Vtiger_MiniList_Model->getTitle()
#7 modules/Settings/WidgetsManagement/views/Configuration.php(32): Settings_WidgetsManagement_Module_Model->getDashboardForModule('Home')
#8 include/main/WebUI.php(187): Settings_WidgetsManagement_Configuration_View->process(Object(App\Request))
#9 index.php(28): Vtiger_WebUI->process(Object(App\Request))
#10 {main}
```

```
App\Exceptions\AppException: LBL_HANDLER_NOT_FOUND in include/Loader.php:149
Stack trace:
#0 app/CustomView.php(206): Vtiger_Loader::getComponentClassName('Filter', '', 'Leads')
#1 app/CustomView.php(265): App\CustomView->getCustomViewFromFile('')
#2 app/CustomView.php(288): App\CustomView->getColumnsByCvidFromDb('')
#3 app/QueryGenerator.php(680): App\CustomView->getColumnsListByCvid('')
#4 modules/Vtiger/models/MiniList.php(78): App\QueryGenerator->initForCustomViewById('')
#5 modules/Vtiger/models/MiniList.php(86): Vtiger_MiniList_Model->initListViewController()
#6 modules/Settings/WidgetsManagement/models/Module.php(528): Vtiger_MiniList_Model->getTitle()
#7 modules/Settings/WidgetsManagement/views/Configuration.php(32): Settings_WidgetsManagement_Module_Model->getDashboardForModule('Home')
#8 include/main/WebUI.php(187): Settings_WidgetsManagement_Configuration_View->process(Object(App\Request))
#9 index.php(28): Vtiger_WebUI->process(Object(App\Request))
#10 {main}
```

```
#0 [info] Opening DB connection: mysql:host=localhost;dbname=crm;port=3306 || yii\db\Connection::open
#1 [info] SHOW FULL COLUMNS FROM `l_yf_settings_tracker_basic` || yii\db\Command::query
#2 [info] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'l_yf_settings_tracker_basic' AND kcu.table_name = 'l_yf_settings_tracker_basic' || yii\db\Command::query
#3 [info] INSERT INTO `l_yf_settings_tracker_basic` (`user_id`, `type`, `module_name`, `record_id`, `date`, `action`) VALUES (14, 1, 'WidgetsManagement', 0, '2020-04-23 14:35:33', 'View:Configuration') || yii\db\Command::execute
#4 [info] Opening DB connection: mysql:host=localhost;dbname=crm;port=3306 || yii\db\Connection::open
#5 [info] SELECT * FROM `vtiger_tab` || yii\db\Command::query
#6 [info] SELECT * FROM `vtiger_entityname` || yii\db\Command::query
#7 [info] SELECT * FROM `vtiger_currency_info` || yii\db\Command::query
#8 [info] SELECT * FROM `vtiger_links` || yii\db\Command::query
#9 [info] SELECT * FROM `u_yf_browsinghistory` WHERE `userid`=14 ORDER BY `id` DESC LIMIT 20 || yii\db\Command::query
#10 [info] SELECT * FROM `vtiger_actionmapping` || yii\db\Command::query
#11 [info] SELECT * FROM `vtiger_settings_blocks` WHERE (`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL) ORDER BY `sequence` || yii\db\Command::query
#12 [info] SELECT * FROM `vtiger_settings_blocks` WHERE `blockid`=2 LIMIT 1 || yii\db\Command::query
#13 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=1) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#14 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=2) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#15 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=11) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#16 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=12) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#17 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=13) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#18 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=7) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#19 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=14) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#20 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=5) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#21 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=15) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#22 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=8) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#23 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=4) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#24 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=3) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#25 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=6) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#26 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=17) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#27 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=9) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,14,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#28 [info] SELECT * FROM `vtiger_field` WHERE `tabid`=83 || yii\db\Command::query
#29 [info] SELECT `vtiger_field`.* FROM `vtiger_field` LEFT JOIN `vtiger_blocks` ON vtiger_field.block = vtiger_blocks.blockid WHERE `vtiger_field`.`tabid`=83 ORDER BY `vtiger_blocks`.`sequence`, `vtiger_field`.`sequence` || yii\db\Command::query
#30 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=258 LIMIT 1 || yii\db\Command::query
#31 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=259 LIMIT 1 || yii\db\Command::query
#32 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=260 LIMIT 1 || yii\db\Command::query
#33 [info] SELECT * FROM `vtiger_ws_fieldtype` || yii\db\Command::query
#34 [info] SELECT * FROM `vtiger_role` WHERE `roleid`='H38' LIMIT 1 || yii\db\Command::query
#35 [info] SELECT `u_yf_announcement`.`announcementid` AS `id`, `u_yf_announcement`.`subject` AS `subject`, `vtiger_crmentity`.`description` AS `description`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `vtiger_crmentity`.`createdtime` AS `createdtime`, `u_yf_announcement`.`is_mandatory` AS `is_mandatory`, `u_yf_announcement`.`interval` AS `interval` FROM `u_yf_announcement` INNER JOIN `vtiger_crmentity` ON u_yf_announcement.announcementid = vtiger_crmentity.crmid WHERE (`vtiger_crmentity`.`deleted`=0) AND (`announcementstatus`='PLL_PUBLISHED') || yii\db\Command::query
#36 [info] Cannot translate this: 'Dział IT' for module '_Base', lang: pl-PL
#37 [info] Language file does not exist, module: Settings//Vtiger ,language: pl-PL
#38 [info] Language file does not exist, module: Settings/Vtiger ,language: pl-PL
#39 [info] Language file does not exist, module: Settings/Logs ,language: pl-PL
#40 [info] Language file does not exist, module: Settings/Help ,language: pl-PL
#41 [info] Cannot translate this: 'LBL_MENU' for module '_Base', lang: pl-PL
#42 [info] SELECT `name`, `value` FROM `yetiforce_mail_config` WHERE `type`='mailIcon' || yii\db\Command::query
#43 [info] Cannot translate this: 'QUICK_ACCESS_MENU' for module '_Base', lang: pl-PL
#44 [info] Cannot translate this: 'LBL_ACTION_MENU' for module '_Base', lang: pl-PL
#45 [info] SELECT `vtiger_tab`.* FROM `vtiger_field` INNER JOIN `vtiger_tab` ON vtiger_tab.tabid = vtiger_field.tabid WHERE (`vtiger_tab`.`presence` <> 1) AND (`vtiger_tab`.`name` <> 'Users') AND (`vtiger_tab`.`name` NOT IN ('ModComments', 'PriceBooks', 'CallHistory', 'OSSMailView', 'SMSNotifier')) || yii\db\Command::query
#46 [info] Language file does not exist, module: WidgetsManagement ,language: pl-PL
#47 [info] SELECT EXISTS(SELECT * FROM `s_yf_companies` WHERE (NOT (`email` IS NULL)) AND (`email` <> '')) || yii\db\Command::query
#48 [info] SELECT * FROM `vtiger_links` INNER JOIN `vtiger_tab` ON vtiger_links.tabid = vtiger_tab.tabid WHERE (`linktype`='DASHBOARDWIDGET') AND (`vtiger_tab`.`presence`=0) || yii\db\Command::query
#49 [info] SELECT * FROM `u_yf_dashboard_type` || yii\db\Command::query
#50 [info] SELECT `mdw`.`blockid`, `mdw`.`data`, `mdw`.`title`, `mdw`.`filterid`, `mdw`.`id`, `mdw`.`size`, `mdw`.`limit`, `mdw`.`isdefault`, `mdw`.`owners`, `mdw`.`cache`, `mdw`.`date`, `vtiger_links`.*, `mdb`.`authorized` FROM `vtiger_module_dashboard` `mdw` INNER JOIN `vtiger_links` ON mdw.linkid = vtiger_links.linkid INNER JOIN `vtiger_module_dashboard_blocks` `mdb` ON mdw.blockid = mdb.id AND vtiger_links.tabid = mdb.tabid WHERE `vtiger_links`.`tabid`=3 || yii\db\Command::query
#51 [info] SELECT * FROM `vtiger_customview` WHERE `cvid`=4 LIMIT 1 || yii\db\Command::query
#52 [info] SELECT * FROM `vtiger_field` WHERE `tabid`=6 || yii\db\Command::query
#53 [info] SELECT `field_name`, `module_name`, `source_field_name` FROM `vtiger_cvcolumnlist` INNER JOIN `vtiger_tab` ON vtiger_tab.name=vtiger_cvcolumnlist.module_name INNER JOIN `vtiger_field` ON vtiger_tab.tabid = vtiger_field.tabid AND vtiger_field.fieldname = vtiger_cvcolumnlist.field_name WHERE (`cvid`='135') AND (`vtiger_field`.`presence` IN (0, 2)) ORDER BY `columnindex` || yii\db\Command::query
#54 [info] SELECT `vtiger_field`.`fieldname`, `u_yf_cv_duplicates`.`ignore` FROM `u_yf_cv_duplicates` INNER JOIN `vtiger_field` ON vtiger_field.fieldid = u_yf_cv_duplicates.fieldid WHERE `u_yf_cv_duplicates`.`cvid`='135' || yii\db\Command::query
#55 [info] SELECT `u_yf_cv_condition`.`group_id`, `u_yf_cv_condition`.`field_name`, `u_yf_cv_condition`.`module_name`, `u_yf_cv_condition`.`source_field_name`, `u_yf_cv_condition`.`operator`, `u_yf_cv_condition`.`value`, `u_yf_cv_condition`.`index` AS `condition_index`, `u_yf_cv_condition_group`.`id`, `u_yf_cv_condition_group`.`condition`, `u_yf_cv_condition_group`.`parent_id`, `u_yf_cv_condition_group`.`index` AS `group_index` FROM `u_yf_cv_condition_group` LEFT JOIN `u_yf_cv_condition` ON u_yf_cv_condition.group_id = u_yf_cv_condition_group.id WHERE `u_yf_cv_condition_group`.`cvid`='135' ORDER BY `u_yf_cv_condition_group`.`parent_id` || yii\db\Command::query
#56 [info] SELECT * FROM `vtiger_field` WHERE `tabid`=7 || yii\db\Command::query
#57 [error] Error Vtiger_Loader::getComponentClassName(Filter, , Leads): Handler not found
#58 [error] LBL_HANDLER_NOT_FOUND
App\Exceptions\AppException: LBL_HANDLER_NOT_FOUND in include/Loader.php:149
Stack trace:
#0 app/CustomView.php(206): Vtiger_Loader::getComponentClassName('Filter', '', 'Leads')
#1 app/CustomView.php(265): App\CustomView->getCustomViewFromFile('')
#2 app/CustomView.php(288): App\CustomView->getColumnsByCvidFromDb('')
#3 app/QueryGenerator.php(680): App\CustomView->getColumnsListByCvid('')
#4 modules/Vtiger/models/MiniList.php(78): App\QueryGenerator->initForCustomViewById('')
#5 modules/Vtiger/models/MiniList.php(86): Vtiger_MiniList_Model->initListViewController()
#6 modules/Settings/WidgetsManagement/models/Module.php(528): Vtiger_MiniList_Model->getTitle()
#7 modules/Settings/WidgetsManagement/views/Configuration.php(32): Settings_WidgetsManagement_Module_Model->getDashboardForModule('Home')
#8 include/main/WebUI.php(187): Settings_WidgetsManagement_Configuration_View->process(Object(App\Request))
#9 index.php(28): Vtiger_WebUI->process(Object(App\Request))
#10 {main}
#59 [info] Cannot translate this: 'include/Loader.php(149)
#0 app/CustomView.php(206): Vtiger_Loader::getComponentClassName('Filter', '', 'Leads')
#1 app/CustomView.php(265): App\CustomView->getCustomViewFromFile('')
#2 app/CustomView.php(288): App\CustomView->getColumnsByCvidFromDb('')
#3 app/QueryGenerator.php(680): App\CustomView->getColumnsListByCvid('')
#4 modules/Vtiger/models/MiniList.php(78): App\QueryGenerator->initForCustomViewById('')
#5 modules/Vtiger/models/MiniList.php(86): Vtiger_MiniList_Model->initListViewController()
#6 modules/Settings/WidgetsManagement/models/Module.php(528): Vtiger_MiniList_Model->getTitle()
#7 modules/Settings/WidgetsManagement/views/Configuration.php(32): Settings_WidgetsManagement_Module_Model->getDashboardForModule('Home')
#8 include/main/WebUI.php(187): Settings_WidgetsManagement_Configuration_View->process(Object(App\Request))
#9 index.php(28): Vtiger_WebUI->process(Object(App\Request))
#10 {main}' for module '_Base', lang: pl-PL
```

**Comment by odiiin** [comment]
Czy jeszcze jakieś logi lub informacje są potrzebne?
Raczej taka sytuacja nie miała miejsca ale zastanawiałem się, czy może być taki objaw gdy ktoś usunie filtr np. w Leadach lub Kontrahentach, który został użyty do stworzenia widgetu w Widżety - konfiguracja ?

**Comment by odiiin** [comment]
Udało mi się rozwiązać problem.

W bazie danych z tabeli `vtiger_module_dashboard` usunąłem kilka stworzonych przeze mnie widgetów. Możliwe, że to by wystarczyło ale usunąłem jeszcze wpisy z tabeli `vtiger_module_dashboard_widgets` . Jeśli masz taki problem to najpierw spróbuj usunąć wpisy z `vtiger_module_dashboard`, może to wystarczy.

Dzięki temu mogłem wejść do Konfiguracja serwera -> Moduły standardowe -> Widżety - konfiguracja następnie dla pewności usunąłem wszystkie "domyślne" widżety i stworzone przeze mnie pulpity. Możliwe, że można było to usunąć od razu w bazie ale nie wiem jakie są powiązania między tabelami.

Nie wiem co było problemem, podejrzewam że ktoś usunął filtr lub pole w filtrze wykorzystane w widżecie.

Pozdrawiam.
