### ISSUE TITLE
[Question] [PL] Projekty, zmiana typu pola "Czas rozpoczęcia" - [startdate] na datetime (UiType: 79)

### ISSUE THREAD

**Issue by vdpawel** [YetiForceCompany/YetiForceCRM#13176]
Wymarzyłem sobie, żeby data rozpoczęcia projektu zawierała również godzinę.
W bazie uaktualniłem odpowiednie pole:
UPDATE `vtiger_field` SET `uitype` = '79'
Gdy zmieniłem w ten sposób inne pola, wszystko działa poprawnie, lecz z tym konkretnym, gdy chce wejść w konfigurację tego pola pojawia się błąd.
Czy jest sposób, żeby zmienić typ tego pola?

I dreamed that the project start date should also include the time.
In the database, I updated the appropriate field:
UPDATE vtiger_field SET uitype = '79'
When I changed other fields in this way, everything works correctly, but with this particular one, when I want to enter the configuration of this field, an error occurs.
Is there a way to change the type of this field?

![obraz](https://user-images.githubusercontent.com/62466142/84587090-8b715880-ae1c-11ea-9ab8-23f1fb7f9758.png)
```
Exception: DateTime::__construct(): Failed to parse time string ($(date : now)$) at position 0 ($): Unexpected character in include/fields/DateTimeField.php:248
Stack trace:
#0 include/fields/DateTimeField.php(248): DateTime->__construct('$(date : now)$', Object(DateTimeZone))
#1 include/fields/DateTimeField.php(210): DateTimeField::convertTimeZone('$(date : now)$', 'Europe/Sarajevo', 'Europe/Sarajevo')
#2 include/fields/DateTimeField.php(288): DateTimeField::convertToUserTimeZone('$(date : now)$', Object(Users_Privileges_Model))
#3 include/fields/DateTimeField.php(72): DateTimeField->getDisplayDate(NULL)
#4 app/Fields/DateTime.php(33): DateTimeField->getDisplayDateTimeValue()
#5 modules/Vtiger/uitypes/Datetime.php(78): App\Fields\DateTime::formatToDisplay('$(date : now)$')
#6 modules/Vtiger/models/Field.php(1246): Vtiger_Datetime_UIType->getEditViewDisplayValue('$(date : now)$', NULL)
#7 cache/templates_c/basic/cdfcc4d61ba04e72ed47cc6055e3f13713bd67f2_0.file.DateTime.tpl.php(27): Vtiger_Field_Model->getEditViewDisplayValue('$(date : now)$', NULL)
#8 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5eafd7dfa27855_09458887(Object(Smarty_Internal_Template))
#9 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#10 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#11 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#12 cache/templates_c/basic/55ceb67d79aee7d5c3ff6c0d4a0db374da5492fe_0.file.Date.tpl.php(29): Smarty_Internal_Template->_subTemplateRender('modules/Vtiger/...', NULL, NULL, 0, 3600, Array, 0, true)
#13 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5eb682d7e8e937_97080794(Object(Smarty_Internal_Template))
#14 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#15 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#16 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#17 cache/templates_c/basic/53378b86cf8d41d301a17d36a362d26033e1022b_0.file.EditField.tpl.php(129): Smarty_Internal_Template->_subTemplateRender('modules/Vtiger/...', NULL, NULL, 0, 3600, Array, 0, true)
#18 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5eaeb06603c674_27731854(Object(Smarty_Internal_Template))
#19 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#20 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#21 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1)
#22 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)
#23 include/runtime/Viewer.php(207): Smarty_Internal_TemplateBase->display('modules/Setting...')
#24 modules/Settings/LayoutEditor/views/EditField.php(43): Vtiger_Viewer->view('EditField.tpl', 'Settings:Layout...')
#25 include/main/WebUI.php(187): Settings_LayoutEditor_EditField_View->process(Object(App\Request))
#26 index.php(28): Vtiger_WebUI->process(Object(App\Request))
#27 public_html/index.php(11): require('/mnt/www/test...')
#28 {main}#0 [info] Opening DB connection: mysql:host=localhost;dbname=test;port=3306 || yii\db\Connection::open
#1 [info] SELECT * FROM `vtiger_field` WHERE `fieldid`=630 LIMIT 1 || yii\db\Command::query
#2 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=107 LIMIT 1 || yii\db\Command::query
#3 [info] SELECT * FROM `vtiger_tab` || yii\db\Command::query
#4 [info] SELECT * FROM `vtiger_entityname` || yii\db\Command::query
#5 [info] SELECT * FROM `vtiger_field` WHERE `tabid`=43 || yii\db\Command::query
#6 [error] DateTime::__construct(): Failed to parse time string ($(date : now)$) at position 0 ($): Unexpected character
Exception: DateTime::__construct(): Failed to parse time string ($(date : now)$) at position 0 ($): Unexpected character in include/fields/DateTimeField.php:248
Stack trace:
#0 include/fields/DateTimeField.php(248): DateTime->__construct('$(date : now)$', Object(DateTimeZone))
#1 include/fields/DateTimeField.php(210): DateTimeField::convertTimeZone('$(date : now)$', 'Europe/Sarajevo', 'Europe/Sarajevo')
#2 include/fields/DateTimeField.php(288): DateTimeField::convertToUserTimeZone('$(date : now)$', Object(Users_Privileges_Model))
#3 include/fields/DateTimeField.php(72): DateTimeField->getDisplayDate(NULL)
#4 app/Fields/DateTime.php(33): DateTimeField->getDisplayDateTimeValue()
#5 modules/Vtiger/uitypes/Datetime.php(78): App\Fields\DateTime::formatToDisplay('$(date : now)$')
#6 modules/Vtiger/models/Field.php(1246): Vtiger_Datetime_UIType->getEditViewDisplayValue('$(date : now)$', NULL)
#7 cache/templates_c/basic/cdfcc4d61ba04e72ed47cc6055e3f13713bd67f2_0.file.DateTime.tpl.php(27): Vtiger_Field_Model->getEditViewDisplayValue('$(date : now)$', NULL)
#8 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5eafd7dfa27855_09458887(Object(Smarty_Internal_Template))
#9 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#10 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#11 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#12 cache/templates_c/basic/55ceb67d79aee7d5c3ff6c0d4a0db374da5492fe_0.file.Date.tpl.php(29): Smarty_Internal_Template->_subTemplateRender('modules/Vtiger/...', NULL, NULL, 0, 3600, Array, 0, true)
#13 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5eb682d7e8e937_97080794(Object(Smarty_Internal_Template))
#14 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#15 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#16 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#17 cache/templates_c/basic/53378b86cf8d41d301a17d36a362d26033e1022b_0.file.EditField.tpl.php(129): Smarty_Internal_Template->_subTemplateRender('modules/Vtiger/...', NULL, NULL, 0, 3600, Array, 0, true)
#18 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_5eaeb06603c674_27731854(Object(Smarty_Internal_Template))
#19 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#20 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#21 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1)
#22 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1)
#23 include/runtime/Viewer.php(207): Smarty_Internal_TemplateBase->display('modules/Setting...')
#24 modules/Settings/LayoutEditor/views/EditField.php(43): Vtiger_Viewer->view('EditField.tpl', 'Settings:Layout...')
#25 include/main/WebUI.php(187): Settings_LayoutEditor_EditField_View->process(Object(App\Request))
#26 index.php(28): Vtiger_WebUI->process(Object(App\Request))
#27 public_html/index.php(11): require('/mnt/www/test...')
#28 {main}
```

**Comment by mariuszkrzaczkowski** [comment]
jak jest domyślna wartość w tym polu ?
wygląda że problemem jest : '$(date : now)$'

**Comment by vdpawel** [comment]
Domyślną wartością było właśnie: $(date : now)$
Gdy skasowałem w bazie, błąd zniknął.
UPDATE `vtiger_field` SET `defaultvalue` = '' WHERE `vtiger_field`.`fieldid` = 630; 

Wygląda na to, że wybranie wartości domyślnej jako: "Aktualny dzień", dla tego typu pola, generuje ten błąd.

**Comment by vdpawel** [comment]
chyba znalazłem problem :) zaraz przetestuje.. Zostawiłem zły typ pola w bazie.
![obraz](https://user-images.githubusercontent.com/62466142/84627154-aad4b800-aee6-11ea-8d66-abd917a26b51.png)

**Comment by vdpawel** [comment]
Dziękuję za pomoc, mogę w pole wpisać datę i godzinę oraz nie mam błędu przy edycji zmiennej - to rozwiązuje mój problem.

**Informacyjnie, ciągle po włączeniu wartości domyślnej: "Aktualny dzień" dla pola UiType: 79, pojawia się powyższy błąd.**

YetiForce CRM 5.3 Service Pack v4

**Comment by vdpawel** [comment]
Przed chwilą sprawdziłem w wersji developerskiej, również błąd występuje. Niestety teraz nie mogę nagrać filmu...

**Wywołanie błędu:**
1. Dowolny moduł -> Dodaj nowe pole -> Nowe pole daty i czasu
2. Ustawienie wartości domyślnej na: "Aktualny dzień"
3. Edycja pola
