### ISSUE TITLE
[bug] CalDav cron job fails: Call to a member function setValue() on null in /var/www/html/yetiforce/app/Integrations/Dav/Calendar.php:837

### ISSUE THREAD

**Issue by merlinwoff** [YetiForceCompany/YetiForceCRM#14470]
# 🐞 bug report

The CalDav cron job does not sync the calendar and result in an error. In the GUI, it says that the cron job was runned successful last time 4 months ago. The DAV is in use and we store our calendars there. But content of calendars get not synced to web gui.

### ⁉️ Describe the bug
```bash
2021-03-28 14:00:50 | ERROR: LBL_CAL_DAV - Cron task throwed exception.
Error: Call to a member function setValue() on null in /var/www/html/yetiforce/app/Integrations/Dav/Calendar.php:837
Stack trace:
#0 /var/www/html/yetiforce/modules/API/models/CalDAV.php(182): App\Integrations\Dav\Calendar->davSaveAttendee(Array)
#1 /var/www/html/yetiforce/modules/API/models/CalDAV.php(123): API_CalDAV_Model->davUpdate(Array)
#2 /var/www/html/yetiforce/modules/API/models/CalDAV.php(89): API_CalDAV_Model->davSync()
#3 /var/www/html/yetiforce/modules/Calendar/crons/CalDav.php(36): API_CalDAV_Model->calDavCrm2Dav()
#4 /var/www/html/yetiforce/cron.php(98): Calendar_CalDav_Cron->process()
#5 {main}
```

### 🔥 How to trigger the error
1. run php cron.php

### 👎 Actual Behavior
Throws the error from above.

### 👍 Expected Behavior
Successfully sync the dav with yetiforce.

### 👷 Testing
- [ ✔️] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           | 6.1.0
| Web server (name and version)       |        Apache/2.4.37 (centos)         |
| PHP                                 |         PHP 7.2.33       |
| Browser (name and version)          |         -       |
| Operating System (name and version) |      CentOS 8          |
| Database (name and version)         |        10.4.14-MariaDB MariaDB Server         |
| Service Pack version                 |   YetiForce CRM 6.1 Service Pack v7          |

### ❗️ Inform the community if you solve the problem
I was able to solve the error by changing the following file /var/www/html/yetiforce/app/Integrations/Dav/Calendar.php on line 837:
```php
                        foreach ($attendees as &$attendee) {
                                $value = ltrim($attendee->getValue(), 'mailto:');
                                if (isset($invities[$value])) {
                                        $row = $invities[$value];
                                        if(isset($attendee['PARTSTAT'])) {
                                                $attendee['PARTSTAT']->setValue($this->getAttendeeStatus($row['status'], false));
                                        }
                                        unset($invities[$value]);
                                } else {
                                        $this->vcomponent->remove($attendee);
                                }
                        }
```

The following if condition was added:
```php
if(isset($attendee['PARTSTAT'])) {
   $attendee['PARTSTAT']->setValue($this->getAttendeeStatus($row['status'], false));
}
```

instead of just the line:
```php
$attendee['PARTSTAT']->setValue($this->getAttendeeStatus($row['status'], false));
```

Please comment my workaround and also if this does not trigger any other failures.

**Comment by merlinwoff** [comment]
The following next error is now triggered on reexecuting cron.php (I dont know if that is related to my workaround?):
```bash
ERROR: LBL_CAL_DAV - Cron task throwed exception.
App\Exceptions\Security: ERR_ILLEGAL_FIELD_VALUE||subject||Calendar||Austausch Praktikum &amp; Company AG in /var/www/html/yetiforce/modules/Vtiger/uitypes/Base.php:128
Stack trace:
#0 /var/www/html/yetiforce/modules/Vtiger/models/Record.php(598): Vtiger_Base_UIType->validate('Austausch Prakt...')
#1 /var/www/html/yetiforce/modules/Calendar/models/Record.php(128): Vtiger_Record_Model->getValuesForSave()
#2 /var/www/html/yetiforce/modules/Vtiger/models/Record.php(548): Calendar_Record_Model->getValuesForSave()
#3 /var/www/html/yetiforce/modules/Calendar/models/Record.php(115): Vtiger_Record_Model->saveToDb()
#4 /var/www/html/yetiforce/modules/Vtiger/models/Record.php(518): Calendar_Record_Model->saveToDb()
#5 /var/www/html/yetiforce/modules/API/models/CalDAV.php(282): Vtiger_Record_Model->save()
#6 /var/www/html/yetiforce/modules/API/models/CalDAV.php(238): API_CalDAV_Model->recordCreate(Array)
#7 /var/www/html/yetiforce/modules/API/models/CalDAV.php(211): API_CalDAV_Model->recordSync()
#8 /var/www/html/yetiforce/modules/Calendar/crons/CalDav.php(40): API_CalDAV_Model->calDav2Crm()
#9 /var/www/html/yetiforce/cron.php(98): Calendar_CalDav_Cron->process()
#10 {main}
```

The field subject in Calendar has the following default properties and since the text "Austausch Praktikum &amp; Company AG" has less then 100 chars, I think it should work.


| Fieldname| Value |
| ----------------------------------- | -------------- |
| Bezeichnung Name | Betreff (readonly) |
| System Name | subject (readonly) |
| Feldtype | string (UiType: 2) (readonly) |
| Länge | 100 (readonly) |
| Feld Maske | |
| Maximale Textlänge | |
| Spaltenbreite [%] |0 |
| Tab-Taste Reihenfolge | 0 |

I also tested, what happens if I increase the text limit to 250, but no success...

**Comment by merlinwoff** [comment]
I was able to solve this new problem by simply do the following change in the code:

```php
if (!is_numeric($value) && (\is_string($value) && $value !== \App\Purifier::decodeHtml(\App\Purifier::purify($value)))) {
     // throw new \App\Exceptions\Security('ERR_ILLEGAL_FIELD_VALUE||' . $this->getFieldModel()->getFieldName() . '||' . $this->getFieldModel()->getModuleName() . '||' . $value, 406);
}
```

In the file yetiforce/modules/Vtiger/uitypes/Base.php on line 127

It had something to do with the & contained in the meeting subject. Is this change I made safe to use?
