### ISSUE TITLE
dependent field issue

### ISSUE THREAD

**Issue by Akaki-1991** [YetiForceCompany/YetiForceCRM#15035]
# 🐞 bug report

### 🔥 How to trigger the error

1. Go to 'settings'
2. Click on 'standat modules'
3. Scroll down to 'dependent fileds'

### 👷 Testing

- [ ] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |  6.1.0
| Web server (name and version)       |          ngnix      |
| PHP                                 |        7.3.5        |
| Browser (name and version)          |      chrome          |
| Operating System (name and version) |      CentOS          |
| Database (name and version)         |         mariaDB       |
| Service Pack version                |                |

### ❗️ Inform the community if you solve the problem

<html>
<body>

No | Error!!!Call to a member function getFullLabelTranslation() on booleanGo backDashboard#0 [info][yii\db\Connection::open] Opening DB connection: mysql:host=localhost;dbname=yetiforcecrm;port=3306 #1 [info][yii\db\Command::query] SELECT EXISTS(SELECT * FROM `vtiger_users` WHERE (`id`=1) AND ((`status`='Active') AND (`deleted`=0))) #2 [info][yii\db\Connection::open] Opening DB connection: mysql:host=localhost;dbname=yetiforcecrm;port=3306 #3 [info][yii\db\Command::query] SHOW FULL COLUMNS FROM `l_yf_settings_tracker_basic` #4 [info][yii\db\Command::query] SELECT     `kcu`.`CONSTRAINT_NAME` AS `constraint_name`,     `kcu`.`COLUMN_NAME` AS `column_name`,     `kcu`.`REFERENCED_TABLE_NAME` AS `referenced_table_name`,     `kcu`.`REFERENCED_COLUMN_NAME` AS `referenced_column_name` FROM `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `rc` JOIN `information_schema`.`KEY_COLUMN_USAGE` AS `kcu` ON     (         `kcu`.`CONSTRAINT_CATALOG` = `rc`.`CONSTRAINT_CATALOG` OR         (`kcu`.`CONSTRAINT_CATALOG` IS NULL AND `rc`.`CONSTRAINT_CATALOG` IS NULL)     ) AND     `kcu`.`CONSTRAINT_SCHEMA` = `rc`.`CONSTRAINT_SCHEMA` AND     `kcu`.`CONSTRAINT_NAME` = `rc`.`CONSTRAINT_NAME` WHERE `rc`.`CONSTRAINT_SCHEMA` = database() AND `kcu`.`TABLE_SCHEMA` = database() AND `rc`.`TABLE_NAME` = 'l_yf_settings_tracker_basic' AND `kcu`.`TABLE_NAME` = 'l_yf_settings_tracker_basic' #5 [info][yii\db\Command::execute] INSERT INTO `l_yf_settings_tracker_basic` (`user_id`, `type`, `module_name`, `record_id`, `date`, `action`) VALUES (1, 1, 'FieldsDependency', 0, '2021-08-04 16:11:20', 'View:List') #6 [info][yii\db\Command::query] SELECT `name` FROM `a_yf_settings_modules` WHERE `status`=1 #7 [info][yii\db\Command::query] SELECT * FROM `vtiger_tab` #8 [info][yii\db\Command::query] SELECT * FROM `vtiger_entityname` #9 [info][yii\db\Command::query] SELECT * FROM `vtiger_currency_info` WHERE `deleted`=0 #10 [info][yii\db\Command::query] SELECT * FROM `vtiger_links` #11 [info][yii\db\Command::query] SHOW FULL COLUMNS FROM `u_yf_browsinghistory` #12 [info][yii\db\Command::query] SELECT     `kcu`.`CONSTRAINT_NAME` AS `constraint_name`,     `kcu`.`COLUMN_NAME` AS `column_name`,     `kcu`.`REFERENCED_TABLE_NAME` AS `referenced_table_name`,     `kcu`.`REFERENCED_COLUMN_NAME` AS `referenced_column_name` FROM `information_schema`.`REFERENTIAL_CONSTRAINTS` AS `rc` JOIN `information_schema`.`KEY_COLUMN_USAGE` AS `kcu` ON     (         `kcu`.`CONSTRAINT_CATALOG` = `rc`.`CONSTRAINT_CATALOG` OR         (`kcu`.`CONSTRAINT_CATALOG` IS NULL AND `rc`.`CONSTRAINT_CATALOG` IS NULL)     ) AND     `kcu`.`CONSTRAINT_SCHEMA` = `rc`.`CONSTRAINT_SCHEMA` AND     `kcu`.`CONSTRAINT_NAME` = `rc`.`CONSTRAINT_NAME` WHERE `rc`.`CONSTRAINT_SCHEMA` = database() AND `kcu`.`TABLE_SCHEMA` = database() AND `rc`.`TABLE_NAME` = 'u_yf_browsinghistory' AND `kcu`.`TABLE_NAME` = 'u_yf_browsinghistory' #13 [info][yii\db\Command::execute] INSERT INTO `u_yf_browsinghistory` (`userid`, `date`, `title`, `url`) VALUES (1, '2021-08-04 16:11:20', 'Dependent Fields System settings', 'index.php?parent=Settings&amp;module=FieldsDependency&amp;view=List') #14 [info][yii\db\Command::query] SELECT * FROM `u_yf_browsinghistory` WHERE `userid`=1 ORDER BY `id` DESC LIMIT 20 #15 [info][yii\db\Command::query] SELECT * FROM `s_yf_meeting_services` ORDER BY `status` DESC #16 [info][yii\db\Command::query] SELECT * FROM `vtiger_actionmapping` #17 [info][yii\db\Command::query] SELECT * FROM `vtiger_settings_blocks` ORDER BY `sequence` #18 [info][yii\db\Command::query] SELECT * FROM `vtiger_settings_field` WHERE `active`=0 ORDER BY `sequence` #19 [info][yii\db\Command::query] SELECT * FROM `vtiger_field` WHERE `tabid`=83 #20 [info][yii\db\Command::query] SELECT `vtiger_field`.* FROM `vtiger_field` LEFT JOIN `vtiger_blocks` ON vtiger_field.block = vtiger_blocks.blockid WHERE `vtiger_field`.`tabid`=83 ORDER BY `vtiger_blocks`.`sequence`, `vtiger_field`.`sequence` #21 [info][yii\db\Command::query] SELECT * FROM `vtiger_blocks` WHERE `blockid`=258 LIMIT 1 #22 [info][yii\db\Command::query] SELECT * FROM `vtiger_blocks` WHERE `blockid`=259 LIMIT 1 #23 [info][yii\db\Command::query] SELECT * FROM `vtiger_blocks` WHERE `blockid`=260 LIMIT 1 #24 [info][yii\db\Command::query] SELECT * FROM `vtiger_ws_fieldtype` #25 [info][yii\db\Command::query] SELECT `u_yf_announcement`.`announcementid` AS `id`, `u_yf_announcement`.`subject` AS `subject`, `vtiger_crmentity`.`description` AS `description`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `vtiger_crmentity`.`createdtime` AS `createdtime`, `u_yf_announcement`.`is_mandatory` AS `is_mandatory`, `u_yf_announcement`.`interval` AS `interval` FROM `u_yf_announcement` INNER JOIN `vtiger_crmentity` ON u_yf_announcement.announcementid = vtiger_crmentity.crmid WHERE (`vtiger_crmentity`.`deleted`=0) AND (`announcementstatus`='PLL_PUBLISHED') #26 [info][yii\db\Command::query] SELECT * FROM `vtiger_role` WHERE `roleid`='H2' LIMIT 1 #27 [info][yii\db\Command::query] SELECT `name`, `value` FROM `yetiforce_mail_config` WHERE `type`='mailIcon' #28 [info][yii\db\Command::query] SELECT `rcuser_id`, `crmuser_id`, `username`, `password` FROM `roundcube_users_autologin` INNER JOIN `roundcube_users` ON roundcube_users_autologin.rcuser_id = roundcube_users.user_id WHERE `roundcube_users_autologin`.`crmuser_id`=1 ORDER BY `active` DESC #29 [info][yii\db\Command::query] SELECT `vtiger_tab`.* FROM `vtiger_field` INNER JOIN `vtiger_tab` ON vtiger_tab.tabid = vtiger_field.tabid WHERE (`vtiger_tab`.`presence` <> 1) AND (`vtiger_tab`.`name` <> 'Users') AND (`vtiger_tab`.`name` NOT IN ('ModComments', 'PriceBooks', 'CallHistory', 'OSSMailView', 'SMSNotifier')) #30 [info][yii\db\Command::query] SELECT EXISTS(SELECT * FROM `s_yf_companies` WHERE (NOT (`email` IS NULL)) AND (`email` <> '')) #31 [info][yii\db\Command::query] SELECT * FROM `s_yf_fields_dependency` LIMIT 100 #32 [info][yii\db\Command::query] SELECT COUNT(*) FROM `s_yf_fields_dependency` #33 [info][yii\db\Command::query] SELECT * FROM `vtiger_field` WHERE `tabid`=6 #34 [info][yii\db\Command::query] SELECT * FROM `vtiger_blocks` WHERE `blockid`=194 LIMIT 1 #35 [info][yii\db\Command::query] SELECT * FROM `vtiger_field` WHERE `tabid`=136 #36 [info][yii\db\Command::query] SELECT * FROM `vtiger_blocks` WHERE `blockid`=478 LIMIT 1 #37 [info][yii\db\Command::query] SELECT * FROM `vtiger_field` WHERE `tabid`=149 #38 [info][yii\db\Command::query] SELECT * FROM `vtiger_blocks` WHERE `blockid`=544 LIMIT 1 #39 [error] Call to a member function getFullLabelTranslation() on boolean Error: Call to a member function getFullLabelTranslation() on boolean in modules/Settings/FieldsDependency/models/Record.php:172 Stack trace: #0 [internal function]: Settings_FieldsDependency_Record_Model->{closure}('cf_1422') #1 modules/Settings/FieldsDependency/models/Record.php(173): array_map(Object(Closure), Array) #2 cache/templates_c/basic/e60f1334464d3891948c3905b250827835af7128_0.file.ListViewContents.tpl.php(62): Settings_FieldsDependency_Record_Model->getDisplayValue('fields') #3 vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_60cb2d5d869a03_85744463(Object(Smarty_Internal_Template)) #4 vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template)) #5 vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template)) #6 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render(false, 1) #7 vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 1) #8 include/runtime/Viewer.php(207): Smarty_Internal_TemplateBase->display('modules/Setting...') #9 modules/Settings/Vtiger/views/List.php(46): Vtiger_Viewer->view('ListViewContent...', 'Settings:Fields...') #10 include/main/WebUI.php(189): Settings_Vtiger_List_View->process(Object(App\Request)) #11 index.php(28): Vtiger_WebUI->process(Object(App\Request)) #12 {main}
-- | --

</body>
</html>

**Comment by Akaki-1991** [comment]
![Capture](https://user-images.githubusercontent.com/75428743/128179386-25d47fa4-df83-4cd9-90a0-e1f97024e49f.PNG)

cannot delete record
