### ISSUE TITLE
[bug] CalDAV cron error

### ISSUE THREAD

**Issue by vencatoitc** [YetiForceCompany/YetiForceCRM#15067]
# 🐞 bug report

### 🔥 How to trigger the error

Waiting for the cron.sh to be executed or manually execute it.

### 👎 Actual Behavior

The cronjob is displayed as running... In the log we found the "Start task" string and not the ending one.

### 👍 Expected Behavior

To be executed just fine.

### 👷 Testing

- [x] I confirm that I tested it at https://gitstable.yetiforce.com
- [ ] I confirm that I tested it at https://gitdeveloper.yetiforce.com

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

- logs -- debugged cronjobs log

```
2021-08-12 16:20:02 [info] - File start
2021-08-12 16:20:02 [info] - SAPI: cli, User: 1
2021-08-12 16:20:02 [info] - Cron start
2021-08-12 16:20:02 [info] - Task start: LBL_WORKFLOW
2021-08-12 16:20:02 [info] -    End task, time: 0.02
2021-08-12 16:20:02 [info] - Task start: LBL_SCHEDULED_IMPORT
2021-08-12 16:20:02 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:02 [info] - Task start: LBL_MAIL_SCANNER_ACTION
2021-08-12 16:20:03 [info] -    End task, time: 0.85
2021-08-12 16:20:03 [info] - Task start: LBL_MAIL_SCANNER_VERIFICATION
2021-08-12 16:20:03 [info] -    End task, time: 0.05
2021-08-12 16:20:03 [info] - Task start: LBL_MAIL_SCANNER_BIND
2021-08-12 16:20:03 [info] -    End task, time: 0.01
2021-08-12 16:20:03 [info] - Task start: LBL_MAILER
2021-08-12 16:20:05 [info] -    End task, time: 2.07
2021-08-12 16:20:05 [info] - Task start: LBL_CAL_DAV
2021-08-12 16:20:05 [error] -    Cron task execution throwed exception: 
---------------  2021-08-12 16:20:02 | Start CRON  ----------
2021-08-12 16:20:02 | LBL_WORKFLOW - Start task
2021-08-12 16:20:02 | LBL_WORKFLOW - End task (0.02 s)
2021-08-12 16:20:02 | LBL_SCHEDULED_IMPORT - Not ready to run as the time to run again is not completed
2021-08-12 16:20:02 | LBL_MAIL_SCANNER_ACTION - Start task
2021-08-12 16:20:03 | LBL_MAIL_SCANNER_ACTION - End task (0.85 s)
2021-08-12 16:20:03 | LBL_MAIL_SCANNER_VERIFICATION - Start task
2021-08-12 16:20:03 | LBL_MAIL_SCANNER_VERIFICATION - End task (0.05 s)
2021-08-12 16:20:03 | LBL_MAIL_SCANNER_BIND - Start task
2021-08-12 16:20:03 | LBL_MAIL_SCANNER_BIND - End task (0.01 s)
2021-08-12 16:20:03 | LBL_MAILER - Start task
2021-08-12 16:20:05 | LBL_MAILER - End task (2.07 s)
2021-08-12 16:20:05 | LBL_CAL_DAV - Start task

TypeError: Return value of Vtiger_Record_Model::getModule() must be an instance of Vtiger_Module_Model, null returned in /var/www/yetiforce/modules/Vtiger/models/Record.php:242
Stack trace:
#0 /var/www/yetiforce/modules/Users/models/Privileges.php(29): Vtiger_Record_Model->getModule()
#1 /var/www/yetiforce/app/Integrations/Dav/Calendar.php(849): Users_Privileges_Model->getName()
#2 /var/www/yetiforce/modules/API/models/CalDAV.php(141): App\Integrations\Dav\Calendar->davSaveAttendee(Array)
#3 /var/www/yetiforce/modules/API/models/CalDAV.php(113): API_CalDAV_Model->davCreate()
#4 /var/www/yetiforce/modules/API/models/CalDAV.php(82): API_CalDAV_Model->davSync()
#5 /var/www/yetiforce/modules/Calendar/crons/CalDav.php(36): API_CalDAV_Model->calDavCrm2Dav()
#6 /var/www/yetiforce/cron.php(99): Calendar_CalDav_Cron->process()
#7 {main}
2021-08-12 16:20:05 [info] - Task start: LBL_CARD_DAV
2021-08-12 16:20:05 [info] -    End task, time: 0.02
2021-08-12 16:20:05 [info] - Task start: LBL_ACTIVITY_STATE
2021-08-12 16:20:05 [info] -    End task, time: 0.03
2021-08-12 16:20:05 [info] - Task start: LBL_SEND_NOTIFICATIONS
2021-08-12 16:20:05 [info] -    End task, time: 0.29
2021-08-12 16:20:05 [info] - Task start: LBL_SEND_REMINDER
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_MULTI_REFERENCE_VALUE
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_CRMACTIVITY_DAYS
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_ASSETS_RENEWAL
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_SOLD_SERVICES_RENEWAL
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_RECORD_LABEL_UPDATER
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_PRIVILEGES_UPDATER
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_MARK_RECORDS_AS_REVIEWED
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_CACHE
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_NEVER_ENDING_RECURRING_EVENTS
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_CLEAR_FILE_UPLOAD_TEMP
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_SMSNOTIFIER
2021-08-12 16:20:05 [info] -    End task, time: 0.01
2021-08-12 16:20:05 [info] - Task start: LBL_BROWSING_HISTORY
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBK_SYSTEM_WARNINGS
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_BATCH_PROCESSES
2021-08-12 16:20:05 [info] -    End task, time: 0.02
2021-08-12 16:20:05 [info] - Task start: LBL_BATCH_METHODS
2021-08-12 16:20:05 [info] -    End task, time: 0.01
2021-08-12 16:20:05 [info] - Task start: LBL_SESSION_CLEANER
2021-08-12 16:20:05 [info] -    End task, time: 0.01
2021-08-12 16:20:05 [info] - Task start: LBL_CURRENCY_UPDATE
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - Task start: LBL_MAIL_RBL
2021-08-12 16:20:05 [info] -    Not ready to run as the time to run again is not completed
2021-08-12 16:20:05 [info] - End CRON (3.63)
2021-08-12 16:20:06 [info] - ------------------------------------
```

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |  6.2 Service Pack v2 |
| Web server (name and version)       | Apache 2.4.29 |
| PHP                                 | 7.4.22 |
| Database (name and version)         | MySQL 5.7.35 |

### ❓ Additional context

The issue has risen the moment after adding the first CalDAV users.

**Comment by vencatoitc** [comment]
```
diff --git a/modules/OSSMail/models/AddressBook.php b/modules/OSSMail/models/AddressBook.php
index 205423ca..a8de044f 100644
--- a/modules/OSSMail/models/AddressBook.php
+++ b/modules/OSSMail/models/AddressBook.php
@@ -36,7 +36,7 @@ class OSSMail_AddressBook_Model
                $db = \App\Db::getInstance();
                $usersIds = \App\Fields\Owner::getUsersIds();
                foreach($usersIds as $userId){
-                       $mails = (new \App\Db\Query())->select([new \yii\db\Expression('CONCAT(name,' . $db->quoteValue(' <') . ',email,'. $db->quoteValue('>') .')')])
+                       $mails = (new \App\Db\Query())->select([new \yii\db\Expression('CONCAT(name,' . $db->quoteValue(' <') . ',email,'. $db->quoteValue('>') .')'), 'vtiger_crmentity.setype'])
                        ->from(self::TABLE)->innerJoin('vtiger_crmentity', self::TABLE . '.id = vtiger_crmentity.crmid')
                        ->where(['or', ['like', self::TABLE . '.users', ",{$userId},"],['like', self::TABLE . '.users', "%,{$userId}", false]])
                        ->orderBy(new \yii\db\Expression("CASE WHEN setype = 'OSSEmployees' THEN 1 WHEN setype = 'Contacts' THEN 2 ELSE 3 END"))->distinct()->column();
```

**Comment by vencatoitc** [comment]
Is this method missing?

```
class Users_Record_Model extends Vtiger_Record_Model
{
        public function getModule()
        {       
                if (!$this->module) {
                        $this->module = Vtiger_Module_Model::getInstance('Users');
                }
                return $this->module;
        }
        [...]
}
```

This temporary solved the issue untill 6.3 will be out.

**Comment by mariuszkrzaczkowski** [comment]
yes

**Comment by jmginfor** [comment]
I have the same problem. 
Just want to be sure. Where do you add this method ? In /var/www/yetiforce/modules/Vtiger/models/Record.php ? If so where exactly ? I don't want to break the system...
thanks
