### ISSUE TITLE
[bug] LBL_ADDRESS_BOOK cronjob error, wrong query

### ISSUE THREAD

**Issue by vencatoitc** [YetiForceCompany/YetiForceCRM#15072]
# 🐞 bug report

### ⁉️ Describe the bug

```
2021-08-13 08:14:09 [info] - Task start: LBL_ADDRESS_BOOK
2021-08-13 08:14:42 [error] -    Cron task execution throwed exception: 
---------------  2021-08-13 08:14:09 | Start CRON  ----------
2021-08-13 08:14:09 | LBL_ADDRESS_BOOK - Start task

PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(name,' <',email,'>') FROM `u_yf_mail_address_book` INNER JOIN `vtiger_crmentity' at line 1 in /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php:264
Stack trace:
#0 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(264): PDO->prepare('SELECT DISTINCT...')
#1 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(1160): yii\db\Command->prepare(true)
#2 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(450): yii\db\Command->queryInternal('fetchAll', 7)
#3 /var/www/yetiforce/vendor/yetiforce/yii2/db/Query.php(318): yii\db\Command->queryColumn()
#4 /var/www/yetiforce/modules/OSSMail/models/AddressBook.php(42): yii\db\Query->column()
#5 /var/www/yetiforce/modules/Vtiger/crons/AddressBook.php(104): OSSMail_AddressBook_Model::createABFile()
#6 /var/www/yetiforce/cron2.php(103): Vtiger_AddressBook_Cron->process()
#7 {main}

Next yii\db\Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(name,' <',email,'>') FROM `u_yf_mail_address_book` INNER JOIN `vtiger_crmentity' at line 1
Failed to prepare SQL: SELECT DISTINCT vtiger_crmentity.setype CONCAT(name,' <',email,'>') FROM `u_yf_mail_address_book` INNER JOIN `vtiger_crmentity` ON u_yf_mail_address_book.id = vtiger_crmentity.crmid WHERE (`u_yf_mail_address_book`.`users` LIKE :qp0) OR (`u_yf_mail_address_book`.`users` LIKE :qp1) ORDER BY CASE WHEN setype = 'OSSEmployees' THEN 1 WHEN setype = 'Contacts' THEN 2 ELSE 3 END in /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php:269
Stack trace:
#0 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(1160): yii\db\Command->prepare(true)
#1 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(450): yii\db\Command->queryInternal('fetchAll', 7)
#2 /var/www/yetiforce/vendor/yetiforce/yii2/db/Query.php(318): yii\db\Command->queryColumn()
#3 /var/www/yetiforce/modules/OSSMail/models/AddressBook.php(42): yii\db\Query->column()
#4 /var/www/yetiforce/modules/Vtiger/crons/AddressBook.php(104): OSSMail_AddressBook_Model::createABFile()
#5 /var/www/yetiforce/cron2.php(103): Vtiger_AddressBook_Cron->process()
#6 {main}
Additional Information:
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(name,' <',email,'>') FROM `u_yf_mail_address_book` INNER JOIN `vtiger_crmentity' at line 1
)

2021-08-13 08:14:42 [info] - End CRON (33.01)
2021-08-13 08:14:42 [info] - ------------------------------------
```

### ❗️ Inform the community if you solve the problem

```
# git diff modules/OSSMail/models/AddressBook.php 
diff --git a/modules/OSSMail/models/AddressBook.php b/modules/OSSMail/models/AddressBook.php
index 205423ca..a8de044f 100644
--- a/modules/OSSMail/models/AddressBook.php
+++ b/modules/OSSMail/models/AddressBook.php
@@ -36,7 +36,7 @@ class OSSMail_AddressBook_Model
                $db = \App\Db::getInstance();
                $usersIds = \App\Fields\Owner::getUsersIds();
                foreach($usersIds as $userId){
-                       $mails = (new \App\Db\Query())->select([new \yii\db\Expression('CONCAT(name,' . $db->quoteValue(' <') . ',email,'. $db->quoteValue('>') .')')])
+                       $mails = (new \App\Db\Query())->select([new \yii\db\Expression('CONCAT(name,' . $db->quoteValue(' <') . ',email,'. $db->quoteValue('>') .')'), 'vtiger_crmentity.setype'])
                        ->from(self::TABLE)->innerJoin('vtiger_crmentity', self::TABLE . '.id = vtiger_crmentity.crmid')
                        ->where(['or', ['like', self::TABLE . '.users', ",{$userId},"],['like', self::TABLE . '.users', "%,{$userId}", false]])
                        ->orderBy(new \yii\db\Expression("CASE WHEN setype = 'OSSEmployees' THEN 1 WHEN setype = 'Contacts' THEN 2 ELSE 3 END"))->distinct()->column();
```

Sorry, I don't have time to make a proper patch and I don't know if it fits as a proper solution :-P

**Comment by mariuszkrzaczkowski** [comment]
thanks, it works
