### ISSUE TITLE
[BUG] Unable to update to 6.3.0 security fix v4

### ISSUE THREAD

**Issue by zazy** [YetiForceCompany/YetiForceCRM#15627]
When updating from 6.3.0 v2 to 6.3.0 v4 I receive an error. Here is the returned error screen:

```
------------- 2022-01-11 23:05:20 -------------
> start update tables (base)
> alter column: u_#__occurrences:participants ... done (0s)
> alter column: vtiger_account:employees ... done (0.1s)
> alter column: vtiger_callhistory:duration ... done (0s)
> alter column: vtiger_campaign:targetsize ... done (0s)
> alter column: vtiger_campaign:expectedresponsecount ... done (0s)
> alter column: vtiger_campaign:expectedsalescount ... done (0s)
> alter column: vtiger_campaign:actualresponsecount ... done (0s)
> alter column: vtiger_campaign:actualsalescount ... done (0s)
> alter column: vtiger_leaddetails:noofemployees ... done (0s)
> alter column: vtiger_outsourcedproducts:prodcount ... done (0s)
> alter column: vtiger_project:targetbudget ... | Error(7) [SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'targetbudget' at row 1
The SQL being executed was: ALTER TABLE `vtiger_project` CHANGE `targetbudget` `targetbudget` int(10) UNSIGNED] in
#0 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /var/www/yetiforce/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /var/www/yetiforce/app/Db/Importer.php(698): yii\db\Command->execute()
#3 /var/www/yetiforce/app/Db/Importer.php(154): App\Db\Importer->updateTables()
#4 /var/www/yetiforce/cache/updates/updates/init.php(105): App\Db\Importer->updateScheme()
#5 /var/www/yetiforce/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update()
#6 /var/www/yetiforce/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate()
#7 /var/www/yetiforce/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import()
#8 /var/www/yetiforce/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3()
#9 /var/www/yetiforce/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod()
#10 /var/www/yetiforce/include/main/WebUI.php(190): Settings_ModuleManager_ModuleImport_View->process()
#11 /var/www/yetiforce/index.php(26): Vtiger_WebUI->process()
#12 /var/www/yetiforce/public_html/index.php(13): require('/var/www/yetifo...')
#13 {main} !!!
> alter column: vtiger_users:records_limit ... done (0.1s)
> alter column: u_#__cfixedassets:timing_change ... done (0s)
> alter column: u_#__cfixedassets:oil_change ... done (0s)
> alter column: u_#__cfixedassets:fuel_consumption ... done (0s)
> alter column: u_#__cfixedassets:current_odometer_reading ... done (0s)
> alter column: u_#__cfixedassets:number_repair ... done (0s)
> alter column: u_#__incidentregister:peoplne_number ... done (0s)
> alter column: u_#__locations:capacity ... done (0s)
# end update tables (0.07s)
> start drop tables
# end drop tables (0 min)
> start drop columns
# end drop columns (0 min)
> start drop indexes
# end drop indexes (0 min)
> start add data rows (base)
# end add data rows (0 min)
> start reset sequence
# end reset sequence (0 min)
> start update foreign key (base)
# end update foreign key (0s)
```

As far I can undestand it's related to MySQL 8 that doesn't accept an empty string as default for an integer columnt. It should be set to NULL

**Comment by mariuszkrzaczkowski** [comment]
Duplicate of #15575
you need to correct the values before uploading the package, if you find the wrong value, write what we will try to protect
