### ISSUE TITLE
[bug] Call to a member function getRelationModel() on bool

### ISSUE THREAD

**Issue by Mekada7387** [YetiForceCompany/YetiForceCRM#15655]
# 🐞 bug report

### ⁉️ Describe the bug

![immagine](https://user-images.githubusercontent.com/98270968/150684571-6d4a7166-dd6d-4115-a2e6-d9b3c8a0dd1a.png)

![immagine](https://user-images.githubusercontent.com/98270968/150684581-1263a474-e897-43ce-9947-b78def542af3.png)

### 🔥 How to trigger the error

The error appeared after updating from version 6.2 (fully functional) to version 6.3. All Leads and Accounts have the same error.
To rule out problems caused by the update procedure, I'm testing the error with a clean installation of version 6.3 on the same server where the 6.2 works (same PHP and MySQL settings) and the same error is present. Creating a Leads and/or an Accounts the same error occurs. 
If I try to disable the "Contacts" module in the general settings, the Leads page opens correctly (obviously without the Contacts section visible) and if I try to disable the "Opportunities" module in the general settings, the Accounts page opens correctly (obviously without the Opportunities section visible).

### 👎 Actual Behavior

Error in screenshots.

### 👍 Expected Behavior

Version 6.2 works fine and so 6.3 should too.

### 👷 Testing

- [X] I confirm that I tested it at https://gitstable.yetiforce.com
- [X] I confirm that I tested it at https://gitdeveloper.yetiforce.com

I tested a clean install of the "YetiForceCRM-6.3.0-complete.zip" Github package on the same server where version 6.2 works correctly (same PHP and MySQL settings). Installing the "SecurityFix_v5" update does not change anything.

### 📷 Screenshot of configuration

![immagine](https://user-images.githubusercontent.com/98270968/150685244-443f35f4-9f2e-46a1-8ce4-122008f3c09e.png)

### 📝 PHP/Apache/Nginx/Browser/CRM Logs

--- YetiForce system.log ---

2022-01-23 14:10:36.0005 [error] - Call to a member function getRelationModel() on bool
Error: Call to a member function getRelationModel() on bool in /home/---/---/crm/cache/templates_c/basic/06bd7623fca71e4e73f660feda9d7abd75c41391_0.file.Basic.tpl.php:59
Stack trace:
#0 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_61ed2e6b7c02a6_75890558(Object(Smarty_Internal_Template))
#1 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#4 /home/---/---/crm/cache/templates_c/basic/a9c0ef86cb1db68f82f362b2ed4d834cc48ca1f5_0.file.DetailViewSummaryView.tpl.php(44): Smarty_Internal_Template->_subTemplateRender('modules/Vtiger/...', NULL, NULL, 0, 3600, Array, 0, true)
#5 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_61ed2e6b746a91_87092586(Object(Smarty_Internal_Template))
#6 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#7 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#8 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0)
#9 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)
#10 /home/---/---/crm/include/runtime/Viewer.php(205): Smarty_Internal_TemplateBase->fetch('modules/Vtiger/...')
#11 /home/---/---/crm/modules/Vtiger/views/Detail.php(360): Vtiger_Viewer->view('DetailViewSumma...', 'Leads', true)
#12 /home/---/---/crm/modules/Vtiger/views/Detail.php(262): Vtiger_Detail_View->showModuleBasicView(Object(App\Request))
#13 /home/---/---/crm/modules/Vtiger/views/Detail.php(194): Vtiger_Detail_View->showDetailViewByMode(Object(App\Request))
#14 /home/---/---/crm/include/main/WebUI.php(188): Vtiger_Detail_View->process(Object(App\Request))
#15 /home/---/---/crm/index.php(26): Vtiger_WebUI->process(Object(App\Request))
#16 {main}

2022-01-23 14:10:45.1592 [error] - Call to a member function getRelationModel() on bool
Error: Call to a member function getRelationModel() on bool in /home/---/---/crm/cache/templates_c/basic/06bd7623fca71e4e73f660feda9d7abd75c41391_0.file.Basic.tpl.php:59
Stack trace:
#0 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_61ed2e6b7c02a6_75890558(Object(Smarty_Internal_Template))
#1 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#4 /home/---/---/crm/cache/templates_c/basic/a9c0ef86cb1db68f82f362b2ed4d834cc48ca1f5_0.file.DetailViewSummaryView.tpl.php(44): Smarty_Internal_Template->_subTemplateRender('modules/Vtiger/...', NULL, NULL, 0, 3600, Array, 0, true)
#5 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_61ed2e6b746a91_87092586(Object(Smarty_Internal_Template))
#6 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#7 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#8 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render(false, 0)
#9 /home/---/---/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(116): Smarty_Internal_TemplateBase->_execute(Object(Smarty_Internal_Template), NULL, NULL, NULL, 0)
#10 /home/---/---/crm/include/runtime/Viewer.php(205): Smarty_Internal_TemplateBase->fetch('modules/Vtiger/...')
#11 /home/---/---/crm/modules/Vtiger/views/Detail.php(360): Vtiger_Viewer->view('DetailViewSumma...', 'Accounts', true)
#12 /home/---/---/crm/modules/Vtiger/views/Detail.php(262): Vtiger_Detail_View->showModuleBasicView(Object(App\Request))
#13 /home/---/---/crm/modules/Vtiger/views/Detail.php(194): Vtiger_Detail_View->showDetailViewByMode(Object(App\Request))
#14 /home/---/---/crm/include/main/WebUI.php(188): Vtiger_Detail_View->process(Object(App\Request))
#15 /home/---/---/crm/index.php(26): Vtiger_WebUI->process(Object(App\Request))
#16 {main}

--- web server error log ---

no errors detected 

### 🌍 Your Environment

YetiForce: 6.3.0
Service Pack version: SecurityFix_v5
PHP: 7.4.27
MySQL: 5.7.36

**Comment by rskrzypczak** [comment]
I don't know where these errors come from, most likely something is messed up in your database.
You mentioned that you checked it on a clean 6.3 instance but are you sure you conducted a full installation process, and you didn't just replace the files for example? 
The demo environments don't indicate this problem either.
Was the update process completed successfully?

I assume you played with the relations and something isn't set right in the database as far as this is concerned.
You can try adding these problematic widgets once again, but it doesn't really solve the problem.
Check if relations are set correctly.

**Comment by Mekada7887** [comment]
To rule out problems due to the update, I proceeded with a new clean installation (from the github zip package) in another subdomain and empty database (same server and same PHP and MySQL settings where 6.2 works) and the installation process is successful. The problem arises immediately without carrying out any customization of the modules and relations.

**Comment by Bailundo** [comment]
I have exactly the same problem.
For screening, I did a new installation of the latest version of Softaculous, with an empty database and the error remains.
"Modules - Relations" is cleared.
