### ISSUE TITLE
[bug] predefined widgets/charts can't be deleted from home page

### ISSUE THREAD

**Issue by apcloic** [YetiForceCompany/YetiForceCRM#16633]
Hi,

Tested on gitdeveloper with Chrome (latest stable) & Firefox (latest)

Test case :
1- go to homepage, create a new widget from filter or chart from filter
2- close it
3- go to predefined widgets and try to delete it
4- nothing happens

![cannot_delete_predefined_home_widget](https://user-images.githubusercontent.com/2930560/200300016-1dfe93ce-a0d7-46b9-b931-30cc04c553ee.gif)

````

Csrf.min.js:1          POST https://gitdeveloper.yetiforce.com/index.php 406
send @ Csrf.min.js:1
send @ jquery.js?s=1662105616:10135
ajax @ jquery.js?s=1662105616:9716
_request @ Connector.js?s=1667818893:143
request @ Connector.js?s=1667818893:35
(anonymous) @ DashBoard.js?s=1667818893:545
dispatch @ jquery.js?s=1662105616:5430
elemData.handle @ jquery.js?s=1662105616:5234
Connector.js?s=1667818893:121 YetiForce debug mode!!!
params.error @ Connector.js?s=1667818893:121
fire @ jquery.js?s=1662105616:3500
fireWith @ jquery.js?s=1662105616:3630
done @ jquery.js?s=1662105616:9824
(anonymous) @ jquery.js?s=1662105616:10083
load (async)
send @ jquery.js?s=1662105616:10102
ajax @ jquery.js?s=1662105616:9716
_request @ Connector.js?s=1667818893:143
request @ Connector.js?s=1667818893:35
(anonymous) @ DashBoard.js?s=1667818893:545
dispatch @ jquery.js?s=1662105616:5430
elemData.handle @ jquery.js?s=1662105616:5234
Connector.js?s=1667818893:125 Error:  
------------------------------------------------------------------------------------------------------------------------------------------------------
Trace:
------------------------------------------------------------------------------------------------------------------------------------------------------
#0 include/main/WebUI.php(185): Vtiger_Widget_Action->checkPermission()
#1 index.php(26): Vtiger_WebUI->process()
#2 public_html/index.php(13): require('...')
#3 {main} 
------------------------------------------------------------------------------------------------------------------------------------------------------
Params:
------------------------------------------------------------------------------------------------------------------------------------------------------
{
	"data": {
		"module": "Home",
		"action": "Widget",
		"mode": "removeWidgetFromList",
		"widgetid": 14
	},
	"type": "POST",
	"jsonp": false,
	"dataType": "json",
	"url": "index.php"
}

````

**Comment by apcloic** [comment]
````
2022-11-10 10:52:01.7383 [error][] - LBL_PERMISSION_DENIED
App\Exceptions\NoPermitted: LBL_PERMISSION_DENIED in /***************/modules/Vtiger/actions/Widget.php:56
Stack trace:
#0 /***************/include/main/WebUI.php(185): Vtiger_Widget_Action->checkPermission(Object(App\Request))
#1 /***************/index.php(26): Vtiger_WebUI->process(Object(App\Request))

````

So I change checkPermission function in /modules/Vtiger/actions/Widget.php and now it works

````
	public function checkPermission(App\Request $request)
	{
		$moduleName = $request->getModule();
		$mode = $request->getMode();

		if ($request->has('widgetid')) {
			$widget = Vtiger_Widget_Model::getInstanceWithWidgetId($request->getInteger('widgetid'), \App\User::getCurrentUserId());
		} else {
			if ('add' !== $mode) {
				$widget = Vtiger_Widget_Model::getInstance($request->getInteger('linkid'), \App\User::getCurrentUserId());
			}
		}
		if (('updateWidgetConfig' === $mode && $request->has('widgetid') && $widget->get('active'))
			|| ('remove' === $mode && !$widget->isDefault() && \App\Privilege::isPermitted($moduleName))
			|| (('positions' === $mode || 'clear' === $mode || 'removeWidgetFromList' === $mode) && \App\Privilege::isPermitted($moduleName))
			|| 'add' === $mode) {
			return true;
		}
		throw new \App\Exceptions\NoPermitted('LBL_PERMISSION_DENIED');
	}

````

**Comment by mariuszkrzaczkowski** [comment]
if you have a fix create a pull request
