### ISSUE TITLE
How to fix "Argument #2 ($haystack) must be of type array, string given TypeError: in_array(): "

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [YetiForceCompany/YetiForceCRM#16835]
### Discussed in https://github.com/YetiForceCompany/YetiForceCRM/discussions/16834

<div type='discussions-op-text'>

<sup>Originally posted by **Jianbin719** January 29, 2023</sup>
I am using webhook for sending notification after the new record comes, but after few days webhook not works, and errors come to me. How can I fix it. please kindly help. 

2023-01-29 09:23:23.0207 [error][] - in_array(): Argument #2 ($haystack) must be of type array, string given
TypeError: in_array(): Argument #2 ($haystack) must be of type array, string given in /www/wwwroot/Yetiforce/cache/templates_c/basic/bfb3dbc0280ecdaf0a108ddbf9c403a11fdf6842_0.file.Webhook.tpl.php:53
Stack trace:
#0 /www/wwwroot/Yetiforce/cache/templates_c/basic/bfb3dbc0280ecdaf0a108ddbf9c403a11fdf6842_0.file.Webhook.tpl.php(53): in_array()
#1 /www/wwwroot/Yetiforce/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_63c218f0e7b520_31348377()
#2 /www/wwwroot/Yetiforce/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#3 /www/wwwroot/Yetiforce/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#4 /www/wwwroot/Yetiforce/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(385): Smarty_Internal_Template->render()
#5 /www/wwwroot/Yetiforce/cache/templates_c/basic/35aa1767906381698f481e6f42f141ae04341abc_0.file.EditTask.tpl.php(60): Smarty_Internal_Template->_subTemplateRender()
#6 /www/wwwroot/Yetiforce/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_63230597e8ce42_71973154()
#7 /www/wwwroot/Yetiforce/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#8 /www/wwwroot/Yetiforce/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#9 /www/wwwroot/Yetiforce/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(238): Smarty_Internal_Template->render()
#10 /www/wwwroot/Yetiforce/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#11 /www/wwwroot/Yetiforce/include/runtime/Viewer.php(210): Smarty_Internal_TemplateBase->display()
#12 /www/wwwroot/Yetiforce/modules/Settings/Workflows/views/EditTask.php(165): Vtiger_Viewer->view()
#13 /www/wwwroot/Yetiforce/include/main/WebUI.php(188): Settings_Workflows_EditTask_View->process()
#14 /www/wwwroot/Yetiforce/index.php(26): Vtiger_WebUI->process()
#15 /www/wwwroot/Yetiforce/public_html/index.php(13): require('...')
#16 {main}
2023-01-29 09:23:22.9579 [info][[application]] -</div>

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://user-images.githubusercontent.com/10198654/215314169-a0eb57a9-3617-47d0-8a69-66ed6ef4cfa7.jpg)

**Comment by mariuszkrzaczkowski** [comment]
attach the required information and attach a file from the cache directory
