### ISSUE TITLE
[bug] Error while permanent delete of record

### ISSUE THREAD

**Issue by JEEVAN28** [YetiForceCompany/YetiForceCRM#17290]
# 🐞 bug report

### ⁉️ Describe the bug
When trying to delete record permanent system hangs. Record does not get deleted.

### 🔥 How to trigger the error

1. Go to 'any contact'
2. Click on 'delete permanent record'

### 👷 

- [ ✔️] I confirm that I tested it at https://gitstable.yetiforce.com - **Works here**
- [ ✔️] I confirm that I tested it at https://gitdeveloper.yetiforce.com - **Works here**

### 📝 PHP/Apache/Nginx/Browser/CRM Logs
When checked logs I found below error

2023-09-29 13:26:34.8582 [error][] - SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared
The SQL being executed was: DELETE FROM `vtiger_crmentity` WHERE `crmid`=312052
PDOException: SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared in /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Command.php:1302
Stack trace:
#0 /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Command.php(1302): PDOStatement->execute()
#1 /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /www/wwwroot/default/crm/yf/modules/Vtiger/models/Record.php(709): yii\db\Command->execute()
#3 /www/wwwroot/default/crm/yf/modules/Vtiger/actions/Delete.php(36): Vtiger_Record_Model->delete()
#4 /www/wwwroot/default/crm/yf/include/main/WebUI.php(188): Vtiger_Delete_Action->process()
#5 /www/wwwroot/default/crm/yf/index.php(26): Vtiger_WebUI->process()
#6 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 1615 Prepared statement needs to be re-prepared
The SQL being executed was: DELETE FROM `vtiger_crmentity` WHERE `crmid`=312052 in /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Schema.php:676
Stack trace:
#0 /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Command.php(1307): yii\db\Schema->convertException()
#1 /www/wwwroot/default/crm/yf/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute()
#2 /www/wwwroot/default/crm/yf/modules/Vtiger/models/Record.php(709): yii\db\Command->execute()
#3 /www/wwwroot/default/crm/yf/modules/Vtiger/actions/Delete.php(36): Vtiger_Record_Model->delete()
#4 /www/wwwroot/default/crm/yf/include/main/WebUI.php(188): Vtiger_Delete_Action->process()
#5 /www/wwwroot/default/crm/yf/index.php(26): Vtiger_WebUI->process()
#6 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 1615
    [2] => Prepared statement needs to be re-prepared
)
-->

Kindly advice what needs to be done
**Jeevan Pendhari**

**Comment by JEEVAN28** [comment]
I searched further on Google and found below changes

SET GLOBAL table_definition_cache = 1024

I did this and then above issue is resolved. Please assist is it ok to set this value from performance point of view
