### ISSUE TITLE
[bug] Unable to update from 6.4 to 6.5 pack v1 and registration was failed

### ISSUE THREAD

**Issue by Ilamparithi-Tamizhanangu** [YetiForceCompany/YetiForceCRM#17345]
Hi,

When i try to update the CRM from 6.4 to 6.5 using automatic updates (Settings > Logs > updates), it successfully download the 6.5 pack v1 file and while installing it shows the error message as no zip was selected. 

so i tried for the manual update using [this link](https://github.com/YetiForceCompany/YetiForceCRM/releases). while upading, it shows the below error message. 
------------- 2023-11-30 07:58:18 -------------
> start drop columns
> drop column: s_yf_companies:status ... done (0s)
> drop column: s_yf_companies:type ... done (0s)
> drop column: s_yf_companies:city ... done (0s)
> drop column: s_yf_companies:address ... done (0s)
> drop column: s_yf_companies:post_code ... done (0s)
> drop column: s_yf_companies:companysize ... done (0s)
> drop column: s_yf_companies:logo ... done (0s)
> drop column: s_yf_companies:firstname ... done (0s)
> drop column: s_yf_companies:lastname ... done (0s)
> drop column: s_yf_companies:facebook ... done (0s)
> drop column: s_yf_companies:twitter ... done (0s)
> drop column: s_yf_companies:linkedin ... done (0s)
# end drop columns (0 min)
> start drop indexes
> drop index, u_yf_modentity_sequences:u_yf_modentity_sequences_tabid_fk ... (0s) | Error(12) [SQLSTATE[HY000]: General error: 1553 Cannot drop index 'u_yf_modentity_sequences_tabid_fk': needed in a foreign key constraint
The SQL being executed was: DROP INDEX `u_yf_modentity_sequences_tabid_fk` ON `u_yf_modentity_sequences`] in
#0 C:\wamp64\www\yetidb\vendor\yetiforce\yii2\db\Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'DROP INDEX `u_y...')
#1 C:\wamp64\www\yetidb\vendor\yetiforce\yii2\db\Command.php(1102): yii\db\Command->internalExecute('DROP INDEX `u_y...')
#2 C:\wamp64\www\yetidb\app\Db\Importer.php(497): yii\db\Command->execute()
#3 C:\wamp64\www\yetidb\cache\updates\updates\init.php(123): App\Db\Importer->dropIndexes(Array)
#4 C:\wamp64\www\yetidb\vtlib\Vtiger\PackageImport.php(1122): YetiForceUpdate->update()
#5 C:\wamp64\www\yetidb\vtlib\Vtiger\PackageImport.php(595): vtlib\PackageImport->importUpdate()
#6 C:\wamp64\www\yetidb\modules\Settings\ModuleManager\views\ModuleImport.php(151): vtlib\PackageImport->import('cache/usermodul...')
#7 C:\wamp64\www\yetidb\app\Controller\ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3(Object(App\Request))
#8 C:\wamp64\www\yetidb\modules\Settings\ModuleManager\views\ModuleImport.php(45): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod('importUserModul...', Object(App\Request))
#9 C:\wamp64\www\yetidb\include\main\WebUI.php(188): Settings_ModuleManager_ModuleImport_View->process(Object(App\Request))
#10 C:\wamp64\www\yetidb\index.php(26): Vtiger_WebUI->process(Object(App\Request))
#11 {main} !!!
# end drop indexes (0 min)
> start update tables (base)
> add table: s_#__reg_data ... done (0s)
> add column: s_#__tokens:one_time_use ... done (0s)
> create index: workflowtask_queue_task_id_entity_id ... done (0s)
> alter column: dav_users:userid ... done (0.1s)
> create index: u_yf_modentity_sequences_tabid_idx ... done (0s)
> alter column: vtiger_notes:filename ... done (0s)
> alter column: vtiger_users:records_limit ... done (0.1s)
# end update tables (0.07s)
> start drop tables
# end drop tables (0 min)
> start drop columns
# end drop columns (0 min)
> start drop indexes
# end drop indexes (0 min)
> start update foreign key (base)
> add: fk_dav_users, dav_users ... done (0s)
# end update foreign key (0s)

Initially yetiforce was registered and while installing the update, it was removed the registration. 

When i visit the updates page (settings > logs > updates), the update 6.5 v2 was available. it shows that update functionality was not available till registration. but when i try to update it, it successfully updated to 6.5 service pack v2 version.

the current status 
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/96602176/9b89e6ec-8ade-406c-ae3a-3a296872e96e)

mostly all the versions are failed first time and second time updated successfully. 

Could you please confirm the update status and is it possible to reinstall the 6.5 version without lossing the data. kindly guide me.

Thanks & Regards,
Rajasekaran.

**Comment by Ilamparithi-Tamizhanangu** [comment]
hi, 

is it possible to reinstall the yetiforce 6.5 version again and could you please suggest the solution for the same. 

Thanks.

with regards,
Rajasekaran
