### ISSUE TITLE
[bug] Generate one PDF file | Sales Invoices | Generating error 

### ISSUE THREAD

**Issue by s2b-git** [YetiForceCompany/YetiForceCRM#17358]
In 6.4 when you chose Generate One PDF file, system returning error. Same in Dev version

**Comment by mariuszkrzaczkowski** [comment]
![119500861-8d4fd580-bd68-11eb-84e0-9a381e3e002d](https://github.com/YetiForceCompany/YetiForceCRM/assets/10198654/88cd56b2-4c5e-4f69-bf53-4d1ecfdf99d9)

**Comment by s2b-git** [comment]
Below gif showing how to reproduce steps:

![yf-gen-one-pdf-err](https://github.com/YetiForceCompany/YetiForceCRM/assets/84110093/0fd68cae-0cc7-430d-8445-1515e5e5f5fc)

**Comment by konadrian** [comment]
Depends on code below if this code is comment or not it causes the problem. There is a problem with generate One Pdf and Pdf's for many records (it print a lot of blank pages)
https://github.com/YetiForceCompany/YetiForcePDF/commit/c766e2991734b2c5335001e7e4b38993083194e2

**Comment by ArniSamano** [comment]
> Depends on code below if this code is comment or not it causes the problem. There is a problem with generate One Pdf and Pdf's for many records (it print a lot of blank pages) [YetiForceCompany/YetiForcePDF@c766e29](https://github.com/YetiForceCompany/YetiForcePDF/commit/c766e2991734b2c5335001e7e4b38993083194e2)

Error persists. Logs returning some BC error:

2024-02-02 13:44:58.4383 [error][] - Code must be digit. get 
InvalidArgumentException: Code must be digit. get  in /var/www/my.domain.com/system/vendor/milon/barcode/src/Milon/Barcode/DNS1D.php:1435
Stack trace:
#0 /var/www/my.domain.com/system/vendor/milon/barcode/src/Milon/Barcode/DNS1D.php(426): Milon\Barcode\DNS1D->barcode_eanupc()
#1 /var/www/my.domain.com/system/vendor/milon/barcode/src/Milon/Barcode/DNS1D.php(178): Milon\Barcode\DNS1D->setBarcode()
#2 /var/www/my.domain.com/system/vendor/milon/barcode/src/Milon/Barcode/DNS1D.php(2491): Milon\Barcode\DNS1D->getBarcodePNG()
#3 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/BarcodeBox.php(141): Milon\Barcode\DNS1D->__call()
#4 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/LineBox.php(120): YetiForcePDF\Layout\BarcodeBox->generateBarcodeImage()
#5 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/BlockBox.php(337): YetiForcePDF\Layout\LineBox->appendBarcode()
#6 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/ElementBox.php(246): YetiForcePDF\Layout\BlockBox->appendBarcodeBox()
#7 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/TableRowBox.php(274): YetiForcePDF\Layout\ElementBox->buildTree()
#8 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/ElementBox.php(268): YetiForcePDF\Layout\TableRowBox->appendTableCellBox()
#9 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/TableRowGroupBox.php(112): YetiForcePDF\Layout\ElementBox->buildTree()
#10 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/ElementBox.php(264): YetiForcePDF\Layout\TableRowGroupBox->appendTableRowBox()
#11 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/TableBox.php(197): YetiForcePDF\Layout\ElementBox->buildTree()
#12 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/ElementBox.php(260): YetiForcePDF\Layout\TableBox->appendTableRowGroupBox()
#13 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/TableWrapperBox.php(95): YetiForcePDF\Layout\ElementBox->buildTree()
#14 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Layout/ElementBox.php(254): YetiForcePDF\Layout\TableWrapperBox->appendTableBox()
#15 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Html/Parser.php(228): YetiForcePDF\Layout\ElementBox->buildTree()
#16 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Document.php(861): YetiForcePDF\Html\Parser->parse()
#17 /var/www/my.domain.com/system/vendor/yetiforce/yetiforcepdf/lib/Document.php(877): YetiForcePDF\Document->parse()
#18 /var/www/my.domain.com/system/app/Pdf/Drivers/YetiForcePDF.php(277): YetiForcePDF\Document->render()
#19 /var/www/my.domain.com/system/modules/Vtiger/actions/PDF.php(200): App\Pdf\Drivers\YetiForcePDF->output()
#20 /var/www/my.domain.com/system/app/Controller/ExposeMethod.php(68): Vtiger_PDF_Action->generate()
#21 /var/www/my.domain.com/system/app/Controller/ExposeMethod.php(81): Vtiger_PDF_Action->invokeExposedMethod()
#22 /var/www/my.domain.com/system/include/main/WebUI.php(188): Vtiger_PDF_Action->process()
#23 /var/www/my.domain.com/system/index.php(27): Vtiger_WebUI->process()

**Comment by TonyM15** [comment]
> Same in Dev version

This is pretty self explanatory. I noticed exactly the same...

**Comment by deepti4666** [comment]
I have the same issue
