### ISSUE TITLE
[bug] Upgrading from 6.3.0 to 6.3.0 v8 

### ISSUE THREAD

**Issue by jcsandoval98** [YetiForceCompany/YetiForceCRM#17418]
# 🐞 bug report

### 🔥 Upgrade 6.3.0 to 6.3.0 V8

Upgrading from Version _6.3.0_ to _6.30 SecurityFix v8_ the package got downloaded but can´t be installed
![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/63214780/bc68bda0-a29b-4f85-a69c-3ae558f82bbc)

### 👎 Actual Behavior
pops the next error message

> `['tableName'=>'vtiger_project','columns'=>['targetbudget'=>NULL],'conditions'=>['targetbudget'=>'']] PDOException: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: '' in /var/www/html/vendor/yetiforce/yii2/db/Command.php:1302 Stack trace: #0 /var/www/html/vendor/yetiforce/yii2/db/Command.php(1302): PDOStatement->execute() #1 /var/www/html/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute() #2 /var/www/html/app/Db/Updater.php(120): yii\db\Command->execute() #3 /var/www/html/cache/updates/updates/init.php(130): App\Db\Updater::batchUpdate() #4 /var/www/html/cache/updates/updates/init.php(118): YetiForceUpdate->updateData() #5 /var/www/html/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update() #6 /var/www/html/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate() #7 /var/www/html/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import() #8 /var/www/html/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3() #9 /var/www/html/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod() #10 /var/www/html/include/main/WebUI.php(188): Settings_ModuleManager_ModuleImport_View->process() #11 /var/www/html/index.php(26): Vtiger_WebUI->process() #12 /var/www/html/public_html/index.php(13): require('/var/www/html/i...') #13 {main} Next yii\db\Exception: SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect INTEGER value: '' The SQL being executed was: UPDATE `vtiger_project` SET `targetbudget`=NULL WHERE `targetbudget`='' in /var/www/html/vendor/yetiforce/yii2/db/Schema.php:678 Stack trace: #0 /var/www/html/vendor/yetiforce/yii2/db/Command.php(1307): yii\db\Schema->convertException() #1 /var/www/html/vendor/yetiforce/yii2/db/Command.php(1102): yii\db\Command->internalExecute() #2 /var/www/html/app/Db/Updater.php(120): yii\db\Command->execute() #3 /var/www/html/cache/updates/updates/init.php(130): App\Db\Updater::batchUpdate() #4 /var/www/html/cache/updates/updates/init.php(118): YetiForceUpdate->updateData() #5 /var/www/html/vtlib/Vtiger/PackageImport.php(1122): YetiForceUpdate->update() #6 /var/www/html/vtlib/Vtiger/PackageImport.php(595): vtlib\PackageImport->importUpdate() #7 /var/www/html/modules/Settings/ModuleManager/views/ModuleImport.php(155): vtlib\PackageImport->import() #8 /var/www/html/app/Controller/ExposeMethod.php(68): Settings_ModuleManager_ModuleImport_View->importUserModuleStep3() #9 /var/www/html/modules/Settings/ModuleManager/views/ModuleImport.php(49): Settings_ModuleManager_ModuleImport_View->invokeExposedMethod() #10 /var/www/html/include/main/WebUI.php(188): Settings_ModuleManager_ModuleImport_View->process() #11 /var/www/html/index.php(26): Vtiger_WebUI->process() #12 /var/www/html/public_html/index.php(13): require('/var/www/html/i...') #13 {main} Additional Information: Array ( [0] => 22007 [1] => 1292 [2] => Truncated incorrect INTEGER value: '' )`

### 👷 Testing

I already tested the next:

- [x]  replacing the entire `/var/www/html/vendor/yetiforce/yii2/db/` folder with a clean copy taken from the 6.3.0 intaller
- [x] the query runs without any problem 'UPDATE vtiger_project SET targetbudget=NULL WHERE targetbudget="" ' 
- [x] updating from CLI (same)
- [x] "UPDATE yetiforce2.vtiger_project SET targetbudget = 0 "
- [x] "UPDATE yetiforce2.vtiger_project SET targetbudget = NULL "

### 📷 Screenshot of configuration

![ConfReport](https://github.com/YetiForceCompany/YetiForceCRM/assets/63214780/cbce7ba4-2d26-48d6-853c-3a38b172014d)

## cache/logs/Importer.log 
```
-------------   2024-04-11 08:40:26   -------------
> start update tables (base)
> alter column: u_#__occurrences:participants ... done    (0.2s)
> alter column: vtiger_account:employees ... done    (0.2s)
> alter column: vtiger_callhistory:duration ... done    (0.2s)
> alter column: vtiger_campaign:targetsize ... done    (0.2s)
> alter column: vtiger_campaign:expectedresponsecount ... done    (1.6s)
> alter column: vtiger_campaign:expectedsalescount ... done    (0.4s)
> alter column: vtiger_campaign:actualresponsecount ... done    (0.9s)
> alter column: vtiger_campaign:actualsalescount ... done    (0.5s)
> alter column: vtiger_leaddetails:noofemployees ... done    (0.2s)
> alter column: vtiger_outsourcedproducts:prodcount ... done    (0.2s)
> alter column: vtiger_project:targetbudget ... done    (2.3s)
> alter column: vtiger_users:records_limit ... done    (0.3s)
> alter column: u_#__cfixedassets:timing_change ... done    (0.3s)
> alter column: u_#__cfixedassets:oil_change ... done    (0.2s)
> alter column: u_#__cfixedassets:fuel_consumption ... done    (0.2s)
> alter column: u_#__cfixedassets:current_odometer_reading ... done    (0.5s)
> alter column: u_#__cfixedassets:number_repair ... done    (0.3s)
> alter column: u_#__incidentregister:peoplne_number ... done    (0.2s)
> alter column: u_#__locations:capacity ... done    (0.2s)
# end update tables    (0.24s)
> start drop tables
# end drop tables (0 min)
> start drop columns
# end drop columns (0 min)
> start drop indexes
# end drop indexes (0 min)
> start add data rows (base)
# end add data rows (0 min)
> start reset sequence
# end reset sequence (0 min)
> start update foreign key (base)
# end update foreign key    (0s)
```

### 🌍 Your Environment

| Environment                         | Version / Name |
| ----------------------------------- | -------------- |
| YetiForce                           |  6.3.0
| Web server (name and version)       |    nginx 1.14.2           |
| PHP                                 |  7.4. 21        |
| Operating System (name and version) |    Docker Oficial Container     |
| Database (name and version)         |  MySQL 8.0.35               |
| Service Pack version                |                |

### ❓ Additional context

Im using Cloudflare, the original instalation was inside a hosting with softaculous, but was really slow and cron wasnt supported with that hosting. We migrated to docker when the latest was 6.2.0 and didnt had problems before.

**Comment by jcsandoval98** [comment]
# Config/Standard modules/Edit fields

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/63214780/da28457b-11cb-499e-b3e9-1f69989465ab)


i tried just skiping the patch and jump to 6.4.0

i already took a look in the db schema at 6.4.0 and 6.3.0 side by side and this bug is related to the version mismatch, the table `vtiger_trees_templates` has the sintax for 6.4.0 but web interface say im at 6.3.0

**Comment by jcsandoval98** [comment]
#16541 has the same bug, and is using mysql 8 too... so ill get a container with mysql 5.6 and discard the version problem

im running the query that appears at the error message, but from mysql workbench 8.0, not sure if php behave differently.

ill mount the db and post what happend

**Comment by jcsandoval98** [comment]
Working again, was related to MYSQL 8, im running now MySQL 5.6 and everything is running.

the collation and charset in MySQL 8 is diferent, so mysql dumps had to be reformated to utf8 and utf8_bin. otherwise some tables didnt import.
