### ISSUE TITLE
[bug] YF V7, Good Received Note - Error in Total calculation

### ISSUE THREAD

**Issue by Ilamparithi-Tamizhanangu** [YetiForceCompany/YetiForceCRM#17441]
Hi,

While creating the Goods Received note, it create the following error. 

![image](https://github.com/YetiForceCompany/YetiForceCRM/assets/96602176/981b2b26-e2bf-42af-96ae-ba4ec7fd3c0f)

The system log file contents are given below. 

2024-04-27 22:24:58.8946 [error][[IllegalValue]] - purifyByType: 31050
 - 0 app\Purifier.php:568  >>  App\Log->error('purifyByType: 31050','IllegalValue')
 - 1 app\Purifier.php:655  >>  App\Purifier->purifyByType('31050','Number')
 - 2 app\Purifier.php:642  >>  App\Purifier->purifyMultiDimensionArray('31050','Number')
 - 3 app\Request.php:311  >>  App\Purifier->purifyMultiDimensionArray([array,array],[Integer,Integer,Integer,Text,Text,Text,Number,Number,Number,Html])
 - 4 modules\Vtiger\models\Record.php:1407  >>  App\Request->getMultiDimensionArray('inventory',[Integer,Integer,Integer,Text,Text,Text,Number,Number,Number,Html])
 - 5 modules\Vtiger\actions\Save.php:201  >>  Vtiger_Record_Model->initInventoryDataFromRequest()
 - 6 modules\Vtiger\actions\Save.php:96  >>  Vtiger_Save_Action->getRecordModelFromRequest()
 - 7 modules\Vtiger\actions\Save.php:76  >>  Vtiger_Save_Action->saveRecord()
 - 8 include\main\WebUI.php:161  >>  Vtiger_Save_Action->process()
 - 9 index.php:26  >>  Vtiger_WebUI->process()
2024-04-27 22:24:58.8952 [error][] - ERR_NOT_ALLOWED_VALUE||31050
App\Exceptions\IllegalValue: ERR_NOT_ALLOWED_VALUE||31050 in app\Purifier.php:569
Stack trace:
#0 app\Purifier.php(655): App\Purifier::purifyByType('31050', 'Number')
#1 app\Purifier.php(642): App\Purifier::purifyMultiDimensionArray('31050', 'Number')
#2 app\Request.php(311): App\Purifier::purifyMultiDimensionArray(Array, Array)
#3 modules\Vtiger\models\Record.php(1407): App\Request->getMultiDimensionArray('inventory', Array)
#4 modules\Vtiger\actions\Save.php(201): Vtiger_Record_Model->initInventoryDataFromRequest(Object(App\Request))
#5 modules\Vtiger\actions\Save.php(96): Vtiger_Save_Action->getRecordModelFromRequest(Object(App\Request))
#6 modules\Vtiger\actions\Save.php(76): Vtiger_Save_Action->saveRecord(Object(App\Request))
#7 include\main\WebUI.php(161): Vtiger_Save_Action->process(Object(App\Request))
#8 index.php(26): Vtiger_WebUI->process(Object(App\Request))
#9 {main}
 - 0 include\main\WebUI.php:164  >>  App\Log->error('ERR_NOT_ALLOWED_VALUE||31050
App\\Exceptions\\IllegalValue: ERR_NOT_ALLOWED_VALUE||31050 in app\\Purifier.php:569
Stack trace:
#0 app\\Purifier.php(655): App\\Purifier::purifyByType(\'31050\', \'Number\')
#1 app\\Purifier.php(642): App\\Purifier::purifyMultiDimensionArray(\'31050\', \'Number\')
#2 app\\Request.php(311): App\\Purifier::purifyMultiDimensionArray(Array, Array)
#3 modules\\Vtiger\\models\\Record.php(1407): App\\Request->getMultiDimensionArray(\'inventory\', Array)
#4 modules\\Vtiger\\actions\\Save.php(201): Vtiger_Record_Model->initInventoryDataFromRequest(Object(App\\Request))
#5 modules\\Vtiger\\actions\\Save.php(96): Vtiger_Save_Action->getRecordModelFromRequest(Object(App\\Request))
#6 modules\\Vtiger\\actions\\Save.php(76): Vtiger_Save_Action->saveRecord(Object(App\\Request))
#7 include\\main\\WebUI.php(161): Vtiger_Save_Action->process(Object(App\\Request))
#8 index.php(26): Vtiger_WebUI->process(Object(App\\Request))
#9 {main}')
 - 1 index.php:26  >>  Vtiger_WebUI->process()
2024-04-27 22:24:58.8256 [info][[application]] - 
$_POST = ['_csrf'=>'sid:15c4b30d3db2a1313302ce3ee59e29e66d75fff9,1714236870','module'=>'IGRN','fromView'=>'Create','action'=>'Save','mappingRelatedField'=>'[]','listFilterFields'=>'[]','defaultOtherEventDuration'=>'[{"activitytype":"Call","duration":"60"},{"activitytype":"Meeting","duration":"60"},{"activitytype":"Task","duration":"60"}]','subject'=>'in8','popupReferenceModule'=>'Products','storageid'=>'3998','storageid_display'=>'B4','vendorid'=>'4005','vendorid_display'=>'VVDN','igrn_status'=>'PLL_ACCEPTED','acceptance_date'=>'27-04-2024','assigned_user_id'=>'1','shownerid'=>'','private'=>'0','description'=>'','attention'=>'','inventory'=>[1=>['seq'=>'1','name'=>'1026','ean'=>'','unit'=>'Qty','subunit'=>'','qty'=>'2','price'=>'31050','total'=>'62 100','comment1'=>'PCB Lightweight cable, 10ft w/4-socket plug to 3 BNC plugs'],2=>['seq'=>'2','name'=>'1027','ean'=>'','unit'=>'Day(s)','subunit'=>'','qty'=>'3','price'=>'5000','total'=>'15 000','comment1'=>'<strong>Code development for the custom application</strong>'],'_NUM_'=>['seq'=>'_NUM_','name'=>'','ean'=>'','unit'=>'','subunit'=>'','qty'=>'1','price'=>'0','total'=>'0','comment1'=>'']]]
$_COOKIE = ['YTSID'=>'4ahm2gevkk7r30drouecivahmr']
$_SESSION = ['CSP_TOKEN'=>'f7448eac6690fa7ae4549fb1af6ebbbf290d0ede80151bcf988e912b2b10d87e','last_activity'=>1714236898.829117,'fingerprint'=>'d520c7a8-421b-4563-b955-f5abc56b97ec','user_agent'=>'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36','UserAuthMethod'=>'PASSWORD','app_unique_key'=>'890b5c117c0d941e1522dcfb4a1953447bbe7c91','user_name'=>'rajajeni','full_user_name'=>'Administrator Rajasekaran','authenticated_user_id'=>1,'DashBoard'=>['Home'=>['LastDashBoardId'=>1]],'lvs'=>['IGRN'=>['viewname'=>92]]]
_HEADERS = ['Host'=>'localhost','Connection'=>'keep-alive','Content-Length'=>'6203','Cache-Control'=>'max-age=0','sec-ch-ua'=>'"Chromium";v="124", "Google Chrome";v="124", "Not-A.Brand";v="99"','sec-ch-ua-mobile'=>'?0','sec-ch-ua-platform'=>'"Windows"','Origin'=>'null','DNT'=>'1','Upgrade-Insecure-Requests'=>'1','Content-Type'=>'multipart/form-data; boundary=----WebKitFormBoundaryV7BuvS5GqGyBfA5h','User-Agent'=>'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36','Accept'=>'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7','Sec-Fetch-Site'=>'same-origin','Sec-Fetch-Mode'=>'navigate','Sec-Fetch-User'=>'?1','Sec-Fetch-Dest'=>'document','Accept-Encoding'=>'gzip, deflate, br, zstd','Accept-Language'=>'en-GB,en-US;q=0.9,en;q=0.8','Cookie'=>'YTSID=4ahm2gevkk7r30drouecivahmr']
$stability = ['error_reporting'=>'E_ALL (32767)','output_buffering'=>'4096']
$security = ['HTTPS'=>'Off','public_html'=>'Off','display_errors'=>'On','session.cookie_samesite'=>'Strict','expose_php'=>'On','disable_functions'=>'']
$libraries = ['apcu'=>'LBL_NO','imagick'=>'LBL_NO','pdo_sqlsrv'=>'LBL_NO','mongodb'=>'LBL_NO']
$performance = ['xdebug'=>'On']
$environment = ['open_basedir'=>false,'openssl.cafile'=>false,'openssl.capath'=>false]
$functionalVerification = ['branding'=>'No']
$headers = ['Header: server'=>'Apache/2.4.58 (Win64) PHP/8.1.26 mod_fcgid/2.3.10-dev','Header: x-powered-by'=>'PHP/8.1.26','Header: access-control-allow-methods'=>false,'Header: access-control-allow-origin'=>false,'Header: referrer-policy'=>false,'Header: expect-ct'=>false,'Header: x-frame-options'=>false,'Header: x-content-type-options'=>false,'Header: x-robots-tag'=>false,'Header: x-permitted-cross-domain-policies'=>false,'Header: content-security-policy'=>false]
====================================================================================================================================

kindly guide me to solve the same.

Thanks & Regards,
Rajasekaran

**Comment by Ilamparithi-Tamizhanangu** [comment]
Hi,

This issue is due to change in the digit grouping (user preference) section.

https://github.com/YetiForceCompany/YetiForceCRM/issues/17446#issue-2272990779

Created the new issue and closing this.
