### ISSUE TITLE
[bug] Problem z generowaniem PDF

### ISSUE THREAD

**Issue by TurzyRGD** [YetiForceCompany/YetiForceCRM#17529]
Problem z generowaniem pliku PDF gdy dodam zmienną: 
$(custom : UserRecordsList|__MODULE_NAME__|__FIELDS_TO_SHOW__|__CONDITIONS__|__ORDER_BY__|__LIMIT__|__VIEW_ID__|__ADVANCE_CONDITIONS__)$

lub

$(custom : RecordsList)$.

Kod błędu:
[error][] - Call to undefined method YetiForcePDF\Layout\LineBox::getRowSpan()
Error: Call to undefined method YetiForcePDF\Layout\LineBox::getRowSpan() in /var/www/html/vendor/yetiforce/yetiforcepdf/lib/Layout/ElementBox.php:119
Stack trace:
#0 /var/www/html/vendor/yetiforce/yetiforcepdf/lib/Html/Parser.php(240): YetiForcePDF\Layout\ElementBox->fixTables()
#1 /var/www/html/vendor/yetiforce/yetiforcepdf/lib/Document.php(889): YetiForcePDF\Html\Parser->parse()
#2 /var/www/html/vendor/yetiforce/yetiforcepdf/lib/Document.php(907): YetiForcePDF\Document->parse()
#3 /var/www/html/app/Pdf/Drivers/YetiForcePDF.php(277): YetiForcePDF\Document->render()
#4 /var/www/html/modules/Vtiger/actions/PDF.php(205): App\Pdf\Drivers\YetiForcePDF->output()
#5 /var/www/html/app/Controller/ExposeMethod.php(68): Vtiger_PDF_Action->generate()
#6 /var/www/html/app/Controller/ExposeMethod.php(81): Vtiger_PDF_Action->invokeExposedMethod()
#7 /var/www/html/include/main/WebUI.php(161): Vtiger_PDF_Action->process()
#8 /var/www/html/index.php(26): Vtiger_WebUI->process()
#9 /var/www/html/public_html/index.php(13): require('...')
#10 {main}

**Comment by mariuszkrzaczkowski** [comment]
![github](https://github.com/YetiForceCompany/YetiForceCRM/assets/10198654/babb68e3-c985-4d6e-8e87-00e70e534dc9)

**Comment by Marco31Bike** [comment]
are you setting var in table?

**Comment by rskrzypczak** [comment]
no activity, closing.
