### ISSUE TITLE
[BUG] Member Login v 2.3.49

### ISSUE THREAD

**Issue by waw555** [YetiForceCompany/YetiForceCRM#2137]
Not included in the system after installing the version 2.3.49

**Comment by waw555** [comment]
LOG

[22-Oct-2015 11:59:02 Asia/Yekaterinburg] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'default.vtiger_cron_task' doesn't exist' in /www/default/include/database/PearDatabase.php:326
Stack trace:
#0 /www/default/include/database/PearDatabase.php(326): PDO->prepare('SELECT * FROM v...')
#1 /www/default/vtlib/Vtiger/Cron.php(287): PearDatabase->pquery('SELECT * FROM v...', Array)
#2 /www/default/vtlib/Vtiger/Cron.php(355): Vtiger_Cron::querySilent('SELECT * FROM v...', Array)
#3 /www/default/cron/vtigercron.php(31): Vtiger_Cron::listAllActiveInstances()
#4 {main}
  thrown in /www/default/include/database/PearDatabase.php on line 326
[22-Oct-2015 12:00:02 Asia/Yekaterinburg] PHP Notice:  Undefined index: current_user in /www/default/include/runtime/Globals.php on line 22
[22-Oct-2015 12:00:02 Asia/Yekaterinburg] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'default.vtiger_users' doesn't exist' in /www/default/include/database/PearDatabase.php:326
Stack trace:
#0 /www/default/include/database/PearDatabase.php(326): PDO->prepare('SELECT id FROM ...')
#1 /www/default/modules/Users/Users.php(1542): PearDatabase->pquery('SELECT id FROM ...', Array)
#2 /www/default/modules/Users/Users.php(1559): Users::getActiveAdminId()
#3 /www/default/cron/vtigercron.php(38): Users::getActiveAdminUser()
#4 {main}
  thrown in /www/default/include/database/PearDatabase.php on line 326
[22-Oct-2015 12:01:04 Asia/Yekaterinburg] PHP Notice:  Undefined index: current_user in /www/default/include/runtime/Globals.php on line 22
[22-Oct-2015 12:01:04 Asia/Yekaterinburg] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'default.vtiger_users' doesn't exist' in /www/default/include/database/PearDatabase.php:326
Stack trace:
#0 /www/default/include/database/PearDatabase.php(326): PDO->prepare('SELECT id FROM ...')
#1 /www/default/modules/Users/Users.php(1542): PearDatabase->pquery('SELECT id FROM ...', Array)
#2 /www/default/modules/Users/Users.php(1559): Users::getActiveAdminId()
#3 /www/default/cron/vtigercron.php(38): Users::getActiveAdminUser()
#4 {main}

**Comment by waw555** [comment]
I help someone else?

Because I can not log in to the system after installation, respectively, and the test also can not ((((

**Comment by waw555** [comment]
Log for version 2.3.101

[26-Oct-2015 16:37:01 Asia/Yekaterinburg] PHP Notice:  Undefined index: current_user in /www/default/include/runtime/Globals.php on line 22
[26-Oct-2015 16:37:01 Asia/Yekaterinburg] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'default.vtiger_users' doesn't exist' in /www/default/include/database/PearDatabase.php:326
Stack trace:
#0 /www/default/include/database/PearDatabase.php(326): PDO->prepare('SELECT id FROM ...')
#1 /www/default/modules/Users/Users.php(1546): PearDatabase->pquery('SELECT id FROM ...', Array)
#2 /www/default/modules/Users/Users.php(1563): Users::getActiveAdminId()
#3 /www/default/cron/vtigercron.php(39): Users::getActiveAdminUser()
#4 {main}
  thrown in /www/default/include/database/PearDatabase.php on line 326
[26-Oct-2015 16:38:01 Asia/Yekaterinburg] PHP Notice:  Undefined index: current_user in /www/default/include/runtime/Globals.php on line 22
[26-Oct-2015 16:38:01 Asia/Yekaterinburg] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'default.vtiger_users' doesn't exist' in /www/default/include/database/PearDatabase.php:326
Stack trace:
#0 /www/default/include/database/PearDatabase.php(326): PDO->prepare('SELECT id FROM ...')
#1 /www/default/modules/Users/Users.php(1546): PearDatabase->pquery('SELECT id FROM ...', Array)
#2 /www/default/modules/Users/Users.php(1563): Users::getActiveAdminId()
#3 /www/default/cron/vtigercron.php(39): Users::getActiveAdminUser()
#4 {main}
  thrown in /www/default/include/database/PearDatabase.php on line 326

**Comment by waw555** [comment]
Table vtiger users and there is evidence it has

**Comment by waw555** [comment]
There is a solution to my problem, because I still can not get into the system after the installation has already tried all the options, nothing changes, how could not log in, and I can not. And I have !!!!

**Comment by waw555** [comment]
Install ver. 2.3.172

Specify a password during the installation, but again does not go.

But it comes with the password: admin

The password can be changed later in the user settings

**Comment by waw555** [comment]
Install ver. 2.3.595

Specify a password during the installation, but again does not go.

But it comes with the password: admin

The password can be changed later in the user settings

**Comment by bpabiszczak** [comment]
It has been fixed in the latest version, as well as incorrect transfer of login data [passwords]. Check again and you still have this problem you'll have to give us some more details.
