### ISSUE TITLE
synchronizacja CalDAV oraz CardDAV

### ISSUE THREAD

**Issue by witer30** [YetiForceCompany/YetiForceCRM#2263]
Po włączeniu logów oraz wyświetlaniu błędów itp.. mam coś takiego jeśli chodzi o synchronizacje...
Logi DAV.log
```
[10-Nov-2015 09:17:20 Europe/Sarajevo] PHP Notice:  Undefined property: stdClass::$crmUserId in /home/nakon/public_html/libraries/SabreDAV/Yeti/WebDAV_Directory.php on line 100

[10-Nov-2015 09:17:20 Europe/Sarajevo] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'crmnakon.vtiger_files_dir' doesn't exist' in /home/xxx/public_html/libraries/SabreDAV/Yeti/WebDAV_Directory.php:100

Stack trace: 
#0 /home/nakon/public_html/libraries/SabreDAV/Yeti/WebDAV_Directory.php(100): PDOStatement->execute(Array)
#1 /home/nakon/public_html/api/dav.php(52): Yeti\WebDAV_Directory->getRootChild()
#2 {main} thrown in /home/xxx/public_html/libraries/SabreDAV/Yeti/WebDAV_Directory.php on line 100
```

W phpmyadmin sprawdzałem bazę danych i nie mam tabeli vtiger_files_dir.
Dodatkowo na stronie logowania spotkała mnie niespodzianka bo tyle "krzaczków" to jeszcze nie widziałem... Czy to jest normalne?
```
Strict Standards: Declaration of AntlrLexer::matchAny() should be compatible with BaseRecognizer::matchAny($input) in /home/nakon/public_html/libraries/antlr/AntlrLexer.php on line 0

Strict Standards: Declaration of AntlrLexer::recover() should be compatible with BaseRecognizer::recover($input, $re) in /home/nakon/public_html/libraries/antlr/AntlrLexer.php on line 0

Strict Standards: Declaration of AntlrLexer::traceIn() should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in /home/nakon/public_html/libraries/antlr/AntlrLexer.php on line 0

Strict Standards: Declaration of AntlrLexer::traceOut() should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in /home/nakon/public_html/libraries/antlr/AntlrLexer.php on line 0

Strict Standards: Declaration of AntlrParser::traceIn() should be compatible with BaseRecognizer::traceIn($ruleName, $ruleIndex, $inputSymbol) in /home/nakon/public_html/libraries/antlr/AntlrParser.php on line 0

Strict Standards: Declaration of AntlrParser::traceOut() should be compatible with BaseRecognizer::traceOut($ruleName, $ruleIndex, $inputSymbol) in /home/nakon/public_html/libraries/antlr/AntlrParser.php on line 0

Strict Standards: Declaration of Users::saveentity() should be compatible with CRMEntity::saveentity($module, $fileid = '') in /home/nakon/public_html/modules/Users/Users.php on line 0

Strict Standards: Declaration of Users::uploadAndSaveFile() should be compatible with CRMEntity::uploadAndSaveFile($id, $module, $file_details, $attachmentType = 'Attachment') in /home/nakon/public_html/modules/Users/Users.php on line 0

Strict Standards: Declaration of Users::insertIntoEntityTable() should be compatible with CRMEntity::insertIntoEntityTable($table_name, $module, $fileid = '') in /home/nakon/public_html/modules/Users/Users.php on line 0

Strict Standards: Declaration of Users::save() should be compatible with CRMEntity::save($module_name, $fileid = '') in /home/nakon/public_html/modules/Users/Users.php on line 0

Strict Standards: Declaration of Users::get_column_value() should be compatible with CRMEntity::get_column_value($columnname, $fldvalue, $fieldname, $uitype, $datatype = '') in /home/nakon/public_html/modules/Users/Users.php on line 0

Strict Standards: Declaration of Vtiger_Module::unsetRelatedList() should be compatible with Vtiger_ModuleBasic::unsetRelatedList() in /home/nakon/public_html/vtlib/Vtiger/Module.php on line 20

Strict Standards: Declaration of Vtiger_LanguageExport::__initExport() should be compatible with Vtiger_PackageExport::__initExport($module, $moduleInstance) in /home/nakon/public_html/vtlib/Vtiger/LanguageExport.php on line 17

Strict Standards: Declaration of Vtiger_LanguageExport::export_Dependencies() should be compatible with Vtiger_PackageExport::export_Dependencies($moduleInstance) in /home/nakon/public_html/vtlib/Vtiger/LanguageExport.php on line 17

Strict Standards: Declaration of Vtiger_LanguageImport::initImport() should be compatible with Vtiger_PackageImport::initImport($zipfile, $overwrite = true) in /home/nakon/public_html/vtlib/Vtiger/LanguageImport.php on line 17

Strict Standards: Non-static method HTTP_Session::_init() should not be called statically in /home/nakon/public_html/libraries/HTTP_Session/Session.php on line 803

Strict Standards: Non-static method HTTP_Session::localName() should not be called statically in /home/nakon/public_html/libraries/HTTP_Session/Session.php on line 728

Strict Standards: Non-static method HTTP_Session::start() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 51

Strict Standards: Non-static method HTTP_Session::name() should not be called statically in /home/nakon/public_html/libraries/HTTP_Session/Session.php on line 155

Strict Standards: Non-static method HTTP_Session::detectID() should not be called statically in /home/nakon/public_html/libraries/HTTP_Session/Session.php on line 158

Strict Standards: Non-static method HTTP_Session::useCookies() should not be called statically in /home/nakon/public_html/libraries/HTTP_Session/Session.php on line 291

Strict Standards: Non-static method HTTP_Session::name() should not be called statically in /home/nakon/public_html/libraries/HTTP_Session/Session.php on line 292

Strict Standards: Non-static method HTTP_Session::id() should not be called statically in /home/nakon/public_html/libraries/HTTP_Session/Session.php on line 159

Strict Standards: Non-static method HTTP_Session::id() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 52

Strict Standards: Non-static method HTTP_Session::isIdle() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 57

Strict Standards: Non-static method HTTP_Session::isExpired() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 57

Notice: Undefined index: authenticated_user_id in /home/nakon/public_html/include/main/WebUI.php on line 54

Strict Standards: Non-static method HTTP_Session::get() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 76

Notice: Undefined index: translated_language in /home/nakon/public_html/include/runtime/Globals.php on line 22

Strict Standards: Non-static method HTTP_Session::get() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 76

Notice: Undefined index: language in /home/nakon/public_html/include/runtime/BaseModel.php on line 35

Notice: Undefined index: authenticated_user_id in /home/nakon/public_html/include/main/WebUI.php on line 54

Strict Standards: Non-static method HTTP_Session::get() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 76

Deprecated: Non-static method Vtiger_Functions::getBrowserInfo() should not be called statically, assuming $this from incompatible context in /home/nakon/public_html/include/runtime/Controller.php on line 91

Notice: Undefined property: Users_Login_View::$viewer in /home/nakon/public_html/include/runtime/Controller.php on line 165

Notice: Undefined index: translated_language in /home/nakon/public_html/include/runtime/Globals.php on line 22

Strict Standards: Non-static method HTTP_Session::get() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 76

Notice: Undefined index: language in /home/nakon/public_html/include/runtime/BaseModel.php on line 35

Notice: Undefined index: theme in /home/nakon/public_html/include/runtime/BaseModel.php on line 35

Notice: Undefined index: translated_language in /home/nakon/public_html/include/runtime/Globals.php on line 22

Strict Standards: Non-static method HTTP_Session::get() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 76

Notice: Undefined index: language in /home/nakon/public_html/include/runtime/BaseModel.php on line 35

Notice: Undefined index: translated_language in /home/nakon/public_html/include/runtime/Globals.php on line 22

Strict Standards: Non-static method HTTP_Session::get() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 76

Notice: Undefined index: language in /home/nakon/public_html/include/runtime/BaseModel.php on line 35

Notice: Undefined index: translated_language in /home/nakon/public_html/include/runtime/Globals.php on line 22

Strict Standards: Non-static method HTTP_Session::get() should not be called statically in /home/nakon/public_html/include/http/Session.php on line 76

Notice: Undefined index: language in /home/nakon/public_html/include/runtime/BaseModel.php on line 35

Strict Standards: Non-static method PearDatabase::getDBConfig() should not be called statically in /home/nakon/public_html/include/database/PearDatabase.php on line 83
<br /> <b>Notice</b>: Undefined index: companyname in <b>/home/nakon/public_html/cache/templates_c/vlayout/f5f7e8db82388297cdf93233f5acfc4546120cb5.file.Login.Default.tpl.php</b> on line <b>47</b><br /> 
```
oraz 
![image](https://cloud.githubusercontent.com/assets/11491482/11057724/bdd0ea80-878d-11e5-9956-7b9b209b6ca8.png)

**Comment by mariuszkrzaczkowski** [comment]
W pliku config/api.php ustaw $enableWebDAV = false;

**Comment by witer30** [comment]
Więc po ustawieniu $enableWebDAV = false mogę się logować do servera DAV... i mój błąd ISE 500 już nie występuje.... 
Teraz potestuje synchronizację... 
dzięki za pomoc... dam znać czy synch jest ok, przetestuje kilku klientów...

**Comment by florek41** [comment]
Sprawdź jak wygląda u Ciebie synchronizacja zadań w kalendarzu.
U mnie po synchronizacji z iOS (iPhone) w kalendarzu pozostaje pustka - jedynie w przypomnieniach (osobna aplikacja) pojawiają się wpisy. Obednie nie mam żadnego urządzenia z Androidem, żeby sprawdzić jak to wygląda tam.

Podobnie zresztą jest kiedy dodam kalendarz do Horde (klient mail z kalendarzem) - nic się nie pojawia.
Za to jednak po dodaniu albo w Horde albo Iphone wydarzenia w kalendarzu to wszystko się synchronizuje w obie strony - ale znów w YF pustka.

Daj znać jak to działa u Ciebie !

**Comment by witer30** [comment]
generalnie nie zdążyłem tego przetestować... bo jak uruchomiłem klienta na outlooku to mi ściągnął i wysłał wpisy kalendarza w dwie strony... ale później w cronie zobaczyłem że caldav wisi i jakby nie może rozpocząć nowego zadania bo nie skończył poprzedniego więc wszystko stanęło...
Z resztą już to zgłosiłem. Fajnie jakby można było zresetować to zadanie aby rozpocząć od nowa... ale niestety nie wiem jak to zrobić..
Pierwsze wrażenie z synchronizacji bardzo fajne, ale niestety kolorów ustawionych w CRM nie przenosi, nawet jeśli mam te same kolory w outlooku ustawione i zmodyfikować rejestry tak aby przepuszczały kategorie/kolory przez imap bo jest to po blokowane... Co do samej synchronizacji to chyba trzeba jeszcze popracować... Chętnie przetestuje innego klienta aby zobaczyć czy klient nie powoduje zwiechy... 
PS. Podobnie backup też mi wisi od kilku dni no i nic nie pomaga aby go wskrzesić...

**Comment by florek41** [comment]
Okazuje się, że mam ten sam problem. Jeśli chodzi o restart zadania to on próbuje się uruchomić o widać po tym, że ostatnio zakończył działanie 4h temu ale próbował uruchomić 4min. temu - więc chce, ale nie umie - w innym wątku #2266 opisałem swój błąd - najprawdopodobniej u Ciebie jest to samo.

Swoją drogą - może jeden wątek z CalDav wystarczy ? Teraz narobiło się ich tyle, że nie wiadomo co i gdzie pisać.
