### ISSUE TITLE
Fatal error install

### ISSUE THREAD

**Issue by kjradv** [YetiForceCompany/YetiForceCRM#2651]
```
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /var/htdocs/crm/test/include/database/PearDatabase.php:116 Stack trace: #0 /var/htdocs/crm/test/include/database/PearDatabase.php(116): PDO->__construct('mysql:host=;dbn...', NULL, NULL, Array) #1 /var/htdocs/crm/test/include/database/PearDatabase.php(67): PearDatabase->connect() #2 /var/htdocs/crm/test/include/database/PearDatabase.php(86): PearDatabase->__construct(NULL, NULL, NULL, NULL, NULL, NULL) #3 /var/htdocs/crm/test/install/models/InitSchema.php(90): PearDatabase::getInstance() #4 /var/htdocs/crm/test/install/models/InitSchema.php(28): Install_InitSchema_Model->setDefaultUsersAccess() #5 /var/htdocs/crm/test/install/views/Index.php(233): Install_InitSchema_Model->initialize() #6 /var/htdocs/crm/test/install/views/Index.php(89): Install_Index_view->Step7(Object(Vtiger_Request)) #7 /var/htdocs/crm/test/install/Install.php(23): Inst in /var/htdocs/crm/test/include/database/PearDatabase.php on line 116
```

**Comment by bpabiszczak** [comment]
version?

**Comment by kjradv** [comment]
$YetiForce_current_version = '2.3.1008';
webserver - ngix
