### ISSUE TITLE
Cron workflow locked in a state  "running" when trigger execute condition is equal to "Execution schedule (defined time intervals)" and workflow task not executed

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#2960]
tested on: https://gitdeveloper.yetiforce.com

- create a trigger (i have tested in the contact module) with condition "Execution schedule (defined time intervals)" 
- Execute frequency = Specific date, 
- choose the running time twenty minutes later
- skip conditions
- add a random task (i tested update field and add todo)
- wait for the cron is executed

Perhaps the error is connected to the webservices

cache/logs/phpError.log:

[10-May-2016 11:07:01 Europe/Amsterdam] PHP Fatal error:  Uncaught exception 'WebServiceException' in /include/Webservices/VtigerWebserviceObject.php:70
Stack trace:
#0 /include/Webservices/Utils.php(475): VtigerWebserviceObject::fromName(Object(PearDatabase), NULL)
#1 /modules/com_vtiger_workflow/tasks/VTUpdateFieldsTask.inc(36): vtws_getModuleHandlerFromName(NULL, Object(Users))
#2 /modules/com_vtiger_workflow/WorkFlowScheduler.php(116): VTUpdateFieldsTask->doTask(Object(VTWorkflowEntity))
#3 /cron/modules/com_vtiger_workflow/com_vtiger_workflow.service(70): WorkFlowScheduler->queueScheduledWorkflowTasks()
#4 /cron/vtigercron.php(74): require_once('/var/www/...')
#5 {main}
thrown in /include/Webservices/VtigerWebserviceObject.php

**Comment by nic86** [comment]
thanks
