### ISSUE TITLE
Failed to parse time string 

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [YetiForceCompany/YetiForceCRM#3061]
![xxxx](https://cloud.githubusercontent.com/assets/10198654/15540852/d8998b0a-2289-11e6-9706-e05afef4a714.png)
DateTime::__construct(): Failed to parse time string (2016-05-25 5) at position 11 (5): Unexpected character
```
#0 C:\www\YetiForceCRM\include\fields\DateTimeField.php(330): DateTime->__construct('2016-05-25 5', Object(DateTimeZone))
#1 C:\www\YetiForceCRM\include\fields\DateTimeField.php(275): DateTimeField::convertTimeZone('2016-05-25 5', 'Europe/Warsaw', 'Europe/Sarajevo')
#2 C:\www\YetiForceCRM\modules\Vtiger\uitypes\Time.php(102): DateTimeField::convertToUserTimeZone('2016-05-25 5')
#3 C:\www\YetiForceCRM\modules\Vtiger\models\Field.php(116): Vtiger_Time_UIType->getDisplayValue('5', false, false, false)
#4 C:\www\YetiForceCRM\modules\Calendar\models\Field.php(75): Vtiger_Field_Model->getDisplayValue('5', false, false, false)
#5 C:\www\YetiForceCRM\modules\ModTracker\models\Field.php(86): Calendar_Field_Model->getDisplayValue('5', false, false, false)
#6 C:\www\YetiForceCRM\cache\templates_c\basic\98758761412d64c65dc1e118ca10e04711b3ff45_0.file.RecentActivitiesTimeLine.tpl.php(87): ModTracker_Field_Model->getDisplayValue('5')
#7 C:\www\YetiForceCRM\libraries\Smarty\libs\sysplugins\smarty_template_resource_base.php(122): content_5745a148e56684_29259946(Object(Smarty_Internal_Template))
#8 C:\www\YetiForceCRM\libraries\Smarty\libs\sysplugins\smarty_template_compiled.php(199): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#9 C:\www\YetiForceCRM\libraries\Smarty\libs\sysplugins\smarty_internal_template.php(159): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#10 C:\www\YetiForceCRM\libraries\Smarty\libs\sysplugins\smarty_internal_templatebase.php(191): Smarty_Internal_Template->render(false, 0)
#11 C:\www\YetiForceCRM\libraries\Smarty\libs\sysplugins\smarty_internal_templatebase.php(94): Smarty_Internal_TemplateBase->_execute('modules/Vtiger/...', NULL, NULL, NULL, 0)
#12 C:\www\YetiForceCRM\include\runtime\Viewer.php(193): Smarty_Internal_TemplateBase->fetch('modules/Vtiger/...')
#13 C:\www\YetiForceCRM\modules\Vtiger\views\Detail.php(402): Vtiger_Viewer->view('RecentActivitie...', 'Calendar', 'true')
#14 [internal function]: Vtiger_Detail_View->showRecentActivities(Object(Vtiger_Request))
#15 C:\www\YetiForceCRM\include\runtime\Controller.php(89): call_user_func_array(Array, Array)
#16 C:\www\YetiForceCRM\modules\Vtiger\views\Detail.php(188): Vtiger_Controller->invokeExposedMethod('showRecentActiv...', Object(Vtiger_Request))
#17 C:\www\YetiForceCRM\include\main\WebUI.php(220): Vtiger_Detail_View->process(Object(Vtiger_Request))
#18 C:\www\YetiForceCRM\index.php(23): Vtiger_WebUI->process(Object(Vtiger_Request))
#19 {main}
```

**Comment by rskrzypczak** [comment]
I can't recreate the error you mentioned.
It was most likely fixed at some point.
