### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tabid' in 'where clause'

### ISSUE THREAD

**Issue by majkel89** [YetiForceCompany/YetiForceCRM#3421]
Sql error while saving account

#### Issue
````
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tabid' in 'where clause'

SELECT cur_id, prefix, postfix FROM vtiger_modentity_num WHERE tabid = ?

#0 PearDatabase->checkError('SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tabid' in 'where clause'','','SELECT cur_id, prefix, postfix FROM vtiger_modentity_num WHERE tabid = ?',[6]) in include/database/PearDatabase.php(378): 
#1 PearDatabase->pquery('SELECT cur_id, prefix, postfix FROM vtiger_modentity_num WHERE tabid = ?',[6]) in include/fields/RecordNumber.php(46): 
#2 includes\fields\RecordNumber->incrementNumber('6') in include/CRMEntity.php(505): 
#3 CRMEntity->insertIntoEntityTable('vtiger_account','Accounts','') in include/CRMEntity.php(127): 
#4 CRMEntity->saveentity('Accounts','') in include/CRMEntity.php(845): 
#5 CRMEntity->save('Accounts') in modules/Vtiger/models/Module.php(181): 
#6 Vtiger_Module_Model->saveRecord() in modules/Vtiger/models/Record.php(294): 
#7 Vtiger_Record_Model->save() in modules/Vtiger/actions/Save.php(81): 
#8 Vtiger_Save_Action->saveRecord() in modules/Vtiger/actions/Save.php(58): 
#9 Vtiger_Save_Action->process() in include/main/WebUI.php(220): 
#10 Vtiger_WebUI->process() in index.php(24): 
````

#### Actual Behavior
Error while saving form

#### Expected Behavior
Creating accounts should be possible without any problems

#### How to trigger the error
1. Create new account
2. Fill all necessary fields (name, assigned to, legal form)
3. Fill Data verification field with some value
4. Save the form

#### Your Environment
https://gitdeveloper.yetiforce.com/index.php

**Comment by vovpff** [comment]
@majkel89 @bpabiszczak @TomaszQr  this is global bug what happens when you try to add new record for any module
dev. 3.1.1064

**Comment by mariuszkrzaczkowski** [comment]
try now

**Comment by vovpff** [comment]
@mariuszkrzaczkowski dev.3.1.1066 works well

**Comment by majkel89** [comment]
works fine
