### ISSUE TITLE
[bug]Corporate Emails related module list view

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3530]
version: 3.2.150

in module Coprporate emails when select a related record(in all module related) it's duplicated in all record.

![gifrecord_2016-09-12_113013](https://cloud.githubusercontent.com/assets/18703633/18431363/e53c0a64-78dc-11e6-84f4-6b39281e68f1.gif)

in local installation when try to open related view in mail company in cache/logs/system.log 

```
#0 LoggerCategory->error('Error Vtiger_Loader::getComponentClassName(View, InOSSMailViewRelation, Leads): Handler not found') in include/Loader.php(169): 
#1 Vtiger_Loader->getComponentClassName('View','InOSSMailViewRelation','Leads') in modules/Vtiger/views/Detail.php(470): 
#2 Vtiger_Detail_View->showRelatedList() in (): 
#3 call_user_func_array([object(OSSMailView_Detail_View),showRelatedList],[object(Vtiger_Request)]) in include/runtime/Controller.php(89): 
#4 Vtiger_Controller->invokeExposedMethod('showRelatedList') in modules/Vtiger/views/Detail.php(194): 
#5 Vtiger_Detail_View->process() in include/main/WebUI.php(220): 
#6 Vtiger_WebUI->process() in index.php(25): 

Mon Sep 12 11:17:13 2016,481 [15411] ERROR System - Error Vtiger_Loader::getComponentClassName(View, InRelation, Leads): Handler not found
Mon Sep 12 11:17:13 2016,481 [15411] ERROR System - 
#0 LoggerCategory->error('Error Vtiger_Loader::getComponentClassName(View, InRelation, Leads): Handler not found') in include/Loader.php(169): 
#1 Vtiger_Loader->getComponentClassName('View','InRelation','Leads') in modules/Vtiger/views/Detail.php(474): 
#2 Vtiger_Detail_View->showRelatedList() in (): 
#3 call_user_func_array([object(OSSMailView_Detail_View),showRelatedList],[object(Vtiger_Request)]) in include/runtime/Controller.php(89): 
#4 Vtiger_Controller->invokeExposedMethod('showRelatedList') in modules/Vtiger/views/Detail.php(194): 
#5 Vtiger_Detail_View->process() in include/main/WebUI.php(220): 
#6 Vtiger_WebUI->process() in index.php(25): 
```

**Comment by konadrian** [comment]
Does the error still occur?
![animation](https://cloud.githubusercontent.com/assets/3193498/18504655/b75c5814-7a63-11e6-81f4-8b6a6a2589b8.gif)

**Comment by nic86** [comment]
in version 3.2.179 the error not exist. how it can be solved in version 3.2?
thank you.

**Comment by konadrian** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/06c8c7270cb1bc8d76afcb9133412934d3c29721

**Comment by nic86** [comment]
thanks
