### ISSUE TITLE
[bug] Parse DateTime field - function convertTimeZone

### ISSUE THREAD

**Issue by nic86** [YetiForceCompany/YetiForceCRM#3537]
Version: 3.2

When try to add an "todo" from a related module(eg. activity tab from detail lead view -> add event) this error block the saving process:

```
{"success":false,"error":{"code":"DateTime::__construct(): Failed to parse time string (2016-09-13 1) at position 11 (1): Unexpected character","message":"DateTime::__construct(): Failed to parse time string (2016-09-13 1) at position 11 (1): Unexpected character"}}<pre>#0 /var/www/yetiforce/include/fields/DateTimeField.php(330): DateTime->__construct('2016-09-13 1', Object(DateTimeZone))
#1 /var/www/yetiforce/include/fields/DateTimeField.php(275): DateTimeField::convertTimeZone('2016-09-13 1', 'Europe/Amsterda...', 'Europe/Amsterda...')
#2 /var/www/yetiforce/modules/Vtiger/uitypes/Time.php(102): DateTimeField::convertToUserTimeZone('2016-09-13 1')
#3 /var/www/yetiforce/modules/Vtiger/models/Field.php(115): Vtiger_Time_UIType->getDisplayValue('1', 47713, Object(Calendar_Record_Model), true)
#4 /var/www/yetiforce/modules/Calendar/models/Field.php(75): Vtiger_Field_Model->getDisplayValue('1', 47713, Object(Calendar_Record_Model), true)
#5 /var/www/yetiforce/modules/Vtiger/helpers/TextParser.php(304): Calendar_Field_Model->getDisplayValue('1', 47713, Object(Calendar_Record_Model), true)
#6 /var/www/yetiforce/modules/Vtiger/helpers/TextParser.php(216): Vtiger_TextParser_Helper->recordChangesDisplayValue('1', Object(Calendar_Field_Model))
#7 /var/www/yetiforce/modules/Vtiger/helpers/TextParser.php(109): Vtiger_TextParser_Helper->recordChanges('listOfAllValues')
#8 [internal function]: Vtiger_TextParser_Helper->{closure}(Array)
#9 /var/www/yetiforce/modules/Vtiger/helpers/TextParser.php(112): preg_replace_callback('/\\((\\w+): ([\\w\\...', Object(Closure), '(recordChanges:...')
#10 /var/www/yetiforce/modules/Vtiger/helpers/TextParser.php(71): Vtiger_TextParser_Helper->parseFunctions()
#11 /var/www/yetiforce/modules/Home/models/Notification.php(154): Vtiger_TextParser_Helper->parse()
#12 /var/www/yetiforce/modules/Home/models/Notification.php(119): Home_Notification_Model->parseContent()
#13 /var/www/yetiforce/modules/ModTracker/handlers/ModTrackerHandler.php(191): Home_Notification_Model->save()
#14 /var/www/yetiforce/include/events/VTEventTrigger.inc(158): ModTrackerHandler->handleEvent('vtiger.entity.a...', Object(VTEntityData))
#15 /var/www/yetiforce/include/events/VTEventsManager.inc(125): VTEventTrigger->trigger(Object(VTEntityData))
#16 /var/www/yetiforce/include/CRMEntity.php(850): VTEventsManager->triggerEvent('vtiger.entity.a...', Object(VTEntityData))
#17 /var/www/yetiforce/modules/Vtiger/models/Module.php(181): CRMEntity->save('Calendar')
#18 /var/www/yetiforce/modules/Vtiger/models/Record.php(294): Vtiger_Module_Model->saveRecord(Object(Calendar_Record_Model))
#19 /var/www/yetiforce/modules/Calendar/models/Record.php(142): Vtiger_Record_Model->save()
#20 /var/www/yetiforce/modules/Vtiger/actions/Save.php(81): Calendar_Record_Model->save()
#21 /var/www/yetiforce/modules/Calendar/actions/SaveAjax.php(22): Vtiger_Save_Action->saveRecord(Object(Vtiger_Request))
#22 /var/www/yetiforce/include/main/WebUI.php(220): Calendar_SaveAjax_Action->process(Object(Vtiger_Request))
#23 /var/www/yetiforce/index.php(25): Vtiger_WebUI->process(Object(Vtiger_Request))
#24 {main}</pre>
```

**Comment by konadrian** [comment]
Does the error still occur? Because I added a record with no errors today.
![animation](https://cloud.githubusercontent.com/assets/3193498/18506161/da24cc76-7a6a-11e6-8fba-7ca85ed30f1e.gif)

Could you attach a screenshot, a link or a video that shows where that error occurs, and describe step by step how to recreate it?

**Comment by nic86** [comment]
in version 3.2, only in lead module with user no admin, when I move between the related tab in the log shows the following errors cache/logs/system.log

```
Wed Sep 14 11:35:17 2016,549 [10460] ERROR System - Error Vtiger_Loader::getComponentClassName(View, InLeadsRelation, Calendar): Handler not found
Wed Sep 14 11:35:17 2016,549 [10460] ERROR System - 
#0 LoggerCategory->error('Error Vtiger_Loader::getComponentClassName(View, InLeadsRelation, Calendar): Handler not found') in include/Loader.php(169): 
#1 Vtiger_Loader->getComponentClassName('View','InLeadsRelation','Calendar') in modules/Vtiger/views/Detail.php(470): 
#2 Vtiger_Detail_View->showRelatedList() in (): 
#3 call_user_func_array([object(Leads_Detail_View),showRelatedList],[object(Vtiger_Request)]) in include/runtime/Controller.php(89): 
#4 Vtiger_Controller->invokeExposedMethod('showRelatedList') in modules/Vtiger/views/Detail.php(194): 
--
Wed Sep 14 11:35:18 2016,523 [10460] ERROR System - Error Vtiger_Loader::getComponentClassName(View, InLeadsRelation, Contacts): Handler not found
Wed Sep 14 11:35:18 2016,523 [10460] ERROR System - 
#0 LoggerCategory->error('Error Vtiger_Loader::getComponentClassName(View, InLeadsRelation, Contacts): Handler not found') in include/Loader.php(169): 
#1 Vtiger_Loader->getComponentClassName('View','InLeadsRelation','Contacts') in modules/Vtiger/views/Detail.php(470): 
#2 Vtiger_Detail_View->showRelatedList() in (): 
#3 call_user_func_array([object(Leads_Detail_View),showRelatedList],[object(Vtiger_Request)]) in include/runtime/Controller.php(89): 
#4 Vtiger_Controller->invokeExposedMethod('showRelatedList') in modules/Vtiger/views/Detail.php(194): 
--
Wed Sep 14 11:35:18 2016,523 [10460] ERROR System - Error Vtiger_Loader::getComponentClassName(View, InRelation, Contacts): Handler not found
Wed Sep 14 11:35:18 2016,523 [10460] ERROR System - 
#0 LoggerCategory->error('Error Vtiger_Loader::getComponentClassName(View, InRelation, Contacts): Handler not found') in include/Loader.php(169): 
#1 Vtiger_Loader->getComponentClassName('View','InRelation','Contacts') in modules/Vtiger/views/Detail.php(474): 
#2 Vtiger_Detail_View->showRelatedList() in (): 
#3 call_user_func_array([object(Leads_Detail_View),showRelatedList],[object(Vtiger_Request)]) in include/runtime/Controller.php(89): 
#4 Vtiger_Controller->invokeExposedMethod('showRelatedList') in modules/Vtiger/views/Detail.php(194): 
--
Wed Sep 14 11:35:19 2016,405 [10460] ERROR System - Error Vtiger_Loader::getComponentClassName(View, InLeadsRelation, Documents): Handler not found
Wed Sep 14 11:35:19 2016,405 [10460] ERROR System - 
#0 LoggerCategory->error('Error Vtiger_Loader::getComponentClassName(View, InLeadsRelation, Documents): Handler not found') in include/Loader.php(169): 
#1 Vtiger_Loader->getComponentClassName('View','InLeadsRelation','Documents') in modules/Vtiger/views/Detail.php(470): 
#2 Vtiger_Detail_View->showRelatedList() in (): 
#3 call_user_func_array([object(Leads_Detail_View),showRelatedList],[object(Vtiger_Request)]) in include/runtime/Controller.php(89): 
#4 Vtiger_Controller->invokeExposedMethod('showRelatedList') in modules/Vtiger/views/Detail.php(194): 
--
Wed Sep 14 11:35:19 2016,405 [10460] ERROR System - Error Vtiger_Loader::getComponentClassName(View, InRelation, Documents): Handler not found
Wed Sep 14 11:35:19 2016,406 [10460] ERROR System - 
#0 LoggerCategory->error('Error Vtiger_Loader::getComponentClassName(View, InRelation, Documents): Handler not found') in include/Loader.php(169): 
#1 Vtiger_Loader->getComponentClassName('View','InRelation','Documents') in modules/Vtiger/views/Detail.php(474): 
#2 Vtiger_Detail_View->showRelatedList() in (): 
#3 call_user_func_array([object(Leads_Detail_View),showRelatedList],[object(Vtiger_Request)]) in include/runtime/Controller.php(89): 
#4 Vtiger_Controller->invokeExposedMethod('showRelatedList') in modules/Vtiger/views/Detail.php(194): 
--
Wed Sep 14 11:35:21 2016,004 [10460] ERROR System - Error Vtiger_Loader::getComponentClassName(View, InLeadsRelation, OSSMailView): Handler not found
Wed Sep 14 11:35:21 2016,005 [10460] ERROR System - 
#0 LoggerCategory->error('Error Vtiger_Loader::getComponentClassName(View, InLeadsRelation, OSSMailView): Handler not found') in include/Loader.php(169): 
#1 Vtiger_Loader->getComponentClassName('View','InLeadsRelation','OSSMailView') in modules/Vtiger/views/Detail.php(470): 
#2 Vtiger_Detail_View->showRelatedList() in (): 
#3 call_user_func_array([object(Leads_Detail_View),showRelatedList],[object(Vtiger_Request)]) in include/runtime/Controller.php(89): 
#4 Vtiger_Controller->invokeExposedMethod('showRelatedList') in modules/Vtiger/views/Detail.php(194): 
--

```

and when add todo the log show this error:
```
Wed Sep 14 11:36:04 2016,362 [10391] ERROR System - DateTime::__construct(): Failed to parse time string (2016-09-14 1) at position 11 (1): Unexpected character => /var/www/organizzo/include/fields/DateTimeField.php:330
Wed Sep 14 11:36:04 2016,362 [10391] ERROR System - 
#0 LoggerCategory->error('DateTime::__construct(): Failed to parse time string (2016-09-14 1) at position 11 (1): Unexpected character => /var/www/organizzo/include/fields/DateTimeField.php:330') in include/main/WebUI.php(226): 
#1 Vtiger_WebUI->process() in index.php(25): 

```

**Comment by nic86** [comment]
@konadrian The first error write in log because in /include/Loader.php in function getComponentClassName the throw new Exception is execute after log writing

```
$log = vglobal('log');
		$log->error("Error Vtiger_Loader::getComponentClassName($componentType, $componentName, $moduleName): Handler not found");
		
		throw new \Exception\AppException('LBL_HANDLER_NOT_FOUND');
```


and in Vtiger/views/Detail.php in function showRelatedList there are multi call to getComponentClassName in  two block try catch.

```
try {
			$targetControllerClass = Vtiger_Loader::getComponentClassName('View', 'In' . $moduleName . 'Relation', $relatedModuleName);
		} catch (\Exception\AppException $e) {
			try {
				// If any module wants to have same view for all the relation, then invoke this.
				$targetControllerClass = Vtiger_Loader::getComponentClassName('View', 'InRelation', $relatedModuleName);
			} catch (\Exception\AppException $e) {
				// Default related list
				$targetControllerClass = Vtiger_Loader::getComponentClassName('View', 'RelatedList', $moduleName);
			}
		}
```


the solutions It might be move the exception above the log in /include/Loader.php in function getComponentClassName:

```
throw new \Exception\AppException('LBL_HANDLER_NOT_FOUND');

$log = vglobal('log');
		$log->error("Error Vtiger_Loader::getComponentClassName($componentType, $componentName, $moduleName): Handler not found");
			
```

but the second error, the creation of "todo" from related module, is still present.

**Comment by TomaszQr** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/commit/04ccec0f745b37c061efdd7ec749ef1bf2a6520e

**Comment by TomaszQr** [comment]
1st error - fixed loading class names, the errors should not appear anymore
2nd error - doesn't exist in the current version
