### ISSUE TITLE
Mailscanner issues

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#3743]
#### Issue

Mailscanner no longer scanning.

#### Actual Behavior

[07-Nov-2016 16:50:14 Africa/Harare] PHP Fatal error:  Uncaught exception 'Exception\NoPermittedToRecord' with message 'LBL_RECORD_DELETE' in /var/www/html/include/CRMEntity.php:784
Stack trace:
#0 /var/www/html/modules/Vtiger/models/Record.php(351): CRMEntity->retrieve_entity_info(103247, 'HelpDesk')
#1 /var/www/html/modules/OSSMailScanner/scanneractions/BindHelpDesk.php(23): Vtiger_Record_Model::getInstanceById(103247, 'HelpDesk')
#2 /var/www/html/modules/OSSMailScanner/models/Record.php(217): OSSMailScanner_BindHelpDesk_ScannerAction->process(Object(OSSMail_Mail_Model))
#3 /var/www/html/modules/OSSMailScanner/models/Record.php(285): OSSMailScanner_Record_Model::executeActions(Array, Object(OSSMail_Mail_Model), 'Sent Items')
#4 /var/www/html/modules/OSSMailScanner/models/Record.php(411): OSSMailScanner_Record_Model::mail_Scan(Resource id #406, Array, 'Sent Items', '6968', 42)
#5 /var/www/html/modules/OSSMailScanner/cron/action.php(17): OSSMailScanner_Record_Model->executeCron('cli - ')
#6 /var/www/html/cron/vtigercron.php(74): require_once('/var/www/html/m...') in /var/www/html/include/CRMEntity.php on line 784
[07-Nov-2016 17:49:47 Africa/Harare] PHP Fatal error:  Uncaught exception 'Exception\NoPermittedToRecord' with message 'LBL_RECORD_DELETE' in /var/www/html/include/CRMEntity.php:784

#### How to trigger the error

1. cronatab -e 
2. */3 * * * *  /usr/bin/flock -n /tmp/yeti.lock sh /var/www/html/cron/vtigercron.sh >> /var/www/html/cache/logs/cron.log

#### Your Environment

* YetiForce Version used: 3.4.237
* Browser name and version: chrome Version 54.0.2840.90 (64-bit)
* Environment name and version:
* Operating System and version: Ubuntu 16

**Comment by kabelo38** [comment]
great it works!!!
