### ISSUE TITLE
[BUG] ForgotPassword dont work

### ISSUE THREAD

**Issue by ezbank** [YetiForceCompany/YetiForceCRM#4453]
When I use password forgotten then I enter my password and send it shows 500 error.
Test on v4.0 and v4.0.209
```
[29-May-2017 19:19:49 Asia/Bangkok] PHP Deprecated:  Non-static method Vtiger_ShortURL_Helper::getInstance() should not be called statically in /home/domain/domain.com/modules/Users/actions/ForgotPassword.php on line 30
[29-May-2017 19:19:49 Asia/Bangkok] PHP Fatal error:  Uncaught WebServiceException: Failed to change password in /home/domain/domain.com/include/Webservices/Custom/ChangePassword.php:50
Stack trace:
#0 /home/domain/domain.com/modules/Users/actions/ForgotPassword.php(42): vtws_changePassword('19x1', '', 'XXXXXX', 'XXXXXX', Object(Users))
#1 /home/domain/domain.com/modules/Users/actions/ForgotPassword.php(105): Users_ForgotPassword_Action->changePassword(Object(Vtiger_Request))
#2 /home/domain/domain.com/modules/Users/actions/ForgotPassword.php(110): Users_ForgotPassword_Action::run(Object(Vtiger_Request))
#3 {main}
  thrown in /home/domain/domain.com/include/Webservices/Custom/ChangePassword.php on line 50
```

**Comment by ezbank** [comment]
What updates do you have?

**Comment by ezbank** [comment]
Still exist in the version v4.0.431

**Comment by ezbank** [comment]
I see a few edits #4d61bdc, but it looks like the problem still exists

**Comment by ezbank** [comment]
Still exist in the version v4.2.53
[18-Aug-2017 00:21:43 Asia/Bangkok] PHP Fatal error:  Uncaught WebServiceException: Failed to change password in /home/users/crm/include/Webservices/Custom/ChangePassword.php:50
Stack trace:
#0 /home/users/crm/modules/Users/actions/ForgotPassword.php(42): vtws_changePassword('19x1', '', 'passwords', 'passwords', Object(Users))
#1 /home/users/crm/modules/Users/actions/ForgotPassword.php(105): Users_ForgotPassword_Action->changePassword(Object(App\Request))
#2 /home/users/crm/modules/Users/actions/ForgotPassword.php(110): Users_ForgotPassword_Action::run(Object(App\Request))
#3 {main}
  thrown in /home/users/crm/include/Webservices/Custom/ChangePassword.php on line 50
