### ISSUE TITLE
Major issues with Caldav

### ISSUE THREAD

**Issue by projakethomas** [YetiForceCompany/YetiForceCRM#4456]
#### Issue
I have enable the API in config/api.php, went I do a sync from

#### Actual Behavior
Created key for Caldav  applied in outlook using caldav synchronizer.

#### Expected Behavior
In api/dav.php there is ICS file but only from outlook but they are not being populated inside of YT calendar?

#### How to trigger the error
1. Sync calendar from outlook

#### Your Environment

* YetiForce Version used: 3.4.0
* Browser name and version: Chrome
* Operating System and version: Windows Server 2012 R2

**Comment by mariuszkrzaczkowski** [comment]
In version 4.0.0 several fixes have been added. Test the latest version

**Comment by Protocorewebcreative** [comment]
Thanks for getting back to me Marius but when I install the 4.0.0 the password I set up in the install wizard don't work when the application has installed any thoughts?

**Comment by Protocorewebcreative** [comment]
for eg I have installed on this domain but the login details that I set up via install wizard are not working?

http://crm.curo.recyclingmanagement.com

**Comment by Protocorewebcreative** [comment]
could you send me a detualt export of one that is work do that I can import user and test it if you don't mind??

**Comment by Protocorewebcreative** [comment]
Error I'm getting after installed locally

Error!!!
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'yt56.vtiger_tab' doesn't exist Failed to prepare SQL: SELECT * FROM `vtiger_tab`

**Comment by Protocorewebcreative** [comment]
could you send me a preinstall instance so I can test out on my side?

**Comment by mariuszkrzaczkowski** [comment]
System requirements checked?
Before installation, turn on the logs and see what is wrong
check mysqlnd

**Comment by Protocorewebcreative** [comment]
System requirements all ok, how can I turn on the logs?

**Comment by Protocorewebcreative** [comment]
Would I just applied this into the .htaccess 

[https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html#htaccess](https://yetiforce.com/en/implementer/installation-updates/103-web-server-requirements.html#htaccess)

**Comment by Protocorewebcreative** [comment]
error in  CalDavSynchronizer
```

CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '405' ('Method Not Allowed'). Message:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>405 Method Not Allowed</title>
</head><body>
<h1>Method Not Allowed</h1>
<p>The requested method GET is not allowed for the URL /api/dav.php/calendars/admin/YFCalendar/.</p>
<p>Additionally, a 405 Method Not Allowed
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetVersions>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetVersions>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.<GetAllVersions>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`7.<Synchronize>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.ContextCreatingSynchronizerDecorator`7.<Synchronize>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Scheduling.SynchronizationProfileRunner.<RunAndRescheduleNoThrow>d__22.MoveNext()
```

**Comment by Protocorewebcreative** [comment]
Install successful now I'm doing the CalDAV sync but only outlook to yeti not both ways also the ics are not going into yetiforce where have I gone wrong

**Comment by mariuszkrzaczkowski** [comment]
Write how you solve the installation problem will help other users. Check that cron works properly and check logs

**Comment by Protocorewebcreative** [comment]
there has been no log file created, I had to install the instance on another server so must be a missing module. 

Only thing that's in the logs is 

```
[06-Jun-2017 11:03:07 Europe/London] PHP Notice:  Only variable references should be returned by reference in C:\xampp\htdocs\crm\vendor\yetiforce\Fields\Owner.php on line 186

[06-Jun-2017 11:03:08 Europe/London] PHP Notice:  Undefined offset: 113 in C:\xampp\htdocs\crm\cache\templates_c\basic\3192f56aee2cf598e27185dd3e44be3d93c34f8c_0.file.Reminders.tpl.php on line 49
```

But surely this has nothing to do with the CalDav?

**Comment by projakethomas** [comment]
This is my API.php file 
```

$enabledServices = [
	'dav',
	'webservices',
	'webservice',
];
/* +***************   DAV   **************** */
$enableBrowser = true;
$enableCardDAV = true;
$enableCalDAV = true;
$enableWebDAV = true;

/* +*********   Webservice config  ********* */
$API_CONFIG = [
	'ENCRYPT_DATA_TRANSFER' => false,
	'AUTH_METHOD' => 'Basic',
	'PRIVATE_KEY' => 'config/private.key',
	'PUBLIC_KEY' => 'config/public.key',
];

```

**Comment by projakethomas** [comment]
any ideas?

**Comment by projakethomas** [comment]
@mariuszkrzaczkowski What do you think it could be ?

**Comment by mariuszkrzaczkowski** [comment]
Make sure you have a properly configured server, because you should not see notice in the error logs
Take a screenshot of the configuration

**Comment by projakethomas** [comment]
What configuration sorry, Thank you for coming back to me @mariuszkrzaczkowski

**Comment by mariuszkrzaczkowski** [comment]
https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index

**Comment by projakethomas** [comment]
See below.
![system req](https://user-images.githubusercontent.com/12185813/26873977-c2a8d896-4b73-11e7-9802-6d9bc75d9d2b.png)

**Comment by projakethomas** [comment]
Could it be APCu I can get this installed if need?

**Comment by mariuszkrzaczkowski** [comment]
show full details from server configuration. apcu is opcjonal

**Comment by projakethomas** [comment]
![system req](https://user-images.githubusercontent.com/12185813/26884727-5f6d6150-4b98-11e7-85a6-a1652d30f86a.png)

**Comment by projakethomas** [comment]
This all ok? @mariuszkrzaczkowski

**Comment by projakethomas** [comment]
Why is it not working for me is it working on your demo can I try?

**Comment by WalterLuis** [comment]
Corrects the errors that appear in the last screenshot you passed, the red lines is that it does not meet the requirement, these parameters are configured in a file called php.ini, find it in your system.

The less red lines you have, the less errors you'll find in CRM

**Comment by projakethomas** [comment]
I've tested the demo one and thats not working in my outlook CalDav would it be something to do on the PC side?

**Comment by projakethomas** [comment]
The error I got CalDav Synchronizer this is using your demo?


```
CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '403' ('Forbidden'). Message:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /api/dav.php/calendars/demo/YFCalendar/
on this server.<br />
</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>

   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReadResponse>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetVersions>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<GetVersions>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.<GetAllVersions>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at GenSync.Synchronization.Synchronizer`7.<Synchronize>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GenSync.Synchronization.ContextCreatingSynchronizerDecorator`7.<Synchronize>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Scheduling.SynchronizationProfileRunner.<RunAndRescheduleNoThrow>d__22.MoveNext()

```

**Comment by projakethomas** [comment]
Could this be the issues on my local Pc? Would I have to give outlook admin privilege

**Comment by projakethomas** [comment]
Also say's php 5.5 is recommended so I changed that to 5.5 from 5.6 now I'm getting 500 error?

Something really wrong?

Can anyone help me?

**Comment by mariuszkrzaczkowski** [comment]
```
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /api/dav.php/calendars/demo/YFCalendar/
on this server.<br />
</p>
<p>Additionally, a 403 Forbidden
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```
He writes that you do not have permissions problem on the side of apache or file permissions.
Ask the administrator to solve this problem.

**Comment by projakethomas** [comment]
What file's do I need to set the permissions on?

**Comment by projakethomas** [comment]
Bere in mind this is your demo I test it with?

**Comment by mariuszkrzaczkowski** [comment]
You have a problem with the server configuration then it must check the administrator

**Comment by projakethomas** [comment]
could you let me what the problem is with my configuration? as I tested it with your **demo** and still didn't work in my CalDAV synchronizer?

**Comment by projakethomas** [comment]
@mariuszkrzaczkowski ?
