### ISSUE TITLE
Mailscanner issues

### ISSUE THREAD

**Issue by kabelo38** [YetiForceCompany/YetiForceCRM#4653]
Strange enough a couple of days we had problems with our mail server and was sorted out, a day later i started seeing strange behavior caused by the mail scanner below is what i have in my cron logs

2017-07-27 12:40:03 | ERROR: LBL_MAIL_SCANNER_ACTION - Cron task execution throwed exception.
Sorry! Attempt to access restricted file.
#0 /var/www/html/include/CRMEntity.php(60): vtlib\Deprecated::checkFileAccessForInclusion('modules//.php')
#1 /var/www/html/modules/Vtiger/models/Record.php(516): CRMEntity::getInstance(NULL)
#2 /var/www/html/modules/com_vtiger_workflow/VTJsonCondition.php(44): Vtiger_Record_Model::getInstanceById('117,2137702')
#3 /var/www/html/modules/com_vtiger_workflow/VTWorkflowManager.php(352): VTJsonCondition->evaluate('[{"fieldname":"...', Object(HelpDesk_Record_Model))
#4 /var/www/html/modules/Vtiger/handlers/Workflow.php(86): Workflow->evaluate(Object(HelpDesk_Record_Model), '2155386')
#5 /var/www/html/vendor/yetiforce/EventHandler.php(286): Vtiger_Workflow_Handler->entityAfterSave(Object(App\EventHandler))
#6 /var/www/html/modules/Vtiger/models/Module.php(246): App\EventHandler->trigger('EntityAfterSave')
#7 /var/www/html/modules/Vtiger/models/Record.php(379): Vtiger_Module_Model->saveRecord(Object(HelpDesk_Record_Model))
#8 /var/www/html/modules/OSSMailScanner/scanneractions/CreatedHelpDesk.php(70): Vtiger_Record_Model->save()
#9 /var/www/html/modules/OSSMailScanner/scanneractions/CreatedHelpDesk.php(32): OSSMailScanner_CreatedHelpDesk_ScannerAction->add(Object(OSSMail_Mail_Model))
#10 /var/www/html/modules/OSSMailScanner/models/Record.php(215): OSSMailScanner_CreatedHelpDesk_ScannerAction->process(Object(OSSMail_Mail_Model))
#11 /var/www/html/modules/OSSMailScanner/models/Record.php(283): OSSMailScanner_Record_Model::executeActions(Array, Object(OSSMail_Mail_Model), 'INBOX')
#12 /var/www/html/modules/OSSMailScanner/models/Record.php(421): OSSMailScanner_Record_Model::mail_Scan(Resource id #209, Array, 'INBOX', '46447', 0)
#13 /var/www/html/modules/OSSMailScanner/cron/action.php(17): OSSMailScanner_Record_Model->executeCron('cli - ')
#14 /var/www/html/cron/vtigercron.php(73): require_once('/var/www/html/m...')
#15 {main}

#### Your Environment

* YetiForce Version used: 4.0 stable
* Browser name and version:
* Environment name and version:
* Operating System and version: Ubuntu 16.04

**Comment by kabelo38** [comment]
@bpabiszczak

**Comment by kabelo38** [comment]
Error was caused due to a mailbox with 5000 mails
