### ISSUE TITLE
fatal error in calendar module 

### ISSUE THREAD

**Issue by vahid-jml** [YetiForceCompany/YetiForceCRM#4665]
Hi 
in calendar module i get this error : 
Error!!!
Handler not found .

/*
#0 modules/Calendar/models/CalendarFilters.php(32): Vtiger_Loader::getComponentClassName('CalendarFilter', '.gitkee', 'Calendar')
#1 modules/Calendar/models/CalendarFilters.php(18): Calendar_CalendarFilters_Model->__construct()
#2 modules/Calendar/views/Calendar.php(89): Calendar_CalendarFilters_Model::getCleanInstance()
#3 include/main/WebUI.php(98): Calendar_Calendar_View->postProcess(Object(App\Request))
#4 include/main/WebUI.php(223): Vtiger_WebUI->triggerPostProcess(Object(Calendar_Calendar_View), Object(App\Request))
#5 index.php(20): Vtiger_WebUI->process(Object(App\Request))
#6 public_html/index.php(11): require('/home/gitdevelo...')
#7 {main}
*/

version : 4.0.520

**Comment by vahid-jml** [comment]
hi 
in the CalendarFilter directory in calendar module there is a .gitkee file that Vtiger_Loader class(in include/loader.php) try to load it and that's  cause the error .
