### ISSUE TITLE
error in mass sms sending

### ISSUE THREAD

**Issue by pflaz** [YetiForceCompany/YetiForceCRM#4669]
#### Issue
When I try to send mass sms there is no result ('please wait' from 10 minutes). 

#### Actual Behavior
In logs I can find:

[30-Jul-2017 21:06:18 Europe/Sarajevo] PHP Fatal error:  Uncaught Error: Call to undefined method SMSNotifier::save() in /home/***/public_html/crm/modules/SMSNotifier/SMSNotifier.php:52
Stack trace:
#0 /home/***/public_html/crm/modules/SMSNotifier/models/Record.php(17): SMSNotifier::sendsms('123', Array, 1, Array, 'SMSNotifier')
#1 /home/***/public_html/crm/modules/SMSNotifier/actions/MassSaveAjax.php(54): SMSNotifier_Record_Model::SendSMS('123', Array, 1, Array, 'SMSNotifier')
#2 /home/***/public_html/crm/include/main/WebUI.php(218): SMSNotifier_MassSaveAjax_Action->process(Object(Vtiger_Request))
#3 /home/***/public_html/crm/index.php(21): Vtiger_WebUI->process(Object(Vtiger_Request))
#4 {main}
  thrown in /home/***/public_html/crm/modules/SMSNotifier/SMSNotifier.php on line 52

**By the way - How can I send sms to only one contact? I cannot find a button on contact's or on company's page...**

#### Your Environment

* YetiForce Version used: 4.0.0
* Browser name and version: IE, FF, Chrome
* PHP 7.0
* Operating System and version: Win10

**Comment by pflaz** [comment]
Some more information from YetiForce logs.
I have created new file: smsprovider.php in 'providers' folder.

[30-Jul-2017 20:38:40 Europe/Sarajevo] PHP Fatal error:  Uncaught Error: Class 'SMSNotifier_smsprovider_Provider' not found in /home/***/public_html/crm/modules/SMSNotifier/models/Provider.php:24
Stack trace:
#0 /home/***/public_html/crm/modules/SMSNotifier/models/Provider.php(40): SMSNotifier_Provider_Model::getInstance('smsprovider')
#1 /home/***/public_html/crm/modules/Settings/SMSNotifier/models/ProviderField.php(20): SMSNotifier_Provider_Model::getAll()
#2 /home/***/public_html/crm/modules/Settings/SMSNotifier/views/Edit.php(29): Settings_SMSNotifier_ProviderField_Model::getAll()
#3 /home/***/public_html/crm/include/main/WebUI.php(218): Settings_SMSNotifier_Edit_View->process(Object(Vtiger_Request))
#4 /home/***/public_html/crm/index.php(21): Vtiger_WebUI->process(Object(Vtiger_Request))
#5 {main}
  thrown in /home/***/public_html/crm/modules/SMSNotifier/models/Provider.php on line 24

**Comment by pflaz** [comment]
I have found the solution - I had to change class name in MySMSProvider.php file to 'SMSNotifier_MySMSProvider_Provider'

But now I have the next problem - when I try to send mass sms there is no result ('please wait' from 10 minutes). In logs I can find:

[30-Jul-2017 21:06:18 Europe/Sarajevo] PHP Fatal error:  Uncaught Error: Call to undefined method SMSNotifier::save() in /home/***/public_html/crm/modules/SMSNotifier/SMSNotifier.php:52
Stack trace:
#0 /home/***/public_html/crm/modules/SMSNotifier/models/Record.php(17): SMSNotifier::sendsms('123', Array, 1, Array, 'SMSNotifier')
#1 /home/***/public_html/crm/modules/SMSNotifier/actions/MassSaveAjax.php(54): SMSNotifier_Record_Model::SendSMS('123', Array, 1, Array, 'SMSNotifier')
#2 /home/***/public_html/crm/include/main/WebUI.php(218): SMSNotifier_MassSaveAjax_Action->process(Object(Vtiger_Request))
#3 /home/***/public_html/crm/index.php(21): Vtiger_WebUI->process(Object(Vtiger_Request))
#4 {main}
  thrown in /home/***/public_html/crm/modules/SMSNotifier/SMSNotifier.php on line 52

**Comment by pflaz** [comment]
The issue is out-of-date because in 4.1.0 version everything works good.
