### ISSUE TITLE
dev 4.2.24 open and edit calendar records

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#4881]
#### Issue

Clicking to open and edit buttons returns errors.

![image](https://user-images.githubusercontent.com/8545791/29270845-3c608450-8101-11e7-9179-4b2357dd3dd0.png)

![image](https://user-images.githubusercontent.com/8545791/29270848-40462fde-8101-11e7-8e97-8af6143a0540.png)

Error for edit:

```
Error!!!
Calling unknown method: App\Db\Command::all()

#0 modules/Events/models/Record.php(53): yii\base\Component->__call('all', Array)
#1 modules/Calendar/views/Edit.php(134): Events_Record_Model->getInvities()
#2 include/runtime/Controller.php(90): Calendar_Edit_View->Events(Object(App\Request), 'Events')
#3 modules/Calendar/views/Edit.php(33): Vtiger_Controller->invokeExposedMethod('Events', Object(App\Request), 'Events')
#4 include/main/WebUI.php(207): Calendar_Edit_View->process(Object(App\Request))
#5 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#6 public_html/index.php(11): require('/home/gitdevelo...')
#7 {main}
```

Error for open:

```
Error!!!
Calling unknown method: App\Db\Command::all()

#0 modules/Events/models/Record.php(53): yii\base\Component->__call('all', Array)
#1 modules/Calendar/views/Detail.php(136): Events_Record_Model->getInvities()
#2 modules/Calendar/views/Detail.php(148): Calendar_Detail_View->showModuleDetailView(Object(App\Request))
#3 modules/Vtiger/views/Detail.php(276): Calendar_Detail_View->showModuleBasicView(Object(App\Request))
#4 modules/Vtiger/views/Detail.php(216): Vtiger_Detail_View->showDetailViewByMode(Object(App\Request))
#5 include/main/WebUI.php(207): Vtiger_Detail_View->process(Object(App\Request))
#6 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#7 public_html/index.php(11): require('/home/gitdevelo...')
#8 {main}
```

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used:
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by konadrian** [comment]
Fixed in https://github.com/YetiForceCompany/YetiForceCRM/issues/4883
