### ISSUE TITLE
500 errors after update to 4.2

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#5171]
#### Issue

Some days ago I updated my system from 4.0 to 4.1 and after that to 4.2. Today I tried to test new update and found what sometimes I has 500 error after clicking save at record edit page or endless loading logo after field editing at summary page for different modules.

After page refresh changes are applied.

There are some error appears at console. I will post error message tomorrow.

How to solve this problem? What logs needed for error analysis?

#### Your Environment

* YetiForce Version used: 4.2.0

**Comment by bpabiszczak** [comment]
https://yetiforce.com/pl/component/zoo/item/apache-500-internal-server-error-3?highlight=WzUwMF0=

**Comment by vovpff** [comment]
Error at chrome console

For full record edit page:
```
POST http://domain/dev400/index.php 500 (Internal Server Error)`
```
For field edit:

```
csrf-magic.js:33 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
open @ csrf-magic.js:33
send @ jquery.js?s=1504958135:9050
ajax @ jquery.js?s=1504958135:8642
_request @ Connector.js?s=1504958134:111
request @ Connector.js?s=1504958134:35
SaveResult.checkData @ SaveResult.min.js?s=1504958133:2
i @ Detail.min.js?s=1505199506:1
handleObj.handler @ jquery.ba-outside-events.js?s=1504958135:207
dispatch @ jquery.js?s=1504958135:4723
elemData.handle @ jquery.js?s=1504958135:4535
trigger @ jquery.js?s=1504958135:7793
jQuery.event.trigger @ jquery-migrate.js?s=1504958135:493
triggerHandler @ jquery.js?s=1504958135:7867
(anonymous) @ jquery.ba-outside-events.js?s=1504958135:228
each @ jquery.js?s=1504958135:351
each @ jquery.js?s=1504958135:144
handle_event @ jquery.ba-outside-events.js?s=1504958135:216
dispatch @ jquery.js?s=1504958135:4723
elemData.handle @ jquery.js?s=1504958135:4535
csrf-magic.js:52 POST http://domain/dev400/index.php 500 (Internal Server Error)
send @ csrf-magic.js:52
send @ jquery.js?s=1504958135:9161
ajax @ jquery.js?s=1504958135:8642
_request @ Connector.js?s=1504958134:111
request @ Connector.js?s=1504958134:35
saveFieldValues @ Detail.min.js?s=1505199506:1
i @ Detail.min.js?s=1505199506:1
handleObj.handler @ jquery.ba-outside-events.js?s=1504958135:207
dispatch @ jquery.js?s=1504958135:4723
elemData.handle @ jquery.js?s=1504958135:4535
trigger @ jquery.js?s=1504958135:7793
jQuery.event.trigger @ jquery-migrate.js?s=1504958135:493
triggerHandler @ jquery.js?s=1504958135:7867
(anonymous) @ jquery.ba-outside-events.js?s=1504958135:228
each @ jquery.js?s=1504958135:351
each @ jquery.js?s=1504958135:144
handle_event @ jquery.ba-outside-events.js?s=1504958135:216
dispatch @ jquery.js?s=1504958135:4723
elemData.handle @ jquery.js?s=1504958135:4535
app.js?s=1505199506:1538 Internal Server Error
errorLog @ app.js?s=1505199506:1538
params.error @ Connector.js?s=1504958134:108
fire @ jquery.js?s=1504958135:3173
fireWith @ jquery.js?s=1504958135:3303
done @ jquery.js?s=1504958135:8745
(anonymous) @ jquery.js?s=1504958135:9109
send @ csrf-magic.js:52
send @ jquery.js?s=1504958135:9161
ajax @ jquery.js?s=1504958135:8642
_request @ Connector.js?s=1504958134:111
request @ Connector.js?s=1504958134:35
saveFieldValues @ Detail.min.js?s=1505199506:1
i @ Detail.min.js?s=1505199506:1
handleObj.handler @ jquery.ba-outside-events.js?s=1504958135:207
dispatch @ jquery.js?s=1504958135:4723
elemData.handle @ jquery.js?s=1504958135:4535
trigger @ jquery.js?s=1504958135:7793
jQuery.event.trigger @ jquery-migrate.js?s=1504958135:493
triggerHandler @ jquery.js?s=1504958135:7867
(anonymous) @ jquery.ba-outside-events.js?s=1504958135:228
each @ jquery.js?s=1504958135:351
each @ jquery.js?s=1504958135:144
handle_event @ jquery.ba-outside-events.js?s=1504958135:216
dispatch @ jquery.js?s=1504958135:4723
elemData.handle @ jquery.js?s=1504958135:4535
app.js?s=1505199506:1544 Internal Server Error
errorLog @ app.js?s=1505199506:1544
params.error @ Connector.js?s=1504958134:108
fire @ jquery.js?s=1504958135:3173
fireWith @ jquery.js?s=1504958135:3303
done @ jquery.js?s=1504958135:8745
(anonymous) @ jquery.js?s=1504958135:9109
send @ csrf-magic.js:52
send @ jquery.js?s=1504958135:9161
ajax @ jquery.js?s=1504958135:8642
_request @ Connector.js?s=1504958134:111
request @ Connector.js?s=1504958134:35
saveFieldValues @ Detail.min.js?s=1505199506:1
i @ Detail.min.js?s=1505199506:1
handleObj.handler @ jquery.ba-outside-events.js?s=1504958135:207
dispatch @ jquery.js?s=1504958135:4723
elemData.handle @ jquery.js?s=1504958135:4535
trigger @ jquery.js?s=1504958135:7793
jQuery.event.trigger @ jquery-migrate.js?s=1504958135:493
triggerHandler @ jquery.js?s=1504958135:7867
(anonymous) @ jquery.ba-outside-events.js?s=1504958135:228
each @ jquery.js?s=1504958135:351
each @ jquery.js?s=1504958135:144
handle_event @ jquery.ba-outside-events.js?s=1504958135:216
dispatch @ jquery.js?s=1504958135:4723
elemData.handle @ jquery.js?s=1504958135:4535
```
Apache access log:

```
192.168.1.1 - - [13/Sep/2017:12:15:11 +0300] "GET /dev400/index.php?module=IGDN&view=Detail&record=2227 HTTP/1.1" 200 140447 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:12 +0300] "GET /dev400/public_html/libraries/bootstrap3/css/bootstrap.css.map HTTP/1.1" 404 343 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:12 +0300] "GET /dev400/public_html/libraries/jquery/datepicker/css/bootstrap-datepicker3.css.map HTTP/1.1" 404 362 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:12 +0300] "GET /dev400/index.php?module=IGDN&view=Detail&record=2227&mode=showRecentComments&page=1&limit=5 HTTP/1.1" 200 3096 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:12 +0300] "GET /dev400/index.php?module=IGDN&view=Detail&record=2227&mode=showRecentActivities&page=1&limit=5&skipHeader=true HTTP/1.1" 200 8736 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:12 +0300] "POST /dev400/index.php HTTP/1.1" 200 56 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:12 +0300] "POST /dev400/index.php HTTP/1.1" 200 1448 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:12 +0300] "POST /dev400/index.php HTTP/1.1" 200 6492 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:16 +0300] "POST /dev400/index.php HTTP/1.1" 200 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:19 +0300] "POST /dev400/index.php HTTP/1.1" 200 72 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:19 +0300] "POST /dev400/index.php HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:20 +0300] "POST /dev400/index.php HTTP/1.1" 200 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
192.168.1.1 - - [13/Sep/2017:12:15:24 +0300] "POST /dev400/index.php HTTP/1.1" 200 2 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36"
```

**Comment by paula-w** [comment]
These are not error logs, we need PHP error logs because we can't really help you without them. 
Read this article: https://yetiforce.com/en/knowledge-base/documentation/developer-documentation/item/debugging

**Comment by vovpff** [comment]
@paula-w 

PHPerror.log

```
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Notice:  Undefined index: HTTP_USER_AGENT in D:\wamp\www\dev400\vendor\yetiforce\RequestUtil.php on line 50
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Notice:  Undefined index: SERVER_PROTOCOL in D:\wamp\www\dev400\vendor\yetiforce\RequestUtil.php on line 105
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Notice:  Undefined index: SERVER_PORT in D:\wamp\www\dev400\vendor\yetiforce\RequestUtil.php on line 107
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Notice:  Undefined index: SERVER_NAME in D:\wamp\www\dev400\vendor\yetiforce\RequestUtil.php on line 110
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Notice:  Undefined index: REQUEST_URI in D:\wamp\www\dev400\vendor\yetiforce\RequestUtil.php on line 111
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Notice:  Undefined index: REQUEST_URI in D:\wamp\www\dev400\vendor\yetiforce\RequestUtil.php on line 112
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Warning:  session_start(): Cannot send session cookie - headers already sent by (output started at D:\wamp\www\dev400\vendor\yetiforce\RequestUtil.php:50) in D:\wamp\www\dev400\vendor\yetiforce\Session.php on line 31
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Warning:  session_start(): Cannot send session cache limiter - headers already sent (output started at D:\wamp\www\dev400\vendor\yetiforce\RequestUtil.php:50) in D:\wamp\www\dev400\vendor\yetiforce\Session.php on line 31
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Notice:  Undefined index: authenticated_user_id in D:\wamp\www\dev400\vendor\yetiforce\Session\Base.php on line 50
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Notice:  Undefined index: app_unique_key in D:\wamp\www\dev400\vendor\yetiforce\Session\Base.php on line 50
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Notice:  Undefined property: OSSMailScanner::$column_fields in D:\wamp\www\dev400\modules\Vtiger\models\Record.php on line 486
[13-Sep-2017 15:01:28 Europe/Moscow] PHP Notice:  Undefined property: OSSMail::$column_fields in D:\wamp\www\dev400\modules\Vtiger\models\Record.php on line 486
```

**Comment by paula-w** [comment]
Your server configuration is wrong, you have to change it. You can check the proper configuration here: https://gitdeveloper.yetiforce.com/index.php?parent=Settings&module=ConfReport&view=Index&block=14&fieldid=65

**Comment by vovpff** [comment]
@paula-w 

my sever config

![image](https://user-images.githubusercontent.com/8545791/30383433-558dbcca-98aa-11e7-99cc-3271ba08f2b1.png)

![image](https://user-images.githubusercontent.com/8545791/30383449-62ac80bc-98aa-11e7-9cc8-d4bd102e239b.png)

**Comment by mariuszkrzaczkowski** [comment]
You have two php.ini configuration files to check if they are identical.
Often php.ini from cron is different and this will not show configuration verification
![30383433-558dbcca-98aa-11e7-99cc-3271ba08f2b1](https://user-images.githubusercontent.com/10198654/30396748-f046a518-98ca-11e7-9b62-b1f3fd095148.png)

**Comment by vovpff** [comment]
@mariuszkrzaczkowski I checked php.ini for CRON and made them identical to Apache php.ini
There are no difference. 500 error not disappears.

**Comment by mariuszkrzaczkowski** [comment]
If you do not see errors in the logs it requires a developer analysis.

**Comment by vovpff** [comment]
@mariuszkrzaczkowski how it is possible?

**Comment by vovpff** [comment]
@mariuszkrzaczkowski Hello one more time. I'm not stopped at this point.
Yesterday I established new server based on Ubuntu 16.04.
Migration from WAMP to LAMP was successful without any errors.
This is v4.0 was established. After that I made step by step update 4.0 to 4.1 (upd pack v6) and v 4.1 to 4.2 (upd pack v1). At first sight all works well but when I try to change subject of IGDN from summary or full edit page I has endless loading or blank page (maybe this is 500 error).
I checked log from /cache/logs/phperrors.log and found this stuff.

```
[26-Sep-2017 23:22:36 Europe/Moscow] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App\TextParser::getDisplayValueByField() must be an instance of Vtiger_Field_Model, string given, called in /var/www/html/my40/vendor/yetiforce/TextParser.php on line 413 and defined in /var/www/html/my40/vendor/yetiforce/TextParser.php:633
Stack trace:
#0 /var/www/html/my40/vendor/yetiforce/TextParser.php(413): App\TextParser->getDisplayValueByField('Gaiser T8', Object(IGDN_Field_Model))
#1 /var/www/html/my40/vendor/yetiforce/TextParser.php(243): App\TextParser->record('ChangesListChan...')
#2 [internal function]: App\TextParser->App\{closure}(Array)
#3 /var/www/html/my40/vendor/yetiforce/TextParser.php(246): preg_replace_callback('/\\$\\((\\w+) : ([...', Object(Closure), '<meta charset="...')
#4 /var/www/html/my40/modules/com_vtiger_workflow/tasks/VTEmailTask.php(60): App\TextParser->parse()
#5 /var/www/html/my40/modules/com_vtiger_workflow/VTWorkflowManager.php(526): VTEmailTask->doTask(Object(IGDN_Record_Model))
#6 /var/www/html/my40/modules/Vtiger/handlers/Workflo in /var/www/html/my40/vendor/yetiforce/TextParser.php on line 633
[26-Sep-2017 23:22:59 Europe/Moscow] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App\TextParser::getDisplayValueByField() must be an instance of Vtiger_Field_Model, string given, called in /var/www/html/my40/vendor/yetiforce/TextParser.php on line 413 and defined in /var/www/html/my40/vendor/yetiforce/TextParser.php:633
Stack trace:
#0 /var/www/html/my40/vendor/yetiforce/TextParser.php(413): App\TextParser->getDisplayValueByField('Gaiser T8 8888', Object(IGDN_Field_Model))
#1 /var/www/html/my40/vendor/yetiforce/TextParser.php(243): App\TextParser->record('ChangesListChan...')
#2 [internal function]: App\TextParser->App\{closure}(Array)
#3 /var/www/html/my40/vendor/yetiforce/TextParser.php(246): preg_replace_callback('/\\$\\((\\w+) : ([...', Object(Closure), '<meta charset="...')
#4 /var/www/html/my40/modules/com_vtiger_workflow/tasks/VTEmailTask.php(60): App\TextParser->parse()
#5 /var/www/html/my40/modules/com_vtiger_workflow/VTWorkflowManager.php(526): VTEmailTask->doTask(Object(IGDN_Record_Model))
#6 /var/www/html/my40/modules/Vtiger/handlers/Wo in /var/www/html/my40/vendor/yetiforce/TextParser.php on line 633
[26-Sep-2017 23:29:31 Europe/Moscow] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to App\TextParser::getDisplayValueByField() must be an instance of Vtiger_Field_Model, string given, called in /var/www/html/my40/vendor/yetiforce/TextParser.php on line 413 and defined in /var/www/html/my40/vendor/yetiforce/TextParser.php:633
Stack trace:
#0 /var/www/html/my40/vendor/yetiforce/TextParser.php(413): App\TextParser->getDisplayValueByField('TPT HB05 \xD0\x9C\xD0\x9D\xD0\x98...', Object(IGDN_Field_Model))
#1 /var/www/html/my40/vendor/yetiforce/TextParser.php(243): App\TextParser->record('ChangesListChan...')
#2 [internal function]: App\TextParser->App\{closure}(Array)
#3 /var/www/html/my40/vendor/yetiforce/TextParser.php(246): preg_replace_callback('/\\$\\((\\w+) : ([...', Object(Closure), '<meta charset="...')
#4 /var/www/html/my40/modules/com_vtiger_workflow/tasks/VTEmailTask.php(60): App\TextParser->parse()
#5 /var/www/html/my40/modules/com_vtiger_workflow/VTWorkflowManager.php(526): VTEmailTask->doTask(Object(IGDN_Record_Model))
#6 /var/www/html/my40/modu in /var/www/html/my40/vendor/yetiforce/TextParser.php on line 633
```

There are imaged 3 attempts by next order: editing field in summary view page, editing field at full record edit page, editing field in summary view page

P.S. I m not sure for 100% but I noticed what error appears for Logistics modules. I can check it one more time this evening.

**Comment by paula-w** [comment]
It's a different error, please open a new issue so we can investigate it separately, and let us know if it also occurs in the developer version.
