### ISSUE TITLE
Selecting module in settings->mappings: ERR_NOT_ALLOWED_VALUE

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5438]
#### Issue

Selecting a module in settings -> mapping will load forever. Reason is a purifier message in logs.

#### Actual Behavior

https://gitdeveloper.yetiforce.com/index.php?module=MappedFields&parent=Settings&page=1&view=List&sourceModule=4

~~~
#0 vendor/yetiforce/Request.php(133): App\Purifier::purifyByType('4', 1)
#1 modules/Settings/Vtiger/views/List.php(91): App\Request->getByType('sourceModule', 1)
#2 modules/Settings/Vtiger/views/List.php(28): Settings_Vtiger_List_View->initializeListViewContents(Object(App\Request), Object(Vtiger_Viewer))
#3 modules/Settings/MappedFields/views/List.php(18): Settings_Vtiger_List_View->preProcess(Object(App\Request), true)
#4 include/main/WebUI.php(258): Settings_MappedFields_List_View->preProcess(Object(App\Request))
#5 include/main/WebUI.php(189): Vtiger_WebUI->triggerPreProcess(Object(Settings_MappedFields_List_View), Object(App\Request))
#6 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#7 public_html/index.php(11): require('/home/gitdevelo...')
#8 {main}
~~~

e.g. for me in logs it is:
~~~
[error][BadRequest] - purifyByType: 13 
[error] - ERR_NOT_ALLOWED_VALUE => vendor/yetiforce/Purifier.php:313 
~~~

**Comment by migoi** [comment]
same (purifier check) for url:
https://gitdeveloper.yetiforce.com/index.php?module=Vendors&src_module=HelpDesk&src_field=parent_id&src_record=&view=Popup&triggerEventName=postSelection9069
