### ISSUE TITLE
OSSPassword: cannot add new record

### ISSUE THREAD

**Issue by migoi** [YetiForceCompany/YetiForceCRM#5456]
#### Issue

Cannot add a new record into OSSPassword module.
Because: modules/OSSPasswords/actions/Save.php
~~~php
...
	public function process(\App\Request $request)
	{
		$recordModel = $this->saveRecord($request);
...
	public function saveRecord(\App\Request $request)
	{
		$recordId = $request->getInteger('record');
...
~~~
$request->getInteger('record') will fail, since record is empty (new record)

#### Actual Behavior

fill in https://gitdeveloper.yetiforce.com/index.php?module=OSSPasswords&view=Edit and click save:
~~~
Incorrect request
Incorrect value detected, please contact your administrator

Home page

#0 modules/OSSPasswords/actions/Save.php(35): App\Request->getInteger('record')
#1 modules/OSSPasswords/actions/Save.php(14): OSSPasswords_Save_Action->saveRecord(Object(App\Request))
#2 include/main/WebUI.php(190): OSSPasswords_Save_Action->process(Object(App\Request))
#3 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#4 public_html/index.php(11): require('/home/gitdevelo...')
#5 {main}
#0 [trace] Entering getColumnFields(Users) method ...
#1 [trace] Exiting getColumnFields method ...
#2 [trace] Entering getColumnFields(OSSPasswords) method ...
#3 [trace] Exiting getColumnFields method ...
#4 [error] ERR_NOT_ALLOWED_VALUE||record|| => vendor/yetiforce/Request.php:170
~~~

**Comment by migoi** [comment]
i guess it should be wrapped with
~~~php
if (!$request->isEmpty('record', true)) {
~~~
?
