### ISSUE TITLE
[BUG][Users][4.2.514] "Incorrect value detected" in Export

### ISSUE THREAD

**Issue by WalterLuis** [YetiForceCompany/YetiForceCRM#5520]
#### Actual Behavior

	#0 vendor/yetiforce/Request.php(136): App\Purifier::purifyByType('', 2)
	#1 modules/Vtiger/models/Export.php(130): App\Request->getByType('viewname', 2)
	#2 modules/Vtiger/models/Export.php(55): Vtiger_Export_Model->getExportQuery(Object(App\Request))
	#3 modules/Vtiger/actions/ExportData.php(42): Vtiger_Export_Model->exportData(Object(App\Request))
	#4 include/main/WebUI.php(190): Vtiger_ExportData_Action->process(Object(App\Request))
	#5 index.php(25): Vtiger_WebUI->process(Object(App\Request))
	#6 public_html/index.php(11): require('/home/gitdevelo...')
	#7 {main}

	#0 [trace] Entering getColumnFields(Users) method ...
	#1 [trace] Exiting getColumnFields method ...
	#2 [error] purifyByType:  || BadRequest
	#3 [error] ERR_NOT_ALLOWED_VALUE|| => vendor/yetiforce/Purifier.php:326

#### How to trigger the error

1.
![2017-11-16_20-03-11](https://user-images.githubusercontent.com/18419851/32913153-661f1f66-cb09-11e7-9242-cd92fa7a9ce1.gif)

2.
3.

#### Your Environment

* YetiForce Version used: 4.2.514
* Browser name and version: Chrome 62.0 x64
* Environment name and version: gitdeveloper.yetiforce.com
* Operating System and version: gitdeveloper.yetiforce.com

**Comment by WalterLuis** [comment]
#5523 duplicated
