### ISSUE TITLE
Import Isuues 

### ISSUE THREAD

**Issue by aylanet2** [YetiForceCompany/YetiForceCRM#5597]
Facing issues with import funtionality once again on new install of 4.2 on 2 servers
Last attempt try both PHP 5.6 and 7
Latest php error log file is here
Any help will be gratly apreciated.

Please note i have implemented both fixes v1 and v2 found elsewhere without success.
Import display blank screen

====================================
[30-Nov-2017 09:13:01 America/New_York] PHP Warning:  require_once(include/Webservices/VtigerModuleOperation.php): failed to open stream: No such file or directory in /home/sportteam/public_html/crm/include/Webservices/Utils.php on line 384
[30-Nov-2017 09:13:01 America/New_York] PHP Fatal error:  require_once(): Failed opening required 'include/Webservices/VtigerModuleOperation.php' (include_path='.:/opt/cpanel/ea-php56/root/usr/share/pear') in /home/sportteam/public_html/crm/include/Webservices/Utils.php on line 384
[30-Nov-2017 09:20:07 America/New_York] PHP Fatal error:  Call to undefined method App\Layout::getTemplatePath() in /home/sportteam/public_html/crm/cache/templates_c/basic/27558b5ef3d4bc1b994030905074d6108c6a75b2_0.file.ImportAdvanced.tpl.php on line 26
[30-Nov-2017 09:22:09 America/New_York] PHP Fatal error:  Call to undefined method App\Layout::getTemplatePath() in /home/sportteam/public_html/crm/cache/templates_c/basic/27558b5ef3d4bc1b994030905074d6108c6a75b2_0.file.ImportAdvanced.tpl.php on line 26
[30-Nov-2017 09:30:41 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined method App\Layout::getTemplatePath() in /home/sportteam/public_html/crm/cache/templates_c/basic/27558b5ef3d4bc1b994030905074d6108c6a75b2_0.file.ImportAdvanced.tpl.php:26
Stack trace:
#0 /home/sportteam/public_html/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): content_5a2013973b38d4_06494548(Object(Smarty_Internal_Template))
#1 /home/sportteam/public_html/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(172): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /home/sportteam/public_html/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(206): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /home/sportteam/public_html/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(216): Smarty_Internal_Template->render(false, 1)
#4 /home/sportteam/public_html/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php( in /home/sportteam/public_html/crm/cache/templates_c/basic/27558b5ef3d4bc1b994030905074d6108c6a75b2_0.file.ImportAdvanced.tpl.php on line 26
[30-Nov-2017 09:36:55 America/New_York] PHP Fatal error:  Uncaught Error: Call to undefined method App\Layout::getTemplatePath() in /home/sportteam/public_html/crm/cache/templates_c/basic/27558b5ef3d4bc1b994030905074d6108c6a75b2_0.file.ImportAdvanced.tpl.php:26
Stack trace:
#0 /home/sportteam/public_html/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): content_5a2013973b38d4_06494548(Object(Smarty_Internal_Template))
#1 /home/sportteam/public_html/crm/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(172): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /home/sportteam/public_html/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(206): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /home/sportteam/public_html/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(216): Smarty_Internal_Template->render(false, 1)
#4 /home/sportteam/public_html/crm/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php( in /home/sportteam/public_html/crm/cache/templates_c/basic/27558b5ef3d4bc1b994030905074d6108c6a75b2_0.file.ImportAdvanced.tpl.php on line 26

**Comment by mariuszkrzaczkowski** [comment]
Duplicated #4827
