### ISSUE TITLE
RC2 4.2 - 4.3 Filter colours do not display

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#5608]
In the developer version the filters can be given a colour which display across the top of the screen (see image1). 
![image1](https://user-images.githubusercontent.com/10598886/33492381-ccae4afc-d6b4-11e7-804b-c9fbcfa81006.png)

After updating I opened a number of existing filters and gave them a colour but I do not see the changes on the front end. I also went to Search & Filters - FIlters Configuration and added the colours there to different filters, still no effect. 

Is there a setting that needs to be switched on somewhere before these filters will display?

Kind regards

**Comment by migoi** [comment]
works for me. Also working on https://gitdeveloper.yetiforce.com/

Open your browsers console (F12) and have a look for warnings etc.
Also: is something in the logs that the record could not be saved?

**Comment by PercyP** [comment]
Hi @migoi 
When I save the filter with the colour change it doesn't produce an error in Console. There are some errors in phpError.log:

`[01-Dec-2017 15:31:28 Europe/London] PHP Warning:  Declaration of Vtiger_Jsign_UIType::getDisplayValue($value) should be compatible with Vtiger_Base_UIType::getDisplayValue($value, $record = false, $recordModel = false, $rawText = false) in /home/mysite/public_html/crm3/modules/Vtiger/uitypes/Jsign.php on line 0
[01-Dec-2017 15:31:33 Europe/London] PHP Warning:  Declaration of Vtiger_Jsign_UIType::getDisplayValue($value) should be compatible with Vtiger_Base_UIType::getDisplayValue($value, $record = false, $recordModel = false, $rawText = false) in /home/mysite/public_html/crm3/modules/Vtiger/uitypes/Jsign.php on line 0
[01-Dec-2017 15:31:33 Europe/London] PHP Fatal error:  Uncaught Error: Call to undefined method Vtiger_Record_Model::getJsignDetails() in /home/mysite/public_html/crm3/cache/templates_c/basic/5f666341c2fdbc8aa1eb1c93516aa3c7a00fa031_0.file.JsignDetailView.tpl.php:27
Stack trace:
#0 /home/mysite/public_html/crm3/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(128): content_5a2175c8656f36_78043845(Object(Smarty_Internal_Template))
#1 /home/mysite/public_html/crm3/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(172): Smarty_Template_Resource_Base->getRenderedTemplateCode(Object(Smarty_Internal_Template))
#2 /home/mysite/public_html/crm3/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(206): Smarty_Template_Compiled->render(Object(Smarty_Internal_Template))
#3 /home/mysite/public_html/crm3/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(372): Smarty_Internal_Template->render()
#4 /home/mysite/public_html/crm3/cache/templates_c/basic/66edc158f2597d2884e2b30032508834f02e in /home/mysite/public_html/crm3/cache/templates_c/basic/5f666341c2fdbc8aa1eb1c93516aa3c7a00fa031_0.file.JsignDetailView.tpl.php on line 27
[01-Dec-2017 15:32:29 Europe/London] PHP Warning:  Declaration of Vtiger_Jsign_UIType::getDisplayValue($value) should be compatible with Vtiger_Base_UIType::getDisplayValue($value, $record = false, $recordModel = false, $rawText = false) in /home/mysite/public_html/crm3/modules/Vtiger/uitypes/Jsign.php on line 0
[01-Dec-2017 15:39:12 Europe/London] PHP Warning:  Invalid argument supplied for foreach() in /home/mysite/public_html/crm3/modules/Vtiger/actions/Inventory.php on line 152`

The record does save, as when I go back in the colour is set, it just doesn't show up

**Comment by migoi** [comment]
have you marked it as "favourite"?

**Comment by PercyP** [comment]
@migoi 

thank you - that was it! I just clicked on the Favourite icon top right of the page and it works. 

Sorry, without instructions I wouldn't have figured that out.

Once again thanks
