### ISSUE TITLE
4.4 RC1 - cannot download the Roundcube etc. files

### ISSUE THREAD

**Issue by PercyP** [YetiForceCompany/YetiForceCRM#6721]
Hi,

I have installed the latest version for testing. Tried to download the 3 libraries for Roundcube etc via module installation. When I click on download the screen flickers but nothing else happens.
This is what shows in my error log:

`[30-Apr-2018 11:39:06 UTC] PHP Fatal error:  Uncaught Error: Class 'yii\base\NotSupportedException' not found in /home/mysitem/public_html/new/vendor/yetiforce/yii2/db/Connection.php:827
Stack trace:
#0 /home/mysitem/public_html/new/vendor/yetiforce/yii2/db/Connection.php(836): yii\db\Connection->getSchema()
#1 /home/mysitem/public_html/new/app/Db/Query.php(27): yii\db\Connection->getQueryBuilder()
#2 /home/mysitem/public_html/new/app/Db/Query.php(97): App\Db\Query->createCommand(Object(App\Db))
#3 /home/mysitem/public_html/new/app/Company.php(36): App\Db\Query->one()
#4 /home/mysitem/public_html/new/app/Controller/View.php(162): App\Company::getInstanceById()
#5 /home/mysitem/public_html/new/modules/Users/views/Login.php(35): App\Controller\View->preProcess(Object(App\Request), false)
#6 /home/mysitem/public_html/new/include/main/WebUI.php(261): Users_Login_View->preProcess(Object(App\Request))
#7 /home/mysitem/public_html/new/include/main/WebUI.php(183): Vtiger_WebUI->triggerPreProcess(Object(Users_Login_View), Object(App\Re in /home/mysitem/public_html/new/vendor/yetiforce/yii2/db/Connection.php on line 827
[30-Apr-2018 11:39:32 UTC] PHP Fatal error:  Uncaught Error: Class 'yii\base\NotSupportedException' not found in /home/mysitem/public_html/new/vendor/yetiforce/yii2/db/Connection.php:827
Stack trace:
#0 /home/mysitem/public_html/new/vendor/yetiforce/yii2/db/Connection.php(836): yii\db\Connection->getSchema()
#1 /home/mysitem/public_html/new/app/Db/Query.php(27): yii\db\Connection->getQueryBuilder()
#2 /home/mysitem/public_html/new/app/Db/Query.php(97): App\Db\Query->createCommand(Object(App\Db))
#3 /home/mysitem/public_html/new/app/Company.php(36): App\Db\Query->one()
#4 /home/mysitem/public_html/new/app/Controller/View.php(162): App\Company::getInstanceById()
#5 /home/mysitem/public_html/new/modules/Users/views/Login.php(35): App\Controller\View->preProcess(Object(App\Request), false)
#6 /home/mysitem/public_html/new/include/main/WebUI.php(261): Users_Login_View->preProcess(Object(App\Request))
#7 /home/mysitem/public_html/new/include/main/WebUI.php(183): Vtiger_WebUI->triggerPreProcess(Object(Users_Login_View), Object(App\Re in /home/mysitem/public_html/new/vendor/yetiforce/yii2/db/Connection.php on line 827
[30-Apr-2018 11:40:40 UTC] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 11:40:40 UTC] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 11:41:55 UTC] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 11:41:55 UTC] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 12:56:42 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 12:56:42 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 12:57:05 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:57:05 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:57:15 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:57:15 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:57:21 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:57:21 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:57:26 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:57:26 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:57:55 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:57:55 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:58:00 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:58:00 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 12:59:43 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 12:59:43 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 13:00:32 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 13:00:32 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 13:01:07 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 13:01:07 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 13:01:10 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 13:01:10 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ModuleManager/models/Library.php on line 126
[30-Apr-2018 13:01:25 Europe/London] PHP Warning:  get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268
[30-Apr-2018 13:01:25 Europe/London] PHP Warning:  get_headers(): This function may only be used against URLs in /home/mysitem/public_html/new/modules/Settings/ConfReport/models/Module.php on line 268`

**Comment by cristyxx** [comment]
I confirm the error. This happened to me.

**Comment by mariuszkrzaczkowski** [comment]
download the library now

**Comment by mariuszkrzaczkowski** [comment]
check the logs

**Comment by mariuszkrzaczkowski** [comment]
> [30-Apr-2018 13:01:25 Europe/London] PHP Warning: get_headers(): https:// wrapper is disabled in the server configuration by **allow_url_fopen=0** in

**Comment by PercyP** [comment]
@mariuszkrzaczkowski 

thank you - that was it, I had not enabled allow_url_fopen
