### ISSUE TITLE
[Developer 4.3.454] Workflow Task - Create Event [bug?]

### ISSUE THREAD

**Issue by ldgbc** [YetiForceCompany/YetiForceCRM#7359]
#### Issue
Want to provide a tutorial for https://github.com/YetiForceCompany/YetiForceCRM/issues/5011 but found this issue. Not sure if it just me.

Basically I can't create a Workflow Event Task. Clicking Save don't do anything.

#### Actual Behavior
Click Save doesn't do anything. Console log below.

#### Expected Behavior
Save button work and Event Task is created.

#### How to trigger the error
1. https://gitdeveloper.yetiforce.com/index.php?module=Workflows&parent=Settings&view=Edit
2. Description: birthday
3. Manual trigger by the user
4. Next > Next (step 3 Add Task)
5. Add To Do
6. Create Event
7. Fill in whatever you want and click save. Error below.

![issue - create event workflow](https://user-images.githubusercontent.com/1805303/43355755-811b935c-9251-11e8-9a9b-49f92943f8a9.jpg)

`{"success":false,"error":{"code":23000,"message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '160' for key 'PRIMARY'\nThe SQL being executed was: INSERT INTO `com_vtiger_workflowtasks` (`task_id`, `workflow_id`, `summary`, `task`) VALUES (160, 77, 'test', 'O:17:\\\"VTCreateEventTask\\\":22:{s:18:\\\"executeImmediately\\\";b:1;s:8:\\\"contents\\\";N;s:10:\\\"workflowId\\\";i:77;s:7:\\\"summary\\\";s:4:\\\"test\\\";s:6:\\\"active\\\";b:1;s:7:\\\"trigger\\\";N;s:9:\\\"eventType\\\";s:7:\\\"Meeting\\\";s:9:\\\"eventName\\\";s:4:\\\"test\\\";s:11:\\\"description\\\";s:0:\\\"\\\";s:16:\\\"sendNotification\\\";s:0:\\\"\\\";s:9:\\\"startTime\\\";s:6:\\\"12:28 \\\";s:9:\\\"startDays\\\";s:0:\\\"\\\";s:14:\\\"startDirection\\\";s:5:\\\"after\\\";s:14:\\\"startDatefield\\\";s:8:\\\"birthday\\\";s:7:\\\"endTime\\\";s:6:\\\"12:28 \\\";s:7:\\\"endDays\\\";s:0:\\\"\\\";s:12:\\\"endDirection\\\";s:5:\\\"after\\\";s:12:\\\"endDatefield\\\";s:8:\\\"birthday\\\";s:6:\\\"status\\\";s:11:\\\"PLL_PLANNED\\\";s:8:\\\"priority\\\";s:0:\\\"\\\";s:16:\\\"assigned_user_id\\\";s:1:\\\"1\\\";s:2:\\\"id\\\";i:160;}')","trace":"#0 vendor\/yetiforce\/yii2\/db\/Command.php(1263): yii\\db\\Schema->convertException(Object(PDOException), 'INSERT INTO `co...')\n#1 vendor\/yetiforce\/yii2\/db\/Command.php(1075): yii\\db\\Command->internalExecute('INSERT INTO `co...')\n#2 modules\/com_vtiger_workflow\/VTTaskManager.php(45): yii\\db\\Command->execute()\n#3 modules\/Settings\/Workflows\/models\/TaskRecord.php(259): VTTaskManager->saveTask(Object(VTCreateEventTask))\n#4 modules\/Settings\/Workflows\/actions\/TaskAjax.php(155): Settings_Workflows_TaskRecord_Model->save()\n#5 [internal function]: Settings_Workflows_TaskAjax_Action->save(Object(App\\Request))\n#6 app\/Controller\/ExposeMethod.php(63): call_user_func_array(Array, Array)\n#7 app\/Controller\/ExposeMethod.php(76): Settings_Workflows_TaskAjax_Action->invokeExposedMethod('save', Object(App\\Request))\n#8 include\/main\/WebUI.php(183): Settings_Workflows_TaskAjax_Action->process(Object(App\\Request))\n#9 index.php(25): Vtiger_WebUI->process(Object(App\\Request))\n#10 public_html\/index.php(11): require('\/home\/gitdevelo...')\n#11 {main}"}}`

#### Your Environment

* YetiForce Version used: 4.3.454
* Browser name and version: Firefox 623
* Environment name and version: YF
* Operating System and version: YF

**Comment by ldgbc** [comment]
Off-topic and may need a new issue. The Selection windows look very bad, can't read/see anything properly. See screenshot.
