### ISSUE TITLE
[4.4.0] Advanced field - Date

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7475]
#### Issue

As litted in new features here #7447 there are added some advanced additional fields.

Date in this field does not match the type specified in user the settings:

![image](https://user-images.githubusercontent.com/8545791/43687081-25462640-98d8-11e8-87c7-56651fdcba99.png)

![image](https://user-images.githubusercontent.com/8545791/43687094-525dd89e-98d8-11e8-84e8-677e4551a54a.png)

After attempt to save record:

![image](https://user-images.githubusercontent.com/8545791/43687104-6c19dada-98d8-11e8-8699-167256f3ba29.png)

This field can't be used because not work proper.

**Comment by poradz** [comment]
https://github.com/YetiForceCompany/YetiForceCRM/pull/7508

After this fix I added advanced date field to calculation module, and there wasn't any error. Can you specify, where did you meet this error, if it still exist?

**Comment by vovpff** [comment]
@poradz what version i can test? on git dev 4.4.4 for quotes:
```
Incorrect request
Incorrect value detected, please contact your administrator


#0 app/Request.php(151): App\Purifier::purifyByType('08/07/2018', 'DateInUserForma...')
#1 modules/Vtiger/inventoryfields/Date.php(27): App\Request->getByType('date11', 'DateInUserForma...')
#2 modules/Vtiger/models/Record.php(1162): Vtiger_Date_InventoryField->getValueFromRequest(Array, Object(App\Request), 1)
#3 modules/Vtiger/models/Record.php(423): Vtiger_Record_Model->initInventoryData()
#4 modules/Vtiger/actions/Save.php(90): Vtiger_Record_Model->save()
#5 modules/Vtiger/actions/Save.php(63): Vtiger_Save_Action->saveRecord(Object(App\Request))
#6 include/main/WebUI.php(183): Vtiger_Save_Action->process(Object(App\Request))
#7 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#8 public_html/index.php(11): require('/home/gitdevelo...')
#9 {main}
#0 [trace] Entering isPermitted(SQuotes,DetailView,3466,) method ...
#1 [info] SELECT `crmid`, `setype`, `deleted`, `smcreatorid`, `smownerid`, `createdtime`, `private` FROM `vtiger_crmentity` WHERE `crmid`=3466 || yii\db\Command::query
#2 [info] Opening DB connection: mysql:host=localhost;dbname=gitdevelop_crm;port=3306 || yii\db\Connection::open
#3 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#4 [trace] Entering getColumnFields(SQuotes) method ...
#5 [trace] Exiting getColumnFields method ...
#6 [info] SELECT `u_yf_squotes`.`subject` AS `u_yf_squotessubject`, `u_yf_squotes`.`category` AS `u_yf_squotescategory`, `u_yf_squotes`.`salesprocessid` AS `u_yf_squotessalesprocessid`, `u_yf_squotes`.`scalculationsid` AS `u_yf_squotesscalculationsid`, `u_yf_squotes`.`squotes_status` AS `u_yf_squotessquotes_status`, `u_yf_squotes`.`accountid` AS `u_yf_squotesaccountid`, `vtiger_crmentity`.`smownerid` AS `vtiger_crmentityassigned_user_id`, `vtiger_crmentity`.`shownerid` AS `vtiger_crmentityshownerid`, `vtiger_crmentity`.`description` AS `vtiger_crmentitydescription`, `vtiger_crmentity`.`attention` AS `vtiger_crmentityattention`, `u_yf_squotes`.`response_time` AS `u_yf_squotesresponse_time`, `vtiger_crmentity`.`createdtime` AS `vtiger_crmentitycreatedtime`, `u_yf_squotes`.`squotes_no` AS `u_yf_squotessquotes_no`, `vtiger_crmentity`.`modifiedtime` AS `vtiger_crmentitymodifiedtime`, `vtiger_crmentity`.`closedtime` AS `vtiger_crmentityclosedtime`, `u_yf_squotes_address`.`addresslevel1a` AS `u_yf_squotes_addressaddresslevel1a`, `u_yf_squotes_address`.`addresslevel2a` AS `u_yf_squotes_addressaddresslevel2a`, `u_yf_squotes_address`.`addresslevel3a` AS `u_yf_squotes_addressaddresslevel3a`, `u_yf_squotes_address`.`addresslevel4a` AS `u_yf_squotes_addressaddresslevel4a`, `u_yf_squotes_address`.`addresslevel5a` AS `u_yf_squotes_addressaddresslevel5a`, `u_yf_squotes_address`.`addresslevel6a` AS `u_yf_squotes_addressaddresslevel6a`, `u_yf_squotes_address`.`addresslevel7a` AS `u_yf_squotes_addressaddresslevel7a`, `u_yf_squotes_address`.`addresslevel8a` AS `u_yf_squotes_addressaddresslevel8a`, `u_yf_squotes_address`.`buildingnumbera` AS `u_yf_squotes_addressbuildingnumbera`, `u_yf_squotes_address`.`localnumbera` AS `u_yf_squotes_addresslocalnumbera`, `u_yf_squotes_address`.`poboxa` AS `u_yf_squotes_addresspoboxa`, `u_yf_squotes`.`company` AS `u_yf_squotescompany`, `u_yf_squotes`.`sum_time` AS `u_yf_squotessum_time`, `vtiger_entity_stats`.`crmactivity` AS `vtiger_entity_statscrmactivity`, `u_yf_squotes`.`sum_total` AS `u_yf_squotessum_total`, `u_yf_squotes`.`sum_marginp` AS `u_yf_squotessum_marginp`, `u_yf_squotes`.`sum_margin` AS `u_yf_squotessum_margin`, `u_yf_squotes`.`sum_gross` AS `u_yf_squotessum_gross`, `u_yf_squotes`.`sum_discount` AS `u_yf_squotessum_discount`, `u_yf_squotes`.`valid_until` AS `u_yf_squotesvalid_until`, `vtiger_crmentity`.`private` AS `vtiger_crmentityprivate`, `vtiger_crmentity`.`deleted` FROM `vtiger_crmentity` LEFT JOIN `u_yf_squotes` ON vtiger_crmentity.crmid = u_yf_squotes.squotesid LEFT JOIN `u_yf_squotescf` ON vtiger_crmentity.crmid = u_yf_squotescf.squotesid LEFT JOIN `u_yf_squotes_address` ON vtiger_crmentity.crmid = u_yf_squotes_address.squotesaddressid LEFT JOIN `vtiger_entity_stats` ON vtiger_crmentity.crmid = vtiger_entity_stats.crmid WHERE (`vtiger_crmentity`.`crmid`=3466) AND (`vtiger_crmentity`.`setype`='SQuotes') LIMIT 1 || yii\db\Command::query
#7 [info] SELECT DISTINCT `userid` FROM `u_yf_crmentity_showners` WHERE `crmid`=3466 || yii\db\Command::query
#8 [trace] Entering isPermitted(SQuotes,EditView,3466,) method ...
#9 [trace] Exiting isPermitted method ... - SEC_USER_IS_ADMIN
#10 [trace] Entering App\Field::getFieldPermission: 89,subject
#11 [trace] Entering App\Field::getFieldsPermissions: 89
#12 [trace] Entering App\Field::getFieldPermission: 89,subject
#13 [trace] Entering App\Field::getFieldsPermissions: 89
#14 [trace] Entering App\Field::getFieldPermission: 89,salesprocessid
#15 [trace] Entering App\Field::getFieldsPermissions: 89
#16 [trace] Entering App\Field::getFieldPermission: 89,salesprocessid
#17 [trace] Entering App\Field::getFieldsPermissions: 89
#18 [trace] Entering App\Field::getFieldPermission: 89,scalculationsid
#19 [trace] Entering App\Field::getFieldsPermissions: 89
#20 [trace] Entering App\Field::getFieldPermission: 89,scalculationsid
#21 [trace] Entering App\Field::getFieldsPermissions: 89
#22 [trace] Entering App\Field::getFieldPermission: 89,accountid
#23 [trace] Entering App\Field::getFieldsPermissions: 89
#24 [trace] Entering App\Field::getFieldPermission: 89,accountid
#25 [trace] Entering App\Field::getFieldsPermissions: 89
#26 [trace] Entering App\Field::getFieldPermission: 89,category
#27 [trace] Entering App\Field::getFieldsPermissions: 89
#28 [trace] Entering App\Field::getFieldPermission: 89,category
#29 [trace] Entering App\Field::getFieldsPermissions: 89
#30 [trace] Entering App\Field::getFieldPermission: 89,squotes_status
#31 [trace] Entering App\Field::getFieldsPermissions: 89
#32 [trace] Entering App\Field::getFieldPermission: 89,squotes_status
#33 [trace] Entering App\Field::getFieldsPermissions: 89
#34 [trace] Entering App\Field::getFieldPermission: 89,assigned_user_id
#35 [trace] Entering App\Field::getFieldsPermissions: 89
#36 [trace] Entering App\Field::getFieldPermission: 89,assigned_user_id
#37 [trace] Entering App\Field::getFieldsPermissions: 89
#38 [trace] Entering App\Field::getFieldPermission: 89,shownerid
#39 [trace] Entering App\Field::getFieldsPermissions: 89
#40 [trace] Entering App\Field::getFieldPermission: 89,shownerid
#41 [trace] Entering App\Field::getFieldsPermissions: 89
#42 [trace] Entering App\Field::getFieldPermission: 89,company
#43 [trace] Entering App\Field::getFieldsPermissions: 89
#44 [trace] Entering App\Field::getFieldPermission: 89,company
#45 [trace] Entering App\Field::getFieldsPermissions: 89
#46 [trace] Entering App\Field::getFieldPermission: 89,valid_until
#47 [trace] Entering App\Field::getFieldsPermissions: 89
#48 [trace] Entering App\Field::getFieldPermission: 89,valid_until
#49 [trace] Entering App\Field::getFieldsPermissions: 89
#50 [trace] Start DateTimeField::convertToDBFormat s:10:"2018-09-05";
#51 [trace] End DateTimeField::convertToDBFormat
#52 [trace] Entering App\Field::getFieldPermission: 89,private
#53 [trace] Entering App\Field::getFieldsPermissions: 89
#54 [trace] Entering App\Field::getFieldPermission: 89,private
#55 [trace] Entering App\Field::getFieldsPermissions: 89
#56 [trace] Entering App\Field::getFieldPermission: 89,description
#57 [trace] Entering App\Field::getFieldsPermissions: 89
#58 [trace] Entering App\Field::getFieldPermission: 89,description
#59 [trace] Entering App\Field::getFieldsPermissions: 89
#60 [trace] Entering App\Field::getFieldPermission: 89,attention
#61 [trace] Entering App\Field::getFieldsPermissions: 89
#62 [trace] Entering App\Field::getFieldPermission: 89,attention
#63 [trace] Entering App\Field::getFieldsPermissions: 89
#64 [trace] Entering App\Field::getFieldPermission: 89,response_time
#65 [trace] Entering App\Field::getFieldsPermissions: 89
#66 [trace] Entering App\Field::getFieldPermission: 89,response_time
#67 [trace] Entering App\Field::getFieldsPermissions: 89
#68 [trace] Entering App\Field::getFieldPermission: 89,sum_time
#69 [trace] Entering App\Field::getFieldsPermissions: 89
#70 [trace] Entering App\Field::getFieldPermission: 89,sum_time
#71 [trace] Entering App\Field::getFieldsPermissions: 89
#72 [trace] Entering App\Field::getFieldPermission: 89,sum_total
#73 [trace] Entering App\Field::getFieldsPermissions: 89
#74 [trace] Entering App\Field::getFieldPermission: 89,sum_total
#75 [trace] Entering App\Field::getFieldsPermissions: 89
#76 [trace] Entering App\Field::getFieldPermission: 89,sum_marginp
#77 [trace] Entering App\Field::getFieldsPermissions: 89
#78 [trace] Entering App\Field::getFieldPermission: 89,sum_marginp
#79 [trace] Entering App\Field::getFieldsPermissions: 89
#80 [trace] Entering App\Field::getFieldPermission: 89,sum_margin
#81 [trace] Entering App\Field::getFieldsPermissions: 89
#82 [trace] Entering App\Field::getFieldPermission: 89,sum_margin
#83 [trace] Entering App\Field::getFieldsPermissions: 89
#84 [trace] Entering App\Field::getFieldPermission: 89,sum_gross
#85 [trace] Entering App\Field::getFieldsPermissions: 89
#86 [trace] Entering App\Field::getFieldPermission: 89,sum_gross
#87 [trace] Entering App\Field::getFieldsPermissions: 89
#88 [trace] Entering App\Field::getFieldPermission: 89,sum_discount
#89 [trace] Entering App\Field::getFieldsPermissions: 89
#90 [trace] Entering App\Field::getFieldPermission: 89,sum_discount
#91 [trace] Entering App\Field::getFieldsPermissions: 89
#92 [trace] Entering App\Field::getFieldPermission: 89,createdtime
#93 [trace] Entering App\Field::getFieldsPermissions: 89
#94 [trace] Entering App\Field::getFieldPermission: 89,createdtime
#95 [trace] Entering App\Field::getFieldsPermissions: 89
#96 [trace] Entering App\Field::getFieldPermission: 89,squotes_no
#97 [trace] Entering App\Field::getFieldsPermissions: 89
#98 [trace] Entering App\Field::getFieldPermission: 89,squotes_no
#99 [trace] Entering App\Field::getFieldsPermissions: 89
#100 [trace] Entering App\Field::getFieldPermission: 89,modifiedtime
#101 [trace] Entering App\Field::getFieldsPermissions: 89
#102 [trace] Entering App\Field::getFieldPermission: 89,modifiedtime
#103 [trace] Entering App\Field::getFieldsPermissions: 89
#104 [trace] Entering App\Field::getFieldPermission: 89,closedtime
#105 [trace] Entering App\Field::getFieldsPermissions: 89
#106 [trace] Entering App\Field::getFieldPermission: 89,closedtime
#107 [trace] Entering App\Field::getFieldsPermissions: 89
#108 [trace] Entering App\Field::getFieldPermission: 89,crmactivity
#109 [trace] Entering App\Field::getFieldsPermissions: 89
#110 [trace] Entering App\Field::getFieldPermission: 89,crmactivity
#111 [trace] Entering App\Field::getFieldsPermissions: 89
#112 [trace] Entering App\Field::getFieldPermission: 89,buildingnumbera
#113 [trace] Entering App\Field::getFieldsPermissions: 89
#114 [trace] Entering App\Field::getFieldPermission: 89,buildingnumbera
#115 [trace] Entering App\Field::getFieldsPermissions: 89
#116 [trace] Entering App\Field::getFieldPermission: 89,localnumbera
#117 [trace] Entering App\Field::getFieldsPermissions: 89
#118 [trace] Entering App\Field::getFieldPermission: 89,localnumbera
#119 [trace] Entering App\Field::getFieldsPermissions: 89
#120 [trace] Entering App\Field::getFieldPermission: 89,addresslevel8a
#121 [trace] Entering App\Field::getFieldsPermissions: 89
#122 [trace] Entering App\Field::getFieldPermission: 89,addresslevel8a
#123 [trace] Entering App\Field::getFieldsPermissions: 89
#124 [trace] Entering App\Field::getFieldPermission: 89,addresslevel7a
#125 [trace] Entering App\Field::getFieldsPermissions: 89
#126 [trace] Entering App\Field::getFieldPermission: 89,addresslevel7a
#127 [trace] Entering App\Field::getFieldsPermissions: 89
#128 [trace] Entering App\Field::getFieldPermission: 89,addresslevel6a
#129 [trace] Entering App\Field::getFieldsPermissions: 89
#130 [trace] Entering App\Field::getFieldPermission: 89,addresslevel6a
#131 [trace] Entering App\Field::getFieldsPermissions: 89
#132 [trace] Entering App\Field::getFieldPermission: 89,addresslevel5a
#133 [trace] Entering App\Field::getFieldsPermissions: 89
#134 [trace] Entering App\Field::getFieldPermission: 89,addresslevel5a
#135 [trace] Entering App\Field::getFieldsPermissions: 89
#136 [trace] Entering App\Field::getFieldPermission: 89,addresslevel4a
#137 [trace] Entering App\Field::getFieldsPermissions: 89
#138 [trace] Entering App\Field::getFieldPermission: 89,addresslevel4a
#139 [trace] Entering App\Field::getFieldsPermissions: 89
#140 [trace] Entering App\Field::getFieldPermission: 89,addresslevel3a
#141 [trace] Entering App\Field::getFieldsPermissions: 89
#142 [trace] Entering App\Field::getFieldPermission: 89,addresslevel3a
#143 [trace] Entering App\Field::getFieldsPermissions: 89
#144 [trace] Entering App\Field::getFieldPermission: 89,addresslevel2a
#145 [trace] Entering App\Field::getFieldsPermissions: 89
#146 [trace] Entering App\Field::getFieldPermission: 89,addresslevel2a
#147 [trace] Entering App\Field::getFieldsPermissions: 89
#148 [trace] Entering App\Field::getFieldPermission: 89,addresslevel1a
#149 [trace] Entering App\Field::getFieldsPermissions: 89
#150 [trace] Entering App\Field::getFieldPermission: 89,addresslevel1a
#151 [trace] Entering App\Field::getFieldsPermissions: 89
#152 [trace] Entering App\Field::getFieldPermission: 89,poboxa
#153 [trace] Entering App\Field::getFieldsPermissions: 89
#154 [trace] Entering App\Field::getFieldPermission: 89,poboxa
#155 [trace] Entering App\Field::getFieldsPermissions: 89
#156 [trace] Entering Vtiger_Record_Model::initInventoryData
#157 [info] SHOW TABLES || yii\db\Command::query
#158 [info] SELECT * FROM `u_yf_squotes_invfield` WHERE `presence`=0 ORDER BY `sequence` || yii\db\Command::query
#159 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#160 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#161 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#162 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#163 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#164 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#165 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#166 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#167 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#168 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#169 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#170 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#171 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#172 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#173 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#174 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#175 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#176 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#177 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#178 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#179 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#180 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#181 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#182 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#183 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#184 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#185 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#186 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#187 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#188 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#189 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#190 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#191 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#192 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#193 [trace] Entering Vtiger_InventoryField_Model::getInventoryFieldInstance| 
#194 [trace] Exiting Vtiger_InventoryField_Model::getInventoryFieldInstance
#195 [error] purifyByType: 08/07/2018 || IllegalValue
#196 [error] ERR_NOT_ALLOWED_VALUE||08/07/2018
App\Exceptions\IllegalValue: ERR_NOT_ALLOWED_VALUE||08/07/2018 in app/Purifier.php:366
Stack trace:
#0 app/Request.php(151): App\Purifier::purifyByType('08/07/2018', 'DateInUserForma...')
#1 modules/Vtiger/inventoryfields/Date.php(27): App\Request->getByType('date11', 'DateInUserForma...')
#2 modules/Vtiger/models/Record.php(1162): Vtiger_Date_InventoryField->getValueFromRequest(Array, Object(App\Request), 1)
#3 modules/Vtiger/models/Record.php(423): Vtiger_Record_Model->initInventoryData()
#4 modules/Vtiger/actions/Save.php(90): Vtiger_Record_Model->save()
#5 modules/Vtiger/actions/Save.php(63): Vtiger_Save_Action->saveRecord(Object(App\Request))
#6 include/main/WebUI.php(183): Vtiger_Save_Action->process(Object(App\Request))
#7 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#8 public_html/index.php(11): require('/home/gitdevelo...')
#9 {main}
```

For calculations I can't check because #7469

**Comment by vovpff** [comment]
@poradz on my local 4.4.0 the same situation after this fix.
