### ISSUE TITLE
PDF Template - SQL error

### ISSUE THREAD

**Issue by gerripeach** [YetiForceCompany/YetiForceCRM#7695]
#### Issue
When creating a pdf template a sql error is thrown.

#### Actual Behavior
sql error. Not able to create pdf template

#### Expected Behavior
no sql error.

#### How to trigger the error
1. Settings -> System Tools -> PDF
2. Create Template -> next Step
3. Error

#### PHP/Apache/Browser Logs
´´´
2018-08-17 13:54:24.4733 [error] - SQLSTATE[HY000]: General error: 1364 Field 'header_content' doesn't have a default value
The SQL being executed was: INSERT INTO `a_yf_pdf` (`status`, `primary_name`, `secondary_name`, `module_name`, `metatags_status`, `meta_subject`, `meta_title`, `meta_author`, `meta_creator`, `meta_keywords`) VALUES (0, 'dfg', 'dfg', 'Vertrag', 1, '', '', '', '', '')
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'header_content' doesn't have a default value in /var/www/Yeti/vendor/yetiforce/yii2/db/Command.php:1258
Stack trace:
#0 /var/www/Yeti/vendor/yetiforce/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /var/www/Yeti/vendor/yetiforce/yii2/db/Command.php(1075): yii\db\Command->internalExecute('INSERT INTO `a_...')
#2 /var/www/Yeti/modules/Settings/PDF/models/Record.php(135): yii\db\Command->execute()
#3 /var/www/Yeti/modules/Settings/PDF/actions/Save.php(39): Settings_PDF_Record_Model::save(Object(Vtiger_PDF_Model), '1')
#4 /var/www/Yeti/include/main/WebUI.php(183): Settings_PDF_Save_Action->process(Object(App\Request))
#5 /var/www/Yeti/index.php(25): Vtiger_WebUI->process(Object(App\Request))
#6 {main}
´´´

I don't understand how this should even work. The table does't have any default values for many of these collumns even though no values are provided

**Comment by gerripeach** [comment]
Ticket can be closed. I had the wrong Database settings. sql_mode still had some values where yetifore requires no sql_modes.

Anyway... an idea for the yetiforce developers: It would be very helpful when the installer forces the user to use the correct settings.
I mean it doesn't matter for the software if you use http or https but it matters to use the right sql_mode.
The same thing applies to the password. Yetiforce needs user passwords which contain a capital letter, a number and a special char. So if I don't use a special char the installer only provides me with a little hint which is easy to oversee. Later on I get an error and I have to look thought the source code to find out whats wrong.
Overall this costs a lot of time.

So please rewrite the installer to point out any wrong values (password, settings, etc.)
