### ISSUE TITLE
Can't get RoundCube to work. 

### ISSUE THREAD

**Issue by one-use** [YetiForceCompany/YetiForceCRM#7707]
#### Issue
Can't get RoundCube to work. All settings seem to be correct yet not possible to log in. Mail-Auto Login User List section is empty. Willing to pay to YetiForce to have this fixed. 

#### Actual Behavior
Not login in. Error: Connection To Storage Server Failed

#### Expected Behavior
To be able to login in and use email facility

#### How to trigger the error

1.
2.
3.

#### Screenshot of configuration
The following modules/extensions are required to run Roundcube:

OK - PCRE
OK - DOM
OK - Session
OK - XML
OK - JSON
OK - PDO
The next couple of extensions are optional and recommended to get the best performance:

ERROR - FileInfo | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/book.fileinfo.php
OK - Libiconv
OK - Multibyte
OK - OpenSSL
OK - Mcrypt
OK - Intl
OK - Exif
Checking available databases
Check which of the supported extensions are installed. At least one of them is required.

OK - MySQL 
ERROR - PostgreSQL | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/ref.pdo-pgsql.php
OK - SQLite 
ERROR - SQLite (v2) | | http://www.php.net/manual/en/ref.pdo-sqlite.php
ERROR - SQL Server (SQLSRV) | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/ref.pdo-sqlsrv.php
ERROR - SQL Server (DBLIB) | Could be loaded. Please add in php.ini | http://www.php.net/manual/en/ref.pdo-dblib.php
Check for required 3rd party libs
This also checks if the include path is set correctly.

OK - PEAR
ERROR - Net_SMTP | Failed to load Net/SMTP.php | http://pear.php.net/package/Net_SMTP
ERROR - Net_IDNA2 | Failed to load Net/IDNA2.php | http://pear.php.net/package/Net_IDNA2
ERROR - Mail_mime | Failed to load Mail/mime.php | http://pear.php.net/package/Mail_mime
Checking php.ini/.htaccess settings
The following settings are required to run Roundcube:

OK - mbstring.func_overload
OK - suhosin.session.encrypt
The following settings are optional and recommended:

OK - allow_url_fopen
OK - date.timezone

#### PHP/Apache/Browser Logs
PHP ERROR LOG:
[12-Aug-2018 14:20:50 America/New_York] PHP Warning:  file_get_contents(https://github.com/YetiForceCompany/lib_PHPExcel/archive/0.0.0.zip): failed to open stream: HTTP request failed! HTTP/1.0 502 Bad Gateway
 in /home/b555776/intranet.one-use.lv/modules/Settings/ModuleManager/models/Library.php on line 120
[12-Aug-2018 14:25:54 America/New_York] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Zip.php on line 79
[12-Aug-2018 15:36:11 America/New_York] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Zip.php on line 84
[12-Aug-2018 15:37:21 America/New_York] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Zip.php on line 79
[12-Aug-2018 15:39:03 America/New_York] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Zip.php on line 79
[12-Aug-2018 15:41:31 America/New_York] PHP Warning:  rmdir(/home/b555776/intranet.one-use.lv/public_html/modules/OSSMail/roundcube//program/lib/Roundcube): Directory not empty in /home/b555776/intranet.one-use.lv/vtlib/Vtiger/Functions.php on line 617
[12-Aug-2018 15:41:31 America/New_York] PHP Warning:  rmdir(/home/b555776/intranet.one-use.lv/public_html/modules/OSSMail/roundcube//program/lib): Directory not empty in /home/b555776/intranet.one-use.lv/vtlib/Vtiger/Functions.php on line 617
[12-Aug-2018 15:41:31 America/New_York] PHP Warning:  rmdir(/home/b555776/intranet.one-use.lv/public_html/modules/OSSMail/roundcube//program): Directory not empty in /home/b555776/intranet.one-use.lv/vtlib/Vtiger/Functions.php on line 617
[12-Aug-2018 15:41:31 America/New_York] PHP Warning:  rmdir(/home/b555776/intranet.one-use.lv/public_html/modules/OSSMail/roundcube/): Directory not empty in /home/b555776/intranet.one-use.lv/vtlib/Vtiger/Functions.php on line 617
[12-Aug-2018 15:41:33 America/New_York] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Zip.php on line 79
[12-Aug-2018 15:42:02 America/New_York] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Zip.php on line 81
[12-Aug-2018 15:45:39 America/New_York] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Zip.php on line 79
[12-Aug-2018 15:46:13 America/New_York] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Zip.php on line 79
[12-Aug-2018 15:55:44 America/New_York] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Zip.php on line 79
[12-Aug-2018 16:20:07 America/New_York] PHP Deprecated:  Non-static method OSSMail_Record_Model::getEditableFields() should not be called statically in /home/b555776/intranet.one-use.lv/modules/OSSMail/models/Record.php on line 569
[12-Aug-2018 16:24:32 America/New_York] PHP Deprecated:  Non-static method OSSMail_Record_Model::getEditableFields() should not be called statically in /home/b555776/intranet.one-use.lv/modules/OSSMail/models/Record.php on line 569
[12-Aug-2018 16:26:50 America/New_York] PHP Deprecated:  Non-static method OSSMail_Record_Model::getEditableFields() should not be called statically in /home/b555776/intranet.one-use.lv/modules/OSSMail/models/Record.php on line 569
[12-Aug-2018 16:31:34 America/New_York] PHP Warning:  imap_append() expects parameter 1 to be resource, boolean given in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Mailer.php on line 476
[12-Aug-2018 16:31:34 America/New_York] PHP Warning:  imap_close() expects parameter 1 to be resource, boolean given in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Mailer.php on line 477
[12-Aug-2018 17:22:25 America/New_York] PHP Deprecated:  Non-static method OSSMail_Record_Model::getEditableFields() should not be called statically in /home/b555776/intranet.one-use.lv/modules/OSSMail/models/Record.php on line 569
[12-Aug-2018 17:30:46 America/New_York] PHP Deprecated:  Non-static method OSSMail_Record_Model::getEditableFields() should not be called statically in /home/b555776/intranet.one-use.lv/modules/OSSMail/models/Record.php on line 569
[12-Aug-2018 18:35:25 America/New_York] PHP Warning:  imap_append() expects parameter 1 to be resource, boolean given in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Mailer.php on line 476
[12-Aug-2018 18:35:25 America/New_York] PHP Warning:  imap_close() expects parameter 1 to be resource, boolean given in /home/b555776/intranet.one-use.lv/vendor/yetiforce/Mailer.php on line 477
[13-Aug-2018 04:23:50 America/New_York] PHP Fatal error:  Uncaught Error: Class 'Settings_CurrencyUpdate_Models_NBP_BankModel' not found in /home/b555776/intranet.one-use.lv/modules/Settings/CurrencyUpdate/models/Module.php:204
Stack trace:
#0 /home/b555776/intranet.one-use.lv/modules/Settings/CurrencyUpdate/views/Index.php(82): Settings_CurrencyUpdate_Module_Model->getSupportedCurrencies()
#1 /home/b555776/intranet.one-use.lv/include/main/WebUI.php(190): Settings_CurrencyUpdate_Index_View->process(Object(App\Request))
#2 /home/b555776/intranet.one-use.lv/index.php(25): Vtiger_WebUI->process(Object(App\Request))
#3 {main}
  thrown in /home/b555776/intranet.one-use.lv/modules/Settings/CurrencyUpdate/models/Module.php on line 204
[18-Aug-2018 07:37:36 America/New_York] PHP Parse error:  syntax error, unexpected ''=> '' (T_CONSTANT_ENCAPSED_STRING), expecting ']' in /home/b555776/intranet.one-use.lv/modules/ConsignmentNote/ConsignmentNote.php on line 66
[18-Aug-2018 07:37:39 America/New_York] PHP Parse error:  syntax error, unexpected ''=> '' (T_CONSTANT_ENCAPSED_STRING), expecting ']' in /home/b555776/intranet.one-use.lv/modules/ConsignmentNote/ConsignmentNote.php on line 66
[19-Aug-2018 04:36:43 America/New_York] PHP Warning:  Invalid argument supplied for foreach() in /home/b555776/intranet.one-use.lv/modules/IStorages/IStorages.php on line 169
[19-Aug-2018 08:36:56 America/New_York] PHP Deprecated:  Non-static method OSSMail_Record_Model::getEditableFields() should not be called statically in /home/b555776/intranet.one-use.lv/modules/OSSMail/models/Record.php on line 569
[19-Aug-2018 08:41:57 America/New_York] PHP Deprecated:  Non-static method OSSMail_Record_Model::getEditableFields() should not be called statically in /home/b555776/intranet.one-use.lv/modules/OSSMail/models/Record.php on line 569
[19-Aug-2018 08:44:01 America/New_York] PHP Deprecated:  Non-static method OSSMail_Record_Model::getEditableFields() should not be called statically in /home/b555776/intranet.one-use.lv/modules/OSSMail/models/Record.php on line 569
[19-Aug-2018 08:44:07 America/New_York] PHP Deprecated:  Non-static method OSSMail_Record_Model::getEditableFields() should not be called statically in /home/b555776/intranet.one-use.lv/modules/OSSMail/models/Record.php on line 569
[19-Aug-2018 09:23:30 America/New_York] PHP Deprecated:  Non-static method OSSMail_Record_Model::getEditableFields() should not be called statically in /home/b555776/intranet.one-use.lv/modules/OSSMail/models/Record.php on line 569

#### Your Environment

* YetiForce Version used: 4.3.0
* Browser name and version: Chrome
* Environment name and version:
* Operating System and version: Win 7 Ultimate

**Comment by PercyP** [comment]
Hi @one-use 

This I believe is your Mail settings. There are loads of posts about this. Check out my settings in the attached one they may help.

https://github.com/YetiForceCompany/YetiForceCRM/issues/7612
