### ISSUE TITLE
Error when creating any record

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#7914]
#### Issue

Tested on 4.4.35. After click save button when create record for any module get net errors:

`LBL_HANDLER_NOT_FOUND`

```
#0 modules/Vtiger/models/Record.php(432): App\EventHandler->trigger('EntityBeforeSav...')
#1 modules/Vtiger/actions/Save.php(90): Vtiger_Record_Model->save()
#2 modules/Vtiger/actions/Save.php(63): Vtiger_Save_Action->saveRecord(Object(App\Request))
#3 include/main/WebUI.php(183): Vtiger_Save_Action->process(Object(App\Request))
#4 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#5 public_html/index.php(11): require('/home/gitdevelo...')
#6 {main}
```

```
#0 [trace] Entering getColumnFields(Accounts) method ...
#1 [trace] Exiting getColumnFields method ...
#2 [trace] Entering App\Field::getFieldPermission: 6,accountname
#3 [trace] Entering App\Field::getFieldsPermissions: 6
#4 [trace] Entering App\Field::getFieldPermission: 6,accountname
#5 [trace] Entering App\Field::getFieldsPermissions: 6
#6 [trace] Entering App\Field::getFieldPermission: 6,account_no
#7 [trace] Entering App\Field::getFieldsPermissions: 6
#8 [trace] Entering App\Field::getFieldPermission: 6,account_no
#9 [trace] Entering App\Field::getFieldsPermissions: 6
#10 [trace] Entering App\Field::getFieldPermission: 6,account_id
#11 [trace] Entering App\Field::getFieldsPermissions: 6
#12 [trace] Entering App\Field::getFieldPermission: 6,account_id
#13 [trace] Entering App\Field::getFieldsPermissions: 6
#14 [trace] Entering App\Field::getFieldPermission: 6,industry
#15 [trace] Entering App\Field::getFieldsPermissions: 6
#16 [trace] Entering App\Field::getFieldPermission: 6,industry
#17 [trace] Entering App\Field::getFieldsPermissions: 6
#18 [trace] Entering App\Field::getFieldPermission: 6,accounttype
#19 [trace] Entering App\Field::getFieldsPermissions: 6
#20 [trace] Entering App\Field::getFieldPermission: 6,accounttype
#21 [trace] Entering App\Field::getFieldsPermissions: 6
#22 [trace] Entering App\Field::getFieldPermission: 6,assigned_user_id
#23 [trace] Entering App\Field::getFieldsPermissions: 6
#24 [trace] Entering App\Field::getFieldPermission: 6,assigned_user_id
#25 [trace] Entering App\Field::getFieldsPermissions: 6
#26 [trace] Entering App\Field::getFieldPermission: 6,was_read
#27 [trace] Entering App\Field::getFieldsPermissions: 6
#28 [trace] Entering App\Field::getFieldPermission: 6,was_read
#29 [trace] Entering App\Field::getFieldsPermissions: 6
#30 [trace] Entering App\Field::getFieldPermission: 6,shownerid
#31 [trace] Entering App\Field::getFieldsPermissions: 6
#32 [trace] Entering App\Field::getFieldPermission: 6,shownerid
#33 [trace] Entering App\Field::getFieldsPermissions: 6
#34 [trace] Entering App\Field::getFieldPermission: 6,modifiedby
#35 [trace] Entering App\Field::getFieldsPermissions: 6
#36 [trace] Entering App\Field::getFieldPermission: 6,modifiedby
#37 [trace] Entering App\Field::getFieldsPermissions: 6
#38 [trace] Entering App\Field::getFieldPermission: 6,active
#39 [trace] Entering App\Field::getFieldsPermissions: 6
#40 [trace] Entering App\Field::getFieldPermission: 6,active
#41 [trace] Entering App\Field::getFieldsPermissions: 6
#42 [trace] Entering App\Field::getFieldPermission: 6,accounts_status
#43 [trace] Entering App\Field::getFieldsPermissions: 6
#44 [trace] Entering App\Field::getFieldPermission: 6,accounts_status
#45 [trace] Entering App\Field::getFieldsPermissions: 6
#46 [trace] Entering App\Field::getFieldPermission: 6,private
#47 [trace] Entering App\Field::getFieldsPermissions: 6
#48 [trace] Entering App\Field::getFieldPermission: 6,private
#49 [trace] Entering App\Field::getFieldsPermissions: 6
#50 [trace] Entering App\Field::getFieldPermission: 6,email1
#51 [trace] Entering App\Field::getFieldsPermissions: 6
#52 [trace] Entering App\Field::getFieldPermission: 6,email1
#53 [trace] Entering App\Field::getFieldsPermissions: 6
#54 [trace] Entering App\Field::getFieldPermission: 6,phone
#55 [trace] Entering App\Field::getFieldsPermissions: 6
#56 [trace] Entering App\Field::getFieldPermission: 6,phone
#57 [trace] Entering App\Field::getFieldsPermissions: 6
#58 [trace] Entering App\Field::getFieldPermission: 6,email2
#59 [trace] Entering App\Field::getFieldsPermissions: 6
#60 [trace] Entering App\Field::getFieldPermission: 6,email2
#61 [trace] Entering App\Field::getFieldsPermissions: 6
#62 [trace] Entering App\Field::getFieldPermission: 6,otherphone
#63 [trace] Entering App\Field::getFieldsPermissions: 6
#64 [trace] Entering App\Field::getFieldPermission: 6,otherphone
#65 [trace] Entering App\Field::getFieldsPermissions: 6
#66 [trace] Entering App\Field::getFieldPermission: 6,website
#67 [trace] Entering App\Field::getFieldsPermissions: 6
#68 [trace] Entering App\Field::getFieldPermission: 6,website
#69 [trace] Entering App\Field::getFieldsPermissions: 6
#70 [trace] Entering App\Field::getFieldPermission: 6,fax
#71 [trace] Entering App\Field::getFieldsPermissions: 6
#72 [trace] Entering App\Field::getFieldPermission: 6,fax
#73 [trace] Entering App\Field::getFieldsPermissions: 6
#74 [trace] Entering App\Field::getFieldPermission: 6,emailoptout
#75 [trace] Entering App\Field::getFieldsPermissions: 6
#76 [trace] Entering App\Field::getFieldPermission: 6,emailoptout
#77 [trace] Entering App\Field::getFieldsPermissions: 6
#78 [trace] Entering App\Field::getFieldPermission: 6,no_approval
#79 [trace] Entering App\Field::getFieldsPermissions: 6
#80 [trace] Entering App\Field::getFieldPermission: 6,no_approval
#81 [trace] Entering App\Field::getFieldsPermissions: 6
#82 [trace] Entering App\Field::getFieldPermission: 6,phone_extra
#83 [trace] Entering App\Field::getFieldsPermissions: 6
#84 [trace] Entering App\Field::getFieldPermission: 6,phone_extra
#85 [trace] Entering App\Field::getFieldsPermissions: 6
#86 [trace] Entering App\Field::getFieldPermission: 6,fax_extra
#87 [trace] Entering App\Field::getFieldsPermissions: 6
#88 [trace] Entering App\Field::getFieldPermission: 6,fax_extra
#89 [trace] Entering App\Field::getFieldsPermissions: 6
#90 [trace] Entering App\Field::getFieldPermission: 6,otherphone_extra
#91 [trace] Entering App\Field::getFieldsPermissions: 6
#92 [trace] Entering App\Field::getFieldPermission: 6,otherphone_extra
#93 [trace] Entering App\Field::getFieldsPermissions: 6
#94 [trace] Entering App\Field::getFieldPermission: 6,balance
#95 [trace] Entering App\Field::getFieldsPermissions: 6
#96 [trace] Entering App\Field::getFieldPermission: 6,balance
#97 [trace] Entering App\Field::getFieldsPermissions: 6
#98 [trace] Entering App\Field::getFieldPermission: 6,sum_time
#99 [trace] Entering App\Field::getFieldsPermissions: 6
#100 [trace] Entering App\Field::getFieldPermission: 6,sum_time
#101 [trace] Entering App\Field::getFieldsPermissions: 6
#102 [trace] Entering App\Field::getFieldPermission: 6,payment_balance
#103 [trace] Entering App\Field::getFieldsPermissions: 6
#104 [trace] Entering App\Field::getFieldPermission: 6,payment_balance
#105 [trace] Entering App\Field::getFieldsPermissions: 6
#106 [trace] Entering App\Field::getFieldPermission: 6,inventorybalance
#107 [trace] Entering App\Field::getFieldsPermissions: 6
#108 [trace] Entering App\Field::getFieldPermission: 6,inventorybalance
#109 [trace] Entering App\Field::getFieldsPermissions: 6
#110 [trace] Entering App\Field::getFieldPermission: 6,discount
#111 [trace] Entering App\Field::getFieldsPermissions: 6
#112 [trace] Entering App\Field::getFieldPermission: 6,discount
#113 [trace] Entering App\Field::getFieldsPermissions: 6
#114 [trace] Entering App\Field::getFieldPermission: 6,creditlimit
#115 [trace] Entering App\Field::getFieldsPermissions: 6
#116 [trace] Entering App\Field::getFieldPermission: 6,creditlimit
#117 [trace] Entering App\Field::getFieldsPermissions: 6
#118 [trace] Entering App\Field::getFieldPermission: 6,last_invoice_date
#119 [trace] Entering App\Field::getFieldsPermissions: 6
#120 [trace] Entering App\Field::getFieldPermission: 6,last_invoice_date
#121 [trace] Entering App\Field::getFieldsPermissions: 6
#122 [trace] Entering App\Field::getFieldPermission: 6,isconvertedfromlead
#123 [trace] Entering App\Field::getFieldsPermissions: 6
#124 [trace] Entering App\Field::getFieldPermission: 6,isconvertedfromlead
#125 [trace] Entering App\Field::getFieldsPermissions: 6
#126 [trace] Entering App\Field::getFieldPermission: 6,verification
#127 [trace] Entering App\Field::getFieldsPermissions: 6
#128 [trace] Entering App\Field::getFieldPermission: 6,verification
#129 [trace] Entering App\Field::getFieldsPermissions: 6
#130 [trace] Entering App\Field::getFieldPermission: 6,created_user_id
#131 [trace] Entering App\Field::getFieldsPermissions: 6
#132 [trace] Entering App\Field::getFieldPermission: 6,created_user_id
#133 [trace] Entering App\Field::getFieldsPermissions: 6
#134 [trace] Entering App\Field::getFieldPermission: 6,employees
#135 [trace] Entering App\Field::getFieldsPermissions: 6
#136 [trace] Entering App\Field::getFieldPermission: 6,employees
#137 [trace] Entering App\Field::getFieldsPermissions: 6
#138 [trace] Entering App\Field::getFieldPermission: 6,createdtime
#139 [trace] Entering App\Field::getFieldsPermissions: 6
#140 [trace] Entering App\Field::getFieldPermission: 6,createdtime
#141 [trace] Entering App\Field::getFieldsPermissions: 6
#142 [trace] Entering App\Field::getFieldPermission: 6,modifiedtime
#143 [trace] Entering App\Field::getFieldsPermissions: 6
#144 [trace] Entering App\Field::getFieldPermission: 6,modifiedtime
#145 [trace] Entering App\Field::getFieldsPermissions: 6
#146 [trace] Entering App\Field::getFieldPermission: 6,closedtime
#147 [trace] Entering App\Field::getFieldsPermissions: 6
#148 [trace] Entering App\Field::getFieldPermission: 6,closedtime
#149 [trace] Entering App\Field::getFieldsPermissions: 6
#150 [trace] Entering App\Field::getFieldPermission: 6,products
#151 [trace] Entering App\Field::getFieldsPermissions: 6
#152 [trace] Entering App\Field::getFieldPermission: 6,services
#153 [trace] Entering App\Field::getFieldsPermissions: 6
#154 [trace] Entering App\Field::getFieldPermission: 6,crmactivity
#155 [trace] Entering App\Field::getFieldsPermissions: 6
#156 [trace] Entering App\Field::getFieldPermission: 6,crmactivity
#157 [trace] Entering App\Field::getFieldsPermissions: 6
#158 [trace] Entering App\Field::getFieldPermission: 6,ownership
#159 [trace] Entering App\Field::getFieldsPermissions: 6
#160 [trace] Entering App\Field::getFieldPermission: 6,ownership
#161 [trace] Entering App\Field::getFieldsPermissions: 6
#162 [trace] Entering App\Field::getFieldPermission: 6,vat_id
#163 [trace] Entering App\Field::getFieldsPermissions: 6
#164 [trace] Entering App\Field::getFieldPermission: 6,vat_id
#165 [trace] Entering App\Field::getFieldsPermissions: 6
#166 [trace] Entering App\Field::getFieldPermission: 6,annual_revenue
#167 [trace] Entering App\Field::getFieldsPermissions: 6
#168 [trace] Entering App\Field::getFieldPermission: 6,annual_revenue
#169 [trace] Entering App\Field::getFieldsPermissions: 6
#170 [trace] Entering App\Field::getFieldPermission: 6,registration_number_2
#171 [trace] Entering App\Field::getFieldsPermissions: 6
#172 [trace] Entering App\Field::getFieldPermission: 6,registration_number_2
#173 [trace] Entering App\Field::getFieldsPermissions: 6
#174 [trace] Entering App\Field::getFieldPermission: 6,siccode
#175 [trace] Entering App\Field::getFieldsPermissions: 6
#176 [trace] Entering App\Field::getFieldPermission: 6,siccode
#177 [trace] Entering App\Field::getFieldsPermissions: 6
#178 [trace] Entering App\Field::getFieldPermission: 6,registration_number_1
#179 [trace] Entering App\Field::getFieldsPermissions: 6
#180 [trace] Entering App\Field::getFieldPermission: 6,registration_number_1
#181 [trace] Entering App\Field::getFieldsPermissions: 6
#182 [trace] Entering App\Field::getFieldPermission: 6,legal_form
#183 [trace] Entering App\Field::getFieldsPermissions: 6
#184 [trace] Entering App\Field::getFieldPermission: 6,legal_form
#185 [trace] Entering App\Field::getFieldsPermissions: 6
#186 [trace] Entering App\Field::getFieldPermission: 6,buildingnumbera
#187 [trace] Entering App\Field::getFieldsPermissions: 6
#188 [trace] Entering App\Field::getFieldPermission: 6,buildingnumbera
#189 [trace] Entering App\Field::getFieldsPermissions: 6
#190 [trace] Entering App\Field::getFieldPermission: 6,localnumbera
#191 [trace] Entering App\Field::getFieldsPermissions: 6
#192 [trace] Entering App\Field::getFieldPermission: 6,localnumbera
#193 [trace] Entering App\Field::getFieldsPermissions: 6
#194 [trace] Entering App\Field::getFieldPermission: 6,addresslevel8a
#195 [trace] Entering App\Field::getFieldsPermissions: 6
#196 [trace] Entering App\Field::getFieldPermission: 6,addresslevel8a
#197 [trace] Entering App\Field::getFieldsPermissions: 6
#198 [trace] Entering App\Field::getFieldPermission: 6,addresslevel7a
#199 [trace] Entering App\Field::getFieldsPermissions: 6
#200 [trace] Entering App\Field::getFieldPermission: 6,addresslevel7a
#201 [trace] Entering App\Field::getFieldsPermissions: 6
#202 [trace] Entering App\Field::getFieldPermission: 6,addresslevel6a
#203 [trace] Entering App\Field::getFieldsPermissions: 6
#204 [trace] Entering App\Field::getFieldPermission: 6,addresslevel6a
#205 [trace] Entering App\Field::getFieldsPermissions: 6
#206 [trace] Entering App\Field::getFieldPermission: 6,addresslevel5a
#207 [trace] Entering App\Field::getFieldsPermissions: 6
#208 [trace] Entering App\Field::getFieldPermission: 6,addresslevel5a
#209 [trace] Entering App\Field::getFieldsPermissions: 6
#210 [trace] Entering App\Field::getFieldPermission: 6,addresslevel4a
#211 [trace] Entering App\Field::getFieldsPermissions: 6
#212 [trace] Entering App\Field::getFieldPermission: 6,addresslevel4a
#213 [trace] Entering App\Field::getFieldsPermissions: 6
#214 [trace] Entering App\Field::getFieldPermission: 6,addresslevel3a
#215 [trace] Entering App\Field::getFieldsPermissions: 6
#216 [trace] Entering App\Field::getFieldPermission: 6,addresslevel3a
#217 [trace] Entering App\Field::getFieldsPermissions: 6
#218 [trace] Entering App\Field::getFieldPermission: 6,addresslevel2a
#219 [trace] Entering App\Field::getFieldsPermissions: 6
#220 [trace] Entering App\Field::getFieldPermission: 6,addresslevel2a
#221 [trace] Entering App\Field::getFieldsPermissions: 6
#222 [trace] Entering App\Field::getFieldPermission: 6,addresslevel1a
#223 [trace] Entering App\Field::getFieldsPermissions: 6
#224 [trace] Entering App\Field::getFieldPermission: 6,addresslevel1a
#225 [trace] Entering App\Field::getFieldsPermissions: 6
#226 [trace] Entering App\Field::getFieldPermission: 6,poboxa
#227 [trace] Entering App\Field::getFieldsPermissions: 6
#228 [trace] Entering App\Field::getFieldPermission: 6,poboxa
#229 [trace] Entering App\Field::getFieldsPermissions: 6
#230 [trace] Entering App\Field::getFieldPermission: 6,buildingnumberb
#231 [trace] Entering App\Field::getFieldsPermissions: 6
#232 [trace] Entering App\Field::getFieldPermission: 6,buildingnumberb
#233 [trace] Entering App\Field::getFieldsPermissions: 6
#234 [trace] Entering App\Field::getFieldPermission: 6,localnumberb
#235 [trace] Entering App\Field::getFieldsPermissions: 6
#236 [trace] Entering App\Field::getFieldPermission: 6,localnumberb
#237 [trace] Entering App\Field::getFieldsPermissions: 6
#238 [trace] Entering App\Field::getFieldPermission: 6,addresslevel8b
#239 [trace] Entering App\Field::getFieldsPermissions: 6
#240 [trace] Entering App\Field::getFieldPermission: 6,addresslevel8b
#241 [trace] Entering App\Field::getFieldsPermissions: 6
#242 [trace] Entering App\Field::getFieldPermission: 6,addresslevel7b
#243 [trace] Entering App\Field::getFieldsPermissions: 6
#244 [trace] Entering App\Field::getFieldPermission: 6,addresslevel7b
#245 [trace] Entering App\Field::getFieldsPermissions: 6
#246 [trace] Entering App\Field::getFieldPermission: 6,addresslevel6b
#247 [trace] Entering App\Field::getFieldsPermissions: 6
#248 [trace] Entering App\Field::getFieldPermission: 6,addresslevel6b
#249 [trace] Entering App\Field::getFieldsPermissions: 6
#250 [trace] Entering App\Field::getFieldPermission: 6,addresslevel5b
#251 [trace] Entering App\Field::getFieldsPermissions: 6
#252 [trace] Entering App\Field::getFieldPermission: 6,addresslevel5b
#253 [trace] Entering App\Field::getFieldsPermissions: 6
#254 [trace] Entering App\Field::getFieldPermission: 6,addresslevel4b
#255 [trace] Entering App\Field::getFieldsPermissions: 6
#256 [trace] Entering App\Field::getFieldPermission: 6,addresslevel4b
#257 [trace] Entering App\Field::getFieldsPermissions: 6
#258 [trace] Entering App\Field::getFieldPermission: 6,addresslevel3b
#259 [trace] Entering App\Field::getFieldsPermissions: 6
#260 [trace] Entering App\Field::getFieldPermission: 6,addresslevel3b
#261 [trace] Entering App\Field::getFieldsPermissions: 6
#262 [trace] Entering App\Field::getFieldPermission: 6,addresslevel2b
#263 [trace] Entering App\Field::getFieldsPermissions: 6
#264 [trace] Entering App\Field::getFieldPermission: 6,addresslevel2b
#265 [trace] Entering App\Field::getFieldsPermissions: 6
#266 [trace] Entering App\Field::getFieldPermission: 6,addresslevel1b
#267 [trace] Entering App\Field::getFieldsPermissions: 6
#268 [trace] Entering App\Field::getFieldPermission: 6,addresslevel1b
#269 [trace] Entering App\Field::getFieldsPermissions: 6
#270 [trace] Entering App\Field::getFieldPermission: 6,poboxb
#271 [trace] Entering App\Field::getFieldsPermissions: 6
#272 [trace] Entering App\Field::getFieldPermission: 6,poboxb
#273 [trace] Entering App\Field::getFieldsPermissions: 6
#274 [trace] Entering App\Field::getFieldPermission: 6,buildingnumberc
#275 [trace] Entering App\Field::getFieldsPermissions: 6
#276 [trace] Entering App\Field::getFieldPermission: 6,buildingnumberc
#277 [trace] Entering App\Field::getFieldsPermissions: 6
#278 [trace] Entering App\Field::getFieldPermission: 6,localnumberc
#279 [trace] Entering App\Field::getFieldsPermissions: 6
#280 [trace] Entering App\Field::getFieldPermission: 6,localnumberc
#281 [trace] Entering App\Field::getFieldsPermissions: 6
#282 [trace] Entering App\Field::getFieldPermission: 6,addresslevel8c
#283 [trace] Entering App\Field::getFieldsPermissions: 6
#284 [trace] Entering App\Field::getFieldPermission: 6,addresslevel8c
#285 [trace] Entering App\Field::getFieldsPermissions: 6
#286 [trace] Entering App\Field::getFieldPermission: 6,addresslevel7c
#287 [trace] Entering App\Field::getFieldsPermissions: 6
#288 [trace] Entering App\Field::getFieldPermission: 6,addresslevel7c
#289 [trace] Entering App\Field::getFieldsPermissions: 6
#290 [trace] Entering App\Field::getFieldPermission: 6,addresslevel6c
#291 [trace] Entering App\Field::getFieldsPermissions: 6
#292 [trace] Entering App\Field::getFieldPermission: 6,addresslevel6c
#293 [trace] Entering App\Field::getFieldsPermissions: 6
#294 [trace] Entering App\Field::getFieldPermission: 6,addresslevel5c
#295 [trace] Entering App\Field::getFieldsPermissions: 6
#296 [trace] Entering App\Field::getFieldPermission: 6,addresslevel5c
#297 [trace] Entering App\Field::getFieldsPermissions: 6
#298 [trace] Entering App\Field::getFieldPermission: 6,addresslevel4c
#299 [trace] Entering App\Field::getFieldsPermissions: 6
#300 [trace] Entering App\Field::getFieldPermission: 6,addresslevel4c
#301 [trace] Entering App\Field::getFieldsPermissions: 6
#302 [trace] Entering App\Field::getFieldPermission: 6,addresslevel3c
#303 [trace] Entering App\Field::getFieldsPermissions: 6
#304 [trace] Entering App\Field::getFieldPermission: 6,addresslevel3c
#305 [trace] Entering App\Field::getFieldsPermissions: 6
#306 [trace] Entering App\Field::getFieldPermission: 6,addresslevel2c
#307 [trace] Entering App\Field::getFieldsPermissions: 6
#308 [trace] Entering App\Field::getFieldPermission: 6,addresslevel2c
#309 [trace] Entering App\Field::getFieldsPermissions: 6
#310 [trace] Entering App\Field::getFieldPermission: 6,addresslevel1c
#311 [trace] Entering App\Field::getFieldsPermissions: 6
#312 [trace] Entering App\Field::getFieldPermission: 6,addresslevel1c
#313 [trace] Entering App\Field::getFieldsPermissions: 6
#314 [trace] Entering App\Field::getFieldPermission: 6,poboxc
#315 [trace] Entering App\Field::getFieldsPermissions: 6
#316 [trace] Entering App\Field::getFieldPermission: 6,poboxc
#317 [trace] Entering App\Field::getFieldsPermissions: 6
#318 [trace] Entering App\Field::getFieldPermission: 6,description
#319 [trace] Entering App\Field::getFieldsPermissions: 6
#320 [trace] Entering App\Field::getFieldPermission: 6,description
#321 [trace] Entering App\Field::getFieldsPermissions: 6
#322 [trace] Entering App\Field::getFieldPermission: 6,attention
#323 [trace] Entering App\Field::getFieldsPermissions: 6
#324 [trace] Entering App\Field::getFieldPermission: 6,attention
#325 [trace] Entering App\Field::getFieldsPermissions: 6
#326 [error] Handler not found, class: Vtiger_SocialMedia_Handler | entityBeforeSave
#327 [error] LBL_HANDLER_NOT_FOUND
App\Exceptions\AppException: LBL_HANDLER_NOT_FOUND in app/EventHandler.php:299
Stack trace:
#0 modules/Vtiger/models/Record.php(432): App\EventHandler->trigger('EntityBeforeSav...')
#1 modules/Vtiger/actions/Save.php(90): Vtiger_Record_Model->save()
#2 modules/Vtiger/actions/Save.php(63): Vtiger_Save_Action->saveRecord(Object(App\Request))
#3 include/main/WebUI.php(183): Vtiger_Save_Action->process(Object(App\Request))
#4 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#5 public_html/index.php(11): require('/home/gitdevelo...')
#6 {main}
```

**Comment by areksolek** [comment]
In the current development version works properly. The error occurred temporarily.
