### ISSUE TITLE
Merging not working

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8226]
#### Issue

Any attempts to try record merging was fault

![no merge](https://user-images.githubusercontent.com/8545791/46615120-2e3de380-cb20-11e8-870e-c330464f7e0e.gif)
 
```
jquery.js:9600 POST https://gitdeveloper.yetiforce.com/index.php 406 (ERR_NOT_ALLOWED_VALUE||)
send @ jquery.js:9600
ajax @ jquery.js:9206
_request @ Connector.js:133
request @ Connector.js:36
container.find.on @ VM7529:19
dispatch @ jquery.js:5183
elemData.handle @ jquery.js:4991
Connector.js:124 YetiForce debug mode!!!
params.error @ Connector.js:124
fire @ jquery.js:3268
fireWith @ jquery.js:3398
done @ jquery.js:9307
(anonymous) @ jquery.js:9548
load (async)
send @ jquery.js:9567
ajax @ jquery.js:9206
_request @ Connector.js:133
request @ Connector.js:36
container.find.on @ VM7529:19
dispatch @ jquery.js:5183
elemData.handle @ jquery.js:4991
Connector.js:125 Error: ERR_NOT_ALLOWED_VALUE|| 
------------------------------------------------------------------------------------------------------------------------------------------------------
Trace:
------------------------------------------------------------------------------------------------------------------------------------------------------
#0 app/Request.php(223): App\Purifier::purifyByType(false, 'Integer')
#1 modules/Vtiger/actions/MergeRecords.php(34): App\Request->getArray('records', 'Integer')
#2 include/main/WebUI.php(183): Vtiger_MergeRecords_Action->process(Object(App\Request))
#3 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#4 public_html/index.php(11): require('/home/gitdevelo...')
#5 {main} 
------------------------------------------------------------------------------------------------------------------------------------------------------
Params:
------------------------------------------------------------------------------------------------------------------------------------------------------
{
	"data": {
		"module": "SQuotes",
		"action": "MergeRecords",
		"records": "[3416,3417]/",
		"record": "3416",
		"subject": "3417",
		"salesprocessid": "3416",
		"scalculationsid": "3416",
		"accountid": "3416",
		"category": "3416",
		"squotes_status": "3416",
		"assigned_user_id": "3416",
		"shownerid": "3416",
		"company": "3416",
		"valid_until": "3416",
		"": "3416",
		"description": "3416",
		"attention": "3416",
		"response_time": "3416",
		"sum_time": "3416",
		"crmactivity": "3416",
		"buildingnumbera": "3416",
		"localnumbera": "3416",
		"addresslevel8a": "3416",
		"addresslevel7a": "3416",
		"addresslevel6a": "3416",
		"addresslevel5a": "3416",
		"addresslevel4a": "3416",
		"addresslevel3a": "3416",
		"addresslevel2a": "3416",
		"addresslevel1a": "3416",
		"poboxa": "3416"
	},
	"type": "POST",
	"jsonp": false,
	"dataType": "json",
	"url": "index.php"
}
```

#### How to trigger the error

1.
2.
3.

#### Your Environment

* YetiForce Version used: dev 4.4.47
* Browser name and version:
* Environment name and version:
* Operating System and version:

**Comment by vovpff** [comment]
@bpabiszczak is it possible to merge advanced modules records?

**Comment by vovpff** [comment]
@TomaszQr @bpabiszczak waht about #7480

**Comment by rezeyle1** [comment]
I have the same problem.
