### ISSUE TITLE
PDF generation error

### ISSUE THREAD

**Issue by vovpff** [YetiForceCompany/YetiForceCRM#8908]
#### Issue

Error then clicking Generate for PDF

#### Actual Behavior

```
Fatal error: Uncaught Error: Call to undefined method Vtiger_ItemNumber_InventoryField::initialize() in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/InventoryField.php:156 Stack trace: #0 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/InventoryField.php(69): Vtiger_InventoryField_Model->getInventoryFieldInstance(Array) #1 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/app/TextParser/ProductsTableLongVersion.php(32): Vtiger_InventoryField_Model->getFields(true) #2 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/app/TextParser.php(1026): App\TextParser\ProductsTableLongVersion->process() #3 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/app/TextParser.php(366): App\TextParser->custom(Array) #4 [internal function]: App\TextParser->App\{closure}(Array) #5 /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/app/TextParser.php(369): preg_replace_callback('/\\$\\((\\w+) : ([...', Object(Cl in /home/gitdevelop/domains/gitdeveloper.yetiforce.com/public_html/modules/Vtiger/models/InventoryField.php on line 156
```

#### Expected Behavior

PDF should be appear

#### How to trigger the error

1. Add PDF template
2. Click Generate

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce         |  dev 4.4.113.
| Web server      | 
| PHP                 | 
| Browser           | 
| Operating System | 
| Database         |

**Comment by rafalpospiech** [comment]
This issue was fixed already
