### ISSUE TITLE
 Illegal value in field language (pl) when creating new user

### ISSUE THREAD

**Issue by technologiegalwaniczne** [YetiForceCompany/YetiForceCRM#8909]
#### Issue
When clickin Add record in Users module I am getting the following error: 

Illegal value in field language (pl)
#0 modulesVtigeruitypesBase.php(51): Vtiger_Languages_UIType->validate('pl', true)
#1 modulesVtigerviewsEdit.php(99): Vtiger_Base_UIType->setValueFromRequest(Object(App\Request), Object(Users_Record_Model))
#2 modulesUsersviewsPreferenceEdit.php(73): Vtiger_Edit_View->process(Object(App\Request))
#3 includemainWebUI.php(190): Users_PreferenceEdit_View->process(Object(App\Request))
#4 index.php(25): Vtiger_WebUI->process(Object(App\Request))
#5 {main}

#0 [info] SELECT * FROM `vtiger_field` WHERE `tabid`=29 || yii\db\Command::query
#1 [info] Opening DB connection: mysql:host=tegal.home.pl;dbname=10580019_yf;port=3306 || yii\db\Connection::open
#2 [info] SELECT * FROM `vtiger_tab` || yii\db\Command::query
#3 [info] SELECT * FROM `vtiger_entityname` || yii\db\Command::query
#4 [info] SHOW FULL COLUMNS FROM `u_yf_browsinghistory` || yii\db\Command::query
#5 [info] SELECT
    kcu.constraint_name,
    kcu.column_name,
    kcu.referenced_table_name,
    kcu.referenced_column_name
FROM information_schema.referential_constraints AS rc
JOIN information_schema.key_column_usage AS kcu ON
    (
        kcu.constraint_catalog = rc.constraint_catalog OR
        (kcu.constraint_catalog IS NULL AND rc.constraint_catalog IS NULL)
    ) AND
    kcu.constraint_schema = rc.constraint_schema AND
    kcu.constraint_name = rc.constraint_name
WHERE rc.constraint_schema = database() AND kcu.table_schema = database()
AND rc.table_name = 'u_yf_browsinghistory' AND kcu.table_name = 'u_yf_browsinghistory' || yii\db\Command::query
#6 [info] INSERT INTO `u_yf_browsinghistory` (`userid`, `date`, `title`, `url`) VALUES (5, '2018-12-17 09:46:08', 'Users Create', 'index.php?module=Users&parent=Settings&view=Edit') || yii\db\Command::execute
#7 [info] SELECT * FROM `vtiger_links` || yii\db\Command::query
#8 [info] SELECT * FROM `s_yf_companies` WHERE `default`=1 || yii\db\Command::query
#9 [info] SELECT * FROM `u_yf_browsinghistory` WHERE `userid`=5 ORDER BY `id` DESC LIMIT 20 || yii\db\Command::query
#10 [info] SELECT * FROM `vtiger_actionmapping` || yii\db\Command::query
#11 [info] SELECT * FROM `u_yf_chat_messages` LIMIT 20 || yii\db\Command::query
#12 [info] SELECT * FROM `vtiger_settings_blocks` WHERE (`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL) ORDER BY `sequence` || yii\db\Command::query
#13 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=16) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#14 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=1) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#15 [info] SELECT * FROM `vtiger_settings_blocks` WHERE `blockid`=1 || yii\db\Command::query
#16 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=2) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#17 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=11) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#18 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=12) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#19 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=13) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#20 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=7) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#21 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=14) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#22 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=5) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#23 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=15) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#24 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=8) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#25 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=4) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#26 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=3) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#27 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=6) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#28 [info] SELECT * FROM `vtiger_settings_field` WHERE ((`blockid`=9) AND (`active`=0)) AND ((`name` NOT IN ('LBL_AUDIT_TRAIL', 'LBL_SYSTEM_INFO', 'LBL_PROXY_SETTINGS', 'LBL_DEFAULT_MODULE_VIEW', 'LBL_FIELDFORMULAS', 'LBL_FIELDS_ACCESS', 'LBL_MAIL_MERGE', 'NOTIFICATIONSCHEDULERS', 'INVENTORYNOTIFICATION', 'ModTracker', 'LBL_WORKFLOW_LIST', 'LBL_TOOLTIP_MANAGEMENT')) AND ((`admin_access` LIKE '%,5,%') OR (`admin_access` IS NULL))) ORDER BY `sequence` || yii\db\Command::query
#29 [info] SELECT * FROM `vtiger_field` WHERE `tabid`=83 || yii\db\Command::query
#30 [info] SELECT `vtiger_field`.* FROM `vtiger_field` LEFT JOIN `vtiger_blocks` ON vtiger_field.block = vtiger_blocks.blockid WHERE `vtiger_field`.`tabid`=83 ORDER BY `vtiger_blocks`.`sequence`, `vtiger_field`.`sequence` || yii\db\Command::query
#31 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=258 || yii\db\Command::query
#32 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=259 || yii\db\Command::query
#33 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=260 || yii\db\Command::query
#34 [info] SELECT * FROM `vtiger_ws_fieldtype` || yii\db\Command::query
#35 [info] SELECT * FROM `vtiger_role` WHERE `roleid`='H10' || yii\db\Command::query
#36 [info] SELECT `u_yf_announcement`.`announcementid` AS `id`, `u_yf_announcement`.`subject` AS `subject`, `vtiger_crmentity`.`description` AS `description`, `vtiger_crmentity`.`smownerid` AS `assigned_user_id`, `vtiger_crmentity`.`createdtime` AS `createdtime`, `u_yf_announcement`.`is_mandatory` AS `is_mandatory` FROM `u_yf_announcement` INNER JOIN `vtiger_crmentity` ON u_yf_announcement.announcementid = vtiger_crmentity.crmid WHERE ((`vtiger_crmentity`.`deleted`=0)) AND (`announcementstatus`='PLL_PUBLISHED') || yii\db\Command::query
#37 [info] SELECT DISTINCT `vtiger_tab`.* FROM `vtiger_field` INNER JOIN `vtiger_tab` ON vtiger_tab.tabid = vtiger_field.tabid WHERE ((((quickcreate = 0) OR (quickcreate = 2)) AND (`vtiger_tab`.`presence` <> 1)) AND (`vtiger_tab`.`type` <> 1)) AND (`vtiger_tab`.`name` NOT IN ('ModComments', 'PriceBooks', 'Events')) || yii\db\Command::query
#38 [info] SELECT `name`, `value` FROM `yetiforce_mail_config` WHERE `type`='mailIcon' || yii\db\Command::query
#39 [info] SELECT `rcuser_id`, `crmuser_id`, `username`, `password` FROM `roundcube_users_autologin` INNER JOIN `roundcube_users` ON roundcube_users_autologin.rcuser_id = roundcube_users.user_id WHERE `roundcube_users_autologin`.`crmuser_id`=5 || yii\db\Command::query
#40 [info] SELECT `vtiger_field`.* FROM `vtiger_field` LEFT JOIN `vtiger_blocks` ON vtiger_field.block = vtiger_blocks.blockid WHERE `vtiger_field`.`tabid`=29 ORDER BY `vtiger_blocks`.`sequence`, `vtiger_field`.`sequence` || yii\db\Command::query
#41 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=77 || yii\db\Command::query
#42 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=118 || yii\db\Command::query
#43 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=78 || yii\db\Command::query
#44 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=79 || yii\db\Command::query
#45 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=82 || yii\db\Command::query
#46 [info] SELECT * FROM `vtiger_blocks` WHERE `blockid`=83 || yii\db\Command::query
#47 [info] SELECT `hour_formatid`, `hour_format` FROM `vtiger_hour_format` ORDER BY `sortorderid` || yii\db\Command::query
#48 [info] SELECT `start_hourid`, `start_hour` FROM `vtiger_start_hour` ORDER BY `sortorderid` || yii\db\Command::query
#49 [info] SELECT `vtiger_field`.*, `vtiger_profile2field`.`readonly`, `vtiger_profile2field`.`visible` FROM `vtiger_field` INNER JOIN `vtiger_profile2field` ON vtiger_profile2field.fieldid = vtiger_field.fieldid INNER JOIN `vtiger_def_org_field` ON vtiger_def_org_field.fieldid = vtiger_field.fieldid WHERE ((`vtiger_field`.`tabid`=29) AND (`vtiger_profile2field`.`visible`=0) AND (`vtiger_def_org_field`.`visible`=0) AND (`vtiger_field`.`presence` IN (0, 2))) AND (`vtiger_profile2field`.`profileid`=1) GROUP BY `vtiger_field`.`fieldid`, `vtiger_profile2field`.`readonly`, `vtiger_profile2field`.`visible` || yii\db\Command::query
#50 [info] SELECT `label` FROM `vtiger_language` WHERE `prefix`='pl' || yii\db\Command::query
#51 [error] ERR_ILLEGAL_FIELD_VALUE||language||pl => modulesVtigeruitypesLanguages.php:26

#### Actual Behavior
Cannot add new or modify an existing user. 

#### Expected Behavior
New user form.

#### How to trigger the error
![crm_problem](https://user-images.githubusercontent.com/29600665/50076324-a6d8b480-01e1-11e9-994d-304b06b9d54b.gif)

#### Your Environment

| Environment    | Version / Name |
| ---------------- | -------------- |
| YetiForce         |  4.3.0
| PHP                 | 7.0.28

**Comment by technologiegalwaniczne** [comment]
Is there any chance to get this right without updating YF? I am getting some errors when trying to apply the update and would like to avoid that right now. Any workaround would be apprecieated.
