### ISSUE TITLE
delete this

### ISSUE THREAD

**Issue by maeglin4** [YetiForceCompany/YetiForceCRM#9949]
please delete this

**Comment by maeglin4** [comment]
[16-Mar-2019 15:55:04 America/New_York] PHP Fatal error:  Uncaught SensioLabs\Security\Exception\RuntimeException: An error occurred: Could not resolve host: security.sensiolabs.org. in /home/expertbatiment/public_html/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/CurlCrawler.php:75
Stack trace:
#0 /home/expertbatiment/public_html/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/BaseCrawler.php(48): SensioLabs\Security\Crawler\CurlCrawler->doCheck('/home/expertbat...', '/home/expertbat...')
#1 /home/expertbatiment/public_html/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/DefaultCrawler.php(31): SensioLabs\Security\Crawler\BaseCrawler->check('/home/expertbat...')
#2 /home/expertbatiment/public_html/vendor/sensiolabs/security-checker/SensioLabs/Security/SecurityChecker.php(52): SensioLabs\Security\Crawler\DefaultCrawler->check('/home/expertbat...')
#3 /home/expertbatiment/public_html/app/SystemWarnings/Security/Dependencies.php(22): SensioLabs\Security\SecurityChecker->check('/home/expertbat...')
#4 /home/expertbatiment/ in /home/expertbatiment/public_html/vendor/sensiolabs/security-checker/SensioLabs/Security/Crawler/CurlCrawler.php on line 75
